server.id.error=服务器ID是无效的
server.name.null=服务器名字是无效的！
server.group.null=服务器分组名字是无效的
jsp.server.title=服务器管理列表
jsp.server.gong=共
jsp.server.serverNum=个服务器, 总计
jsp.server.page=页
jsp.server.id=服务器ID
jsp.server.name=服务器名字
jsp.server.groupname=平台标识
jsp.server.worldIp=WorldIP
jsp.server.worldPort=WorldPort
jsp.server.ishefu=是否合服
jsp.server.hefutime=合服时间
jsp.server.hefuserver=合到目标区
jsp.server.deal=操作
jsp.server.mod=修改
jsp.server.del=删除
jsp.server.delConfirm=确认删除？
jsp.server.sumbit=提交
jsp.server.combine1=请输入y,确认需要把
jsp.server.combine2=合到
jsp.server.combine3=吗？
jsp.server.delete=请输入y,确认删除
jsp.server.deleteOk=删除成功
jsp.server.pageNum=页数
jsp.server.perPage=每页
jsp.query=查询
jsp.server.areaid=服务器ID
jsp.server.moreareaid=服务器的唯一编号
jsp.server.morename=服务器的名字
jsp.server.worldMore=与GM后台相连的World服IP
jsp.server.worldPortMore=与GM后台相连的World服端口
jsp.server.groupmore=服务器所属的平台分组标识
jsp.add=添加
jsp.combine=合区管理
jsp.combine.currentId=当前合服的区
jsp.combine.currentIdMore=当前要关闭的游戏服ID
jsp.combine.destId=目标区号
jsp.combine.destIdMore=合服目标服ID，只能填写一个
jsp.combine.add=添加合区
jsp.main.title=天之禁API服务器
jsp.login.logo=天之禁API服务器
jsp.login.user=用户名
jsp.login.pass=密码
jsp.login.checkCode=验证码
jsp.login.newpass=新密码
jsp.login.cpass=确认密码
jsp.login=登录
jsp.login.logout=注销
jsp.login.success=登陆成功
jsp.login.fauilre=登陆失败，请检查账号密码
jsp.login.changepwd=修改密码
jsp.login.noPermission=你没有任何权限
jsp.login.nullusername=用户名不为空
jsp.login.nullpassword=密码不为空
jsp.login.minpasswordlength=密码不能少于12个字符
jsp.login.passwordnofigure=密码必须含有数字
jsp.login.passwordnoletter=密码必须含有字母
jsp.login.passwordnocharacter=密码必须含有特殊字符
jsp.login.nullcheckcode=验证码不为空
jsp.login.checkcodewrong=验证码不正确，请重新输入
jsp.login.cpwdnoeqpwd=确认密码和输入密码不同，请重新输入
jsp.login.changepicture=看不清，换一个
jsp.user.id=您的ID是
jsp.dblog.title=日志库管理列表
jsp.dblog.dblogurl=日志库的地址
jsp.dblog.dblogname=日志库的数据库名
jsp.dblog.dbloguser=日志库用户
jsp.dblog.dblogpass=日志库密码
jsp.dblog.serverlist=日志库服务区列表
jsp.dblog.dblogurlmore=后台查询的日志库地址，格式：ip(或域名):端口 如127.0.0.1:5849
jsp.dblog.namemore=后台查询的日志库的名字
jsp.dblog.usermore=后台查询的日志库用户名
jsp.dblog.passmore=后台查询的日志库密码
jsp.dblog.serverlistmore=查询的日志库的含有数据的区服列表
dblog.serveripPort.null=日志数据库的地址为空
dblog.dbname.null=日志数据库名字为空
dblog.dbuser.null=日志数据库用户名为空
dblog.dbpass.null=日志数据库库的密码为空
db.insert.success=插入新的数据成功了
db.insert.failure=插入新的记录失败了
db.update.success=更新数据成功
db.update.failure=更新数据失败了
dblog.delete.tishi1=删除id:
dblog.delete.tishi2=失败了
server.worldIp.null=后台连接游戏服地址为空
server.worldport.null=后台连接游戏服端口为空
server.other.error=其它参数错误
server.insert.success=插入最新服务器列表成功，最新ID：
server.combine.destIdError=合区的服务器ID指定失败了!
server.combine.noDblog=目标服务器没有日志数据库配置 !
server.combine.noExist=当前操作的区是不存在的
server.combine.destIdnoExist=目标区已经不存在server表中
server.combine.destIdIsHefu=目标区是已经合过服了，不到往此服务器合
jsp.server.combineclear=清理合服数据
jsp.server.isClearCombine=请输入y，确认清理当前服的合服信息
server.combine.not=当前服并没有合服操作
server.combine.clearUpLogerror=更新日志库失败了！
jsp.dblog.serverType=服务类型
jsp.dblog.game=游戏服
jsp.dblog.login=登录服
jsp.dblog.loginLog=登录日志服
jsp.dblog.serverTypeMore=选择添加的数据库连接的游戏服类型
jsp.server.test=测试连接
jsp.server.testsuccess=测试连接成功！
jsp.run.command=需要执行的命令
jsp.run.cparams=需要执行的参数
jsp.server.testServer=测试服
jsp.server.normalServer=正式服
jsp.server.serverType=服务器类型
jsp.server.serverIsShow=充值服务器列表是否有效
jsp.server.serverTypeMore=选择是游戏服还是正式服
jsp.user.langswitch=切换语言
jsp.user.curlang=当前语言
jsp.language.ko_KR=韩语（韩国）
jsp.language.vi_VN=越南语（越南）
jsp.language.zh_CN=简体中文（中国）
jsp.language.zh_SG=简体中文（新马）
jsp.language.zh_TW=繁体中文（台湾）
jsp.language.zh_EN=英文
server.all.choice=全选
forbid.dataerror=数据不符合要求！
forbid.chat.userId=账号ID
forbid.chat.createTime=创建时间
forbid.chat.endtime=禁言结束时间(秒)
forbid.chat.backCrname=操作创建人
forbid.chat.reason=操作理由
forbid.chat.dealServer=送到的区服
forbid.chat.tiao=条
forbid.chat.jiechu=解除禁言
forbid.chat.currpage=当前第
forbid.chat.currpageend=页，每页
forbid.chat.deal=禁言
forbid.chat.showrecent=近期记录
forbid.chat.to=对 
forbid.chat.say=说:
forbid.chat.crime=违规类型
forbid.chat.crime1=黑色产业(工作室、拉人和广告等)
forbid.chat.crime2=不良信息(黄赌毒等违规信息)
forbid.chat.type=处罚类型
forbid.chat.type1=工作室禁言
forbid.chat.type2=全文替换禁言
forbid.chat.type3=关键字替换禁言
forbid.chat.type4=常规禁言
forbid.chat.type5=隐形禁言
forbid.chat.type6=隔离禁言
forbid.chat.endtimeInfo=此处填写以秒为单位，大于0为禁言秒值  填写 0为不禁言， -1 为永久禁言
forbid.chat.userInfo=此禁言是禁止此账号下的所有角色不能向其它玩家发送世界聊天信息！
forbid.user.type=封号类型
forbid.user.type1=账号
forbid.user.type2=IP
forbid.user.type3=机器码
forbid.user.type4=IMEI
forbid.user.type5=MAC
forbid.user.userid=封号目标
forbid.user.endtime=封号结束时间
forbid.user.ls=发送LS服务器编号
forbid.user.lsResult=LS返回结果
forbid.user.jiechu=解除封号
forbid.user.add=添加封号
forbid.user.conerror=封号条件错误
forbid.user.con=,封号条件
forbid.user.result=,结果
forbid.needwrite=必填
forbid.user.conditioninfo=屏蔽的账号数据，可以是IP、账号名、mac地址、imei和机器唯一码(例如:{9527cd86-9f3d-4449-a605-a57bb7fd5e87})  
forbid.user.endtimeInfo=封号的结束日期
forbid.user.con1=Ip：
forbid.user.con2=账号名：
forbid.user.con3=mac地址：
forbid.user.con4=imei：
forbid.user.con5=机器唯一码：
kick.player=角色ID
kick.playerInfo=请填写要踢下线的角色ID
kick.deal=踢人
announce.qiyong=启用
announce.stop=停用
announce.overtime=已过期
announce.timesOver=已结束
announce.isDelete=已删除
announce.query.noRecord=查询的记录不存在！
announce.imedia.reasonNull=理由不能为空，请检查！
announce.imedia.serverNull=没有选择服务器
announce.imedia.serverNotsendBegin=选择的服务器还有(
announce.imedia.serverNotsendEnd=)不在当前选择的组中！
announce.imedia.saveFailure=\n保存当前公告失败了！
announce.imedia.saveOk=\n保存当前公告成功!
announce.add.timesError=时间调节参数错误！
announce.add.endTimeError=时间格式错误！
announce.add.contentError=公告的内容不能为空
announce.add.saveSuccess=添加新的公告成功!
announce.add.savefailure=添加新的公告内容失败了！
announce.do.success=处理成功！
announce.do.failure=处理失败！
forbid.deal.exceptionError=进行数据操作时，发生异常错误
forbid.deal.noRecord=解除禁言当前记录不存在！
forbid.deal.chatTonot=解除禁言成功
forbid.deal.userNoRecord=封号记录并不存在
forbid.deal.userUpdaterError=封号解除更新记录失败
forbid.deal.userToSuccess=解除封号成功
forbid.deal.ls=登录服(
forbid.deal.updateResult=)更新禁言表结果：
forbid.deal.insertResult=)插入禁言表结果：
forbid.deal.reason=原因：
mail.list.state1=待批准
mail.list.state2=发送未成功
mail.list.state3=发送成功
mail.list.state4=不予发送
mail.list.state5=已删除
mail.list.operate1=一键发送
mail.list.operate2=准予发送
mail.list.operate3=不予发送
mail.list.operate4=删除
mail.server.notexist=请求查询的服务器并不存在
mail.query.roleidsError=请填写正确的角色ID值！
mail.query.roleidsCorrect=输入的角色都有效！
mail.query.roleidsCheck=请先验证角色ID填写是否正确！
mail.query.begin=的角色ID在
mail.query.end=服中找不到！
mail.save.paramError=提交的邮件参数有错
mail.save.updateError=保存数据失败了，通知运维检查后台连接！
mail.save.success=保存成功！请审核后发送
mail.send.serverNull=不能指定到达具体的游戏服！
mail.admin.updateError=更新邮件记录失败了！
mail.admin.updateSuccess=更新邮件成功！
mail.admin.updateNoRecord=邮件记录已经不存在了
mail.admin.notallow=标记此邮件不允许发送！
mail.onekey.success=一键发送功能处理成功！
announce.jsp.content=内容
announce.jsp.existTime=有效日期
announce.jsp.existTimeInfo=格式: 年-月-日 时:分:秒 注意去掉末尾的空格 例如 2012-12-21 12:30:00
announce.jsp.playTimes=播放次数
announce.jsp.playTimesInfo=填 0 则不受此条件限制
announce.jsp.timeStep=时间频率(分)
announce.jsp.timeStepInfo=(单位：分) 选择此公告往服务器发送的频率
announce.jsp.state=状态
announce.jsp.state1=启用
announce.jsp.state2=停用
announce.jsp.stateinfo=选择当前公告是启用还是停用
announce.jsp.type=显示位置
announce.jsp.typeInfo=选择设置显示是跑马灯还是聊天框
announce.jsp.type1=跑马灯
announce.jsp.type2=聊天框
announce.jsp.create=创建
jsp.loading=数据努力加载中.....
jsp.dealing=执行中
announce.jsp.sureUpdate=确定要操作此公告吗？
announce.jsp.sureDelete=确定要删除吗？
announce.jsp.createAnnouce=新增公告
announce.jsp.openlist=启用列表
announce.jsp.closeList=禁用列表
announce.jsp.createtime=创建时间
announce.jsp.createUser=创建者
announce.jsp.sendServers=发送的服务器
announce.jsp.begintime=开始日期
announce.jsp.accountbegintime=结算开始时间
announce.jsp.endtime=结束日期
announce.jsp.accountendtime=结算结束时间
announce.jsp.totalTimes=总次数
announce.jsp.currTimes=当前次数
announce.jsp.nextFlushdate=下一次满足时间
announce.jsp.gunInfo=输入滚动公告文本,不支持url
announce.jsp.chatInfo=内容中加入url的写法: 前往{官网;http://xx.qmr.com} = 前往<span style=\"text-decoration: underline;\">官网</span>
announce.jsp.sureimedia=确定发送即时公告?一经发出,即时生效,不可修改
jsp.parse.content=粘贴内容
jsp.save=保存
jsp.push=发布
announce.jsp.loading=公告历史加载中......
jsp.server=服务器
jsp.roleId.check=检查角色ID有效性
jsp.roleId.Info=支持输入多个角色ID[','分隔]
mail.jsp.reason=发送原因
mail.jsp.sitemInfo=发物品,不带附件物品，本邮件会直接发送。如有物品则需要审核页处理
mail.jsp.titlemax=最大20个字
mail.jsp.contentmax=最大1000个字
mail.jsp.fujian=附件
mail.jsp.adminUser=确认者
mail.jsp.adminTime=确认时间
mail.jsp.demo=备注
mail.jsp.mailState=邮件状态
mail.jsp.operate=操作
mail.waitlist=待处理邮件
mail.minelist=自己的邮件
mail.historylist=历史邮件
jsp.choice=选择
jsp.user.nopermission=没有权限
item.top.di=第
item.top.dangci=档次
item.top.ming=名
item.top.ci=次
item.top.continuousRechargeCount=累积充值目标天数
item.top.activityReward=活动奖励
item.top.rechargeRequire=每日充值额
item.top.reachamount=_达到数量
item.attr.str0=白板
item.attr.str1=数量
item.attr.str2=绑定
item.attr.str3=过期
item.attr.str4=强化
item.attr.str5=升星
item.attr.str6=职业
item.attr.str7=未知2
item.attr.str8=未知3
item.attr2.str0=白板
item.attr2.str1=数量
item.attr2.str2=绑定
item.attr2.str3=过期
item.attr2.str4=掉落权重
item.attr2.str5=职业
item.attr2.str6=未知2
item.attr2.str7=未知3
item.attr2.str8=未知4
error.type=错误类型
error.title=错误标题
error.content=错误内容
error.current.value=当前产生的数量值
error.deal=是否发送邮件
errot.report=错误报告
whitelist.deal.success=白名单操作成功
whitelist.condition=白名单条件
whitelist.allowLogin=允许登陆
whitelist.notallowLogin=不允许登陆
jsp.prev.page=上一页
jsp.next.page=下一页
whitelist.jsp.condition=条件
whitelist.jsp.type=类型
whitelist.jsp.ip=创建人的IP
whitelist.jsp.loginback=登陆服返回的结果
whitelist.add=新增
user.emptyobj=空对象
user.userisexist=用户名已存在
user.useripillegal=用户IP非法
user.userorpwdnull=用户名或密码为空
user.usernoexist=用户名不存在
user.userisdeleted=用户已被禁用
user.pwderror=密码错误
user.pwdupdatesuccess=密码修改成功
user.cannotdelcuruser=不能删除当前用户!!
user.pwdisnotsame=两次输入的密码不一致
user.pwdcannotempty=密码不能为空
user.pwdlengtherror=密码长度错误
user.ipforbid=IP地址被禁用
jsp.datareload.title=后台数据加载
jsp.dataload.loadfail=加载失败
jsp.dataload.loadfinish=加载完成
jsp.dataload.reload=重新加载
jsp.dataload.data=后台数据
jsp.dataload.action=操作
jsp.dataload.gamedata=策划数据库相关,读取gameData.js文件
jsp.dataload.configFile=原因码、道具信息和语言包等配置文件信息加载，读取reason.properties、languageNo.properties和language文件夹下语言包文件
jsp.dataload.logfield=日志查询实体字段配置信息(主要用于游戏日志库查询时实体字段的配置),读取fields.js文件
jsp.dataload.ls=登录服相关数据(LS数据库信息、LS日志服数据库连接、LS相应渠道信息),读取t_dblog表、t_server表和lslog.js文件
jsp.dataload.dblogservers=平台相关游戏服务器信息(主要用于提供平台相关的服务器信息，读取t_dblog和t_server表)
jsp.dataload.annouce=公告数据读取
jsp.dataload.servers=游戏服务器信息读取(主要用于与游戏服(world)进行交互时参数提供，读取t_server表)
jsp.menu.title=菜单列表
jsp.menu.addsuccess=添加成功
jsp.menu.continueadd=继续添加
jsp.menu.sure=确认操作?
jsp.menu.yes=是
jsp.menu.no=否
recharge.siderror=服务器Id错误
recharge.rechargegolderror=充值金额错误
recharge.serverdbnotfound=后台异常,未找到服务器DB信息
recharge.roleiderror=角色ID验证失败
recharge.servernotfound=后台异常,未找到服务器信息
recharge.rechargefail=充值失败
jsp.recharge.title=充值页面
jsp.recharge.groupname=平台名:
jsp.recharge.rechargefinish=充值完成
jsp.recharge.serverchoose=服务器选择
jsp.recharge.roleid=角色ID
jsp.recharge.playermustbeonline=请确保角色在线，否则充值无效
jsp.recharge.rechargegold=充值金额
jsp.recharge.recharge=充值
jsp.recharge.serverId=服务器id
jsp.recharge.roleId=角色id
jsp.recharge.rechargeGold=充值蓝钻数量
jsp.recharge.createUser=创建者
jsp.recharge.platformName=角色渠道
jsp.recharge.createTime=创建时间
jsp.recharge.rechargeState=充值状态
jsp.recharge.approvalUser=审核者
jsp.recharge.approvalTime=审核时间
jsp.recharge.rechargeReason=充值理由
jsp.recharge.rechargeSend=是否发送
jsp.recharge.rechargeWait=待审核
jsp.recharge.rechargeSuccess=成功
jsp.recharge.rechargeFail=失败
jsp.recharge.trueSend=准予发送
jsp.recharge.falseSend=不予发送
jsp.menu.open=开启
jsp.menu.close=关闭
jsp.login.tips=温馨提示：因部分浏览器对本站支持不佳，建议用户使用较高版本浏览器进行访问
manager.platform=平台:
manager.getchannelerror=获取渠道失败!
jsp.whitelist.lschoose=登录服选择
jsp.itemDictionary.title=道具词典
jsp.itemDictionary.itemId=道具ID
jsp.itemDictionary.itemName=道具名称
jsp.itemDictionary.itemMax=道具最大重叠数
jsp.itemDictionary.itemList=道具列表
jsp.itemDictionary.loadItemList=加载所有道具说明
jsp.decGold.title=扣除元宝
jsp.decGold.chooseServer=服务器选择
jsp.decGold.tip=扣除元宝请谨慎操作
jsp.decGold.roleId=角色ID
jsp.decGold.type=类型
jsp.decGold.num=数量
jsp.decGold.reason=操作原因
jsp.decGold.decGold=扣除
jsp.decGold.success=操作成功
jsp.activity.rechargeRank=充值排行
jsp.activity.consumeRank=消费排行
jsp.activity.lowerRank=最低排名
jsp.activity.higherRank=最高排名
jsp.headIcon.playerId=玩家id
jsp.headIcon.image=上传头像
jsp.headIcon.date=上传日期
jsp.headIcon.state=审核状态
jsp.headIcon.operation=操作
jsp.headIcon.wait=待审核
jsp.headIcon.all=全部
jsp.headIcon.headNum=个头像，总计
jsp.headIcon.nowstate=当前状态
jsp.headIcon.switch=审核开关
jsp.headIcon.onePass=一键审核
jsp.headIcon.pass=审核