#后台与登录服
REQUESTLOGINSERVERKEY=753509031ad2ced8d284f0f20f4277a8
#登录服日志库库名(角色查询API会使用到) 例：tzj_login_log
loginLogName=tzj_login_log
#gameID 对应游戏的ID
gameID=1001
#部署环境 dev pro
env=dev
#GM后台连接地址 例：http://127.0.0.1:8080/GameManager
GMUrl=http://155.212.166.16:8080/GameManager
#自动开服检查间隔时间（单位：分）
AutoOpenInterval=1