#商城购买日志
fields.shopbuy.platfrom=渠道
fields.shopbuy.sid=区服ID
fields.shopbuy.roleId=角色ID
fields.shopbuy.rolelevel=等级
fields.shopbuy.shopId=商城ID
fields.shopbuy.sellId=商品编号
fields.shopbuy.moneyType=货币ID 
fields.shopbuy.moneyNum=货币数量
fields.shopbuy.itemModelId=商品道具ID
fields.shopbuy.realNum=道具数量
fields.shopbuy.buyTimes=购买次数
fields.shopbuy.reasonCode=原因码 
fields.shopbuy.FromSrc=商品标签页ID
fields.shopbuy.time=时间
fields.shopbuy.action=唯一标识
#元宝变化日志
fields.goldchange.platformName=渠道
fields.goldchange.sid=区服ID
fields.goldchange.userid=用户ID
fields.goldchange.roleId=角色ID
fields.goldchange.rolelevel=角色等级
fields.goldchange.beforenum=之前数量
fields.goldchange.afternum=之后数量
fields.goldchange.changenum=变化数量
fields.goldchange.reason=原因
fields.goldchange.loginip=IP
fields.goldchange.time=时间
fields.goldchange.actionId=唯一标识
#活跃奖励日志
fields.activereward.sid=区服ID
fields.activereward.playerId=角色ID
fields.activereward.curActiveValue=当前活跃值
fields.activereward.rewardActiveValue=奖励活跃值
fields.activereward.rewardItems=奖励物品
fields.activereward.time=时间
#活动领取日志
fields.activityget.sid=区服ID
fields.activityget.roleid=角色ID
fields.activityget.activityId=活动ID
fields.activityget.parms=领取状态
fields.activityget.actionId=唯一标识
fields.activityget.time=时间
fields.activityget.acType=活动类型
fields.activityget.acName=活动名称
#公会动态日志
fields.guildchange.platform=平台名
fields.guildchange.createSid=区服
fields.guildchange.userId=用户ID
fields.guildchange.roleId=角色ID
fields.guildchange.roleName=角色名
fields.guildchange.guildId=公会ID
fields.guildchange.guildName=公会名
fields.guildchange.actId=被操作角色ID
fields.guildchange.actName=被操作角色名
fields.guildchange.type=操作类型
fields.guildchange.time=时间
#公会成员日志
fields.guildmember.guildId=公会ID
fields.guildmember.roleId=角色ID
fields.guildmember.otherId=踢人者ID
fields.guildmember.type=类型
fields.guildmember.time=时间
#聊天日志
fields.chat.sid=区服ID
fields.chat.roleId=角色ID
fields.chat.sendName=角色名
fields.chat.content=聊天内容
fields.chat.channel=聊天类型
fields.chat.receRoleId=消息接收者ID
fields.chat.time=时间
#充值成功日志
fields.rechargesuccess.platformName=渠道
fields.rechargesuccess.sid=区服ID
fields.rechargesuccess.userId=用户ID
fields.rechargesuccess.roleId=角色ID
fields.rechargesuccess.roleName=角色名
fields.rechargesuccess.os=操作系统
fields.rechargesuccess.orderId=订单ID
fields.rechargesuccess.oid=渠道订单ID
fields.rechargesuccess.amount=充值金额
fields.rechargesuccess.gold=充值元宝
fields.rechargesuccess.gift=赠送绑元
fields.rechargesuccess.currency=币种
fields.rechargesuccess.type=充值步骤
fields.rechargesuccess.reason=充值理由
fields.rechargesuccess.parm=描述
fields.rechargesuccess.time=时间
fields.rechargesuccess.actionId=唯一标识
fields.rechargesuccess.level=等级
fields.rechargesuccess.itemId=商品ID
#排行榜日志
fields.rank.date=记录时间
fields.rank.rankKind=排行榜类别 
fields.rank.rank=名次 
fields.rank.roleId=角色Id
fields.rank.roleName=角色名 
fields.rank.rankData=排行数据
#绑定元宝变化日志
fields.bindgoldchange.platformName=渠道
fields.bindgoldchange.sid=区服ID
fields.bindgoldchange.roleId=角色ID
fields.bindgoldchange.rolelevel=角色等级
fields.bindgoldchange.beforenum=之前数量
fields.bindgoldchange.afternum=之后数量
fields.bindgoldchange.changenum=变化数量
fields.bindgoldchange.reason=原因
fields.bindgoldchange.loginip=IP
fields.bindgoldchange.time=时间
fields.bindgoldchange.actionId=唯一标识
#副本进入日志
fields.instanceEnter.sid=区服
fields.instanceEnter.roleId=角色ID
fields.instanceEnter.name=角色名
fields.instanceEnter.level=角色等级
fields.instanceEnter.cloneId=副本ID
fields.instanceEnter.clonename=副本名称
fields.instanceEnter.auto=自动扫荡
fields.instanceEnter.time=时间
#副本奖励日志
fields.copymap.platform=渠道
fields.copymap.sid=区服
fields.copymap.playerid=角色ID
fields.copymap.name=角色名
fields.copymap.zonemodelid=副本类型
fields.copymap.isSuccess=是否胜利
fields.copymap.copyOverTime=完成时间
fields.copymap.score=得分
fields.copymap.reward=奖励
fields.copymap.dcReward=档次奖励
fields.copymap.type=其他类型
fields.copymap.actionId=唯一标识
fields.copymap.time=时间
#角色改名日志
fields.changerolename.userId=用户ID
fields.changerolename.playerId=角色ID
fields.changerolename.sid=区服
fields.changerolename.oldName=原名
fields.changerolename.newName=新名
fields.changerolename.time=时间
#玩家结婚日志
fields.marriage.marriageId=婚礼ID
fields.marriage.type=婚礼类型
fields.marriage.ownId=发起者
fields.marriage.oppositeId=受邀者
fields.marriage.action=结婚操作
fields.marriage.time=时间
#玩家交易日志
fields.trade.actionId=交易唯一标识
fields.trade.sellRoleId=卖方角色ID
fields.trade.sellRoleName=卖方角色名
fields.trade.num=交易数量
fields.trade.buyplat=买方交易平台
fields.trade.sellplat=卖方交易平台
fields.trade.buyRoleId=买方角色ID
fields.trade.buyRoleName=买方角色名
fields.trade.marketId=交易市场名称
fields.trade.secret=交易密码
fields.trade.itemModelId=交易道具名称
fields.trade.coinNum=交易货币数量
fields.trade.coinType=货币类型
fields.trade.state=交易状态
fields.trade.time=时间
#城市争夺战日志
fields.cityBattleOver.cityId=城市ID
fields.cityBattleOver.sid=区服
fields.cityBattleOver.camp=阵营ID
fields.cityBattleOver.roleId=角色ID
fields.cityBattleOver.name=角色名
fields.cityBattleOver.unionId=王府ID
fields.cityBattleOver.unionName=王府名
fields.cityBattleOver.guildId=公会ID
fields.cityBattleOver.guildName=公会名
fields.cityBattleOver.score=积分
fields.cityBattleOver.time=时间
#王府创建日志
fields.kpCreate.sid=区服ID
fields.kpCreate.kpId=王府ID
fields.kpCreate.kpName=王府名称
fields.kpCreate.kpNotice=王府公告
fields.kpCreate.guildId=公会ID
fields.kpCreate.GuildName=公会名称
fields.kpCreate.roleId=角色ID
fields.kpCreate.roleName=角色名称
fields.kpCreate.icon=旗帜图标
fields.kpCreate.actionId=唯一标识
fields.kpCreate.time=时间
#王府成员增加日志
fields.kpMemberAdd.sid=区服ID
fields.kpMemberAdd.kpId=王府ID
fields.kpMemberAdd.kpName=王府名称
fields.kpMemberAdd.guildId=公会ID
fields.kpMemberAdd.guildName=公会名称
fields.kpMemberAdd.dealRoleId=操作者角色ID
fields.kpMemberAdd.dealRoleName=操作者角色名
fields.kpMemberAdd.kpOfficer=操作者角色官职
fields.kpMemberAdd.time=时间
#王府成员删除日志
fields.kpMemberDel.sid=区服ID
fields.kpMemberDel.kpId=王府ID
fields.kpMemberDel.kpName=王府名称
fields.kpMemberDel.guildId=公会ID
fields.kpMemberDel.guildName=公会名称
fields.kpMemberDel.dealRoleId=操作者角色ID
fields.kpMemberDel.dealRoleName=操作者角色名
fields.kpMemberDel.kpOfficer=操作者角色官职
fields.kpMemberDel.gongxian=王府贡献
fields.kpMemberDel.time=时间
#王府捐献
fields.kpDonation.kpId=王府ID
fields.kpDonation.kpName=王府名称
fields.kpDonation.guildId=公会ID
fields.kpDonation.guildName=公会名称
fields.kpDonation.dealRoleId=操作者角色ID
fields.kpDonation.dealRoleName=操作者角色名
fields.kpDonation.gongxian=贡献值
fields.kpDonation.type=贡献类型
fields.kpDonation.actionId=唯一标识
fields.kpDonation.time=时间
#王府贡献
fields.kpGongXian.sid=区服ID
fields.kpGongXian.kpId=王府ID
fields.kpGongXian.kpName=王府名称
fields.kpGongXian.dealRoleId=操作者角色ID
fields.kpGongXian.dealRoleName=操作者角色名
fields.kpGongXian.power=操作者权限
fields.kpGongXian.prevProsper=变化前的值
fields.kpGongXian.prosper=变化后的值
fields.kpGongXian.changeNum=变化值
fields.kpGongXian.reason=原因码
fields.kpGongXian.actionId=唯一标识
fields.kpGongXian.time=时间
#王府基本信息修改日志
fields.kpBaseInfoModify.sid=区服ID
fields.kpBaseInfoModify.kpId=王府ID
fields.kpBaseInfoModify.kpName=王府名称
fields.kpBaseInfoModify.guildId=公会ID
fields.kpBaseInfoModify.guildName=公会名称
fields.kpBaseInfoModify.dealRoleId=操作者角色ID
fields.kpBaseInfoModify.dealRoleName=操作者角色名
fields.kpBaseInfoModify.power=操作者官职
fields.kpBaseInfoModify.notice=王府公告
fields.kpBaseInfoModify.isAuto=自动同意加入
fields.kpBaseInfoModify.limitLevel=最小加入等级
fields.kpBaseInfoModify.icon=旗帜图标
fields.kpBaseInfoModify.dealType=修改类型
fields.kpBaseInfoModify.actionId=唯一标识
fields.kpBaseInfoModify.time=时间
#王府官职变动日志 
fields.kpOffice.kpId=王府ID
fields.kpOffice.kpName=王府名称
fields.kpOffice.dealRoleId=操作者角色ID
fields.kpOffice.dealRoleName=操作者角色名
fields.kpOffice.dealPower=操作者官职
fields.kpOffice.destGuild=目标角色公会
fields.kpOffice.destRoleId=目标角色ID
fields.kpOffice.destRoleName=目标角色名
fields.kpOffice.destPrePower=目标旧官职
fields.kpOffice.destPower=目标新官职
fields.kpOffice.time=时间
#王府升级日志
fields.kpUpLevel.sid=区服ID
fields.kpUpLevel.kpId=王府ID
fields.kpUpLevel.kpName=王府名称
fields.kpUpLevel.dealRoleId=操作者角色ID
fields.kpUpLevel.dealRoleName=操作者角色名
fields.kpUpLevel.power=操作者官职
fields.kpUpLevel.prevLevel=变化前等级
fields.kpUpLevel.level=变化后等级
fields.kpUpLevel.payProsper=花费贡献值
fields.kpUpLevel.reason=原因码
fields.kpUpLevel.actionId=唯一标识
fields.kpUpLevel.time=时间
#Boss存活时间日志
fields.copymapbosssurvivelog.dieTime=死亡时间
fields.copymapbosssurvivelog.serviveTime=boss存活时间[毫秒]
fields.copymapbosssurvivelog.copyMapId=副本Id
fields.copymapbosssurvivelog.cupyMapName=副本名字
fields.copymapbosssurvivelog.copyModelId=副本模组ID
fields.copymapbosssurvivelog.serverId=服务器ID
fields.copymapbosssurvivelog.time=时间
#跨服进入日志
fields.crossCloneEnter.name=角色名字
fields.crossCloneEnter.roleId=角色ID
fields.crossCloneEnter.time=记录时间
fields.crossCloneEnter.fightId=副本房间ID
fields.crossCloneEnter.modelId=副本模板ID
fields.crossCloneEnter.campNo=战场阵营编号
fields.crossCloneEnter.platsid=平台区服标识
#跨服结束日志
fields.crossCloneEnd.modelId=副本模组ID
fields.crossCloneEnd.conditeStr=玩家分数值
fields.crossCloneEnd.roomId=副本房间ID
fields.crossCloneEnd.failure=失败说明
fields.crossCloneEnd.CreateTime=副本创建时间
fields.crossCloneEnd.success=成功说明
fields.crossCloneEnd.time=记录时间
#跨服战角色日志
fields.crossWarRole.sid=服务器ID
fields.crossWarRole.campNo=战场阵营编号
fields.crossWarRole.baoMingTime=报名时间
fields.crossWarRole.fightID=战斗ID
fields.crossWarRole.roleId=角色ID
fields.crossWarRole.roleName=角色名字
fields.crossWarRole.time=时间
fields.crossWarRole.level=角色等级
#战斗奖励创建日志
fields.flightRewardCreate.platSid=平台+服务器ID
fields.flightRewardCreate.Data=数据[待解析]
fields.flightRewardCreate.time=时间
#战斗奖励删除日志
fields.flightRewardDelete.platSid=平台+服务器ID
fields.flightRewardDelete.Data=数据[待解析]
fields.flightRewardDelete.time=时间
#战斗房间创建日志
fields.flightRoomCreate.roleName=角色名字
fields.flightRoomCreate.power=要求战斗力值
fields.flightRoomCreate.time=时间
fields.flightRoomCreate.fid=战场编号
fields.flightRoomCreate.roleId=角色ID
fields.flightRoomCreate.isAuto=是否自动
fields.flightRoomCreate.modelId=副本ID号
fields.flightRoomCreate.sid=服务器ID
fields.flightRoomCreate.plat=平台
#战斗房间删除日志
fields.flightRoomDelete.modelId=副本ID号
fields.flightRoomDelete.time=时间
fields.flightRoomDelete.fid=战场编号
fields.flightRoomDelete.typeRange=战场类型
fields.flightRoomDelete.data=玩家信息
fields.flightRoomDelete.state=房间状态
#玩家进入房间日志
fields.playerEnterRoom.power=玩家的战力
fields.playerEnterRoom.roleId=角色ID
fields.playerEnterRoom.modelId=副本ID号
fields.playerEnterRoom.sid=服务器编号
fields.playerEnterRoom.sizeNo=阵营编号
fields.playerEnterRoom.level=角色等级(阶数和等级计算出来)
fields.playerEnterRoom.plat=平台标识
fields.playerEnterRoom.roleName=角色名字
fields.playerEnterRoom.fid=战场编号
#悬赏任务日志
fileds.battlefieldTaskFinish.pageTitle=悬赏任务日志
fileds.battlefieldTaskFinish.getBittlefieldLogCountList=统计玩家每日进入悬赏任务的次数
fileds.battlefieldTaskFinish.getAllBittlefieldLogList=查看悬赏任务日志
fileds.battlefieldTaskFinish.row=行数
fileds.battlefieldTaskFinish.userId=玩家账号ID
fileds.battlefieldTaskFinish.roleId=角色ID
fileds.battlefieldTaskFinish.roleName=角色名称
fileds.battlefieldTaskFinish.platformName=平台名称
fileds.battlefieldTaskFinish.sid=服务器ID
fileds.battlefieldTaskFinish.taskCount=当前任务所处第几环
fileds.battlefieldTaskFinish.modelName=任务名称
fileds.battlefieldTaskFinish.finishType=完成的方式
fileds.battlefieldTaskFinish.finishType.common=普通完成
fileds.battlefieldTaskFinish.finishType.supperFinish=一键完成
fileds.battlefieldTaskFinish.finishType.optimalSupperFinish=最优一键完成（一键完成所有）
fileds.battlefieldTaskFinish.finishType.giveup=通过放弃
fileds.battlefieldTaskFinish.count=参与次数
fileds.battlefieldTaskFinish.time=参与时间
fileds.battlefieldTaskFinish.camp=阵营
#精英boss日志
fileds.eliteBoss.pageTitle=精英boss日志
fileds.eliteBoss.getEliteBossCountList=统计玩家每日进入精英boss的次数
fileds.eliteBoss.getAllEliteBossLogList=查看精英boss日志
fileds.eliteBoss.row=行数
fileds.eliteBoss.userId=玩家账号ID
fileds.eliteBoss.roleId=角色ID
fileds.eliteBoss.roleName=角色名称
fileds.eliteBoss.eliteBossName=精英boss名称
fileds.eliteBoss.time=参与时间
fileds.eliteBoss.count=参与次数
fileds.eliteBoss.camp=阵营
#绑定金币日志
fileds.moneyChange.pageTile=绑定金币日志
fileds.moneyChange.getLogList=查看绑定金币日志
fileds.moneyChange.userId=玩家账号ID
fileds.moneyChange.sid=服务器ID
fileds.moneyChange.platformName=平台名称
fileds.moneyChange.roleId=角色ID
fileds.moneyChange.roleName=角色名称
fileds.moneyChange.roleLevel=角色等级
fileds.moneyChange.actionId=唯一标识
fileds.moneyChange.moneyType=货币类型
fileds.moneyChange.beforenum=之前数量
fileds.moneyChange.afternum=之后数量
fileds.moneyChange.changenum=变化数量
fileds.moneyChange.reason=变化原因
fileds.moneyChange.time=时间
fileds.moneyChange.loginip=访问IP
#荣誉值和军功日志
fileds.zhenqiAndTie.pageTile=荣誉值和军功日志
fileds.zhenqiAndTie.getLogList=查看荣誉值和军功日志
fileds.zhenqiAndTie.userId=玩家账号ID
fileds.zhenqiAndTie.sid=服务器ID
fileds.zhenqiAndTie.platformName=平台名称
fileds.zhenqiAndTie.roleId=角色ID
fileds.zhenqiAndTie.roleName=角色名称
fileds.zhenqiAndTie.roleLevel=角色等级
fileds.zhenqiAndTie.actionId=唯一标识
fileds.zhenqiAndTie.moneyType=货币类型
fileds.zhenqiAndTie.beforenum=之前数量
fileds.zhenqiAndTie.afternum=之后数量
fileds.zhenqiAndTie.changenum=变化数量
fileds.zhenqiAndTie.reason=变化原因
fileds.zhenqiAndTie.time=时间
fileds.zhenqiAndTie.loginip=访问IP
#其它货币日志
fileds.coin.pageTile=其它货币日志
fileds.coin.getLogList=查看其它货币日志
fileds.coin.userId=玩家账号ID
fileds.coin.sid=服务器ID
fileds.coin.platformName=平台名称
fileds.coin.roleId=角色ID
fileds.coin.roleName=角色名称
fileds.coin.roleLevel=角色等级
fileds.coin.actionId=唯一标识
fileds.coin.moneyType=货币类型
fileds.coin.beforenum=之前数量
fileds.coin.afternum=之后数量
fileds.coin.changenum=变化数量
fileds.coin.reason=变化原因
fileds.coin.time=时间
fileds.coin.loginip=访问IP
#主线任务任务日志
fileds.mainTask.pageTitle=主线任务日志
fileds.mainTask.getMainTaskCountList=统计玩家每日完成主线任务的次数
fileds.mainTask.getAllMainTaskLogList=查看主线任务日志
fileds.mainTask.getMainTaskRoleCountList=统计每个主线任务完成的角色数
fileds.mainTask.row=行数
fileds.mainTask.userId=玩家账号ID
fileds.mainTask.roleId=角色ID
fileds.mainTask.roleName=角色名称
fileds.mainTask.platformName=平台名称
fileds.mainTask.sid=服务器ID
fileds.mainTask.fshmoney=完成任务时的金币数
fileds.mainTask.fshmodelID=完成任务时的任务ID
fileds.mainTask.fshmodelName=完成任务时的任务名称
fileds.mainTask.fshlevel=完成任务时的等级
fileds.mainTask.fshonlineTime=完成任务时的在线时间
fileds.mainTask.accmoney=接下一任务的金币数
fileds.mainTask.accmodelName=接下一任务的名称
fileds.mainTask.acclevel=接下一任务的等级
fileds.mainTask.acconlineTime=接下一任务的在线时间
fileds.mainTask.count=参与次数
fileds.mainTask.time=参与时间
fileds.mainTask.roleCount=参与角色数
#装备培养
fileds.equipStreng.pageTitle=装备培养日志
fileds.equipStreng.getAllEquipStrengLog=查看装备培养日志
fileds.equipStreng.getEquipStrengCountList=按天统计每个玩家对应每一个装备培养的次数
fileds.equipStreng.getEquipStrengAllCountList=按天统计每个玩家装备培养的总次数
fileds.equipStreng.row=行数
fileds.equipStreng.userId=玩家账号ID
fileds.equipStreng.roleId=角色ID
fileds.equipStreng.roleName=角色名称
fileds.equipStreng.modelid1=培养装备模型ID
fileds.equipStreng.modelid2=材料装备模型ID
fileds.equipStreng.equipId1=培养装备唯一ID
fileds.equipStreng.equipId2=材料装备唯一ID
fileds.equipStreng.actioinId=唯一标识
fileds.equipStreng.platformName=平台名称
fileds.equipStreng.sid=服务器ID
fileds.equipStreng.time=参与时间
fileds.equipStreng.count=培养次数
fileds.equipStreng.groupNo=阵营
fileds.equipStreng.expend=消耗材料
#装备升星
fileds.equipUpStar.pageTitle=装备升星日志
fileds.equipUpStar.getAllEquipUpStarLog=查看装备升星日志
fileds.equipUpStar.getEquipUpStarCountList=按天统计每个玩家对应每一个部位升星的次数
fileds.equipUpStar.getEquipUpStarAllCountList=按天统计每个玩家装备升星的总次数
fileds.equipUpStar.row=行数
fileds.equipUpStar.userId=玩家账号ID
fileds.equipUpStar.roleId=角色ID
fileds.equipUpStar.roleName=角色名称
fileds.equipUpStar.part=升星部位
fileds.equipUpStar.startlv=升星前等级
fileds.equipUpStar.endlv=升星后等级
fileds.equipUpStar.actioinId=唯一标识
fileds.equipUpStar.platformName=平台名称
fileds.equipUpStar.sid=服务器ID
fileds.equipUpStar.time=参与时间
fileds.equipUpStar.count=培养次数
fileds.equipUpStar.groupNo=阵营
fileds.equipUpStar.expend=消耗材料
#玩家坐骑、翅膀、宠物统计
fileds.roleCollection.pageTitle=玩家收集统计
fileds.roleCollection.collectList=玩家收集坐骑、翅膀、宠物数据统计
fileds.roleCollection.collectHorses=收集坐骑数
fileds.roleCollection.collectWings=收集翅膀数
fileds.roleCollection.collectPets=收集宠物数
fileds.roleCollection.userId=玩家账号ID
fileds.roleCollection.roleId=角色ID
fileds.roleCollection.roleName=角色名称
fileds.roleCollection.platformName=渠道名称
fileds.roleCollection.date=统计截止日期
#VIP变化日志
fileds.vipChangeLog.roleId=角色ID
fileds.vipChangeLog.roleLevel=等级
fileds.vipChangeLog.startlv=VIP变化前等级
fileds.vipChangeLog.endlv=VIP变化后等级
fileds.vipChangeLog.time=时间
fileds.vipChangeLog.sid=区服ID
fileds.vipChangeLog.channelId=渠道ID
#王者对决赛日志
fileds.kingMonthReward.title=王者对决赛奖励日志
fileds.kingMonthReward.season=赛季
fileds.kingMonthReward.rank=名次
fileds.kingMonthReward.userId=账号id
fileds.kingMonthReward.roleId=角色id
fileds.kingMonthReward.roleName=角色名
fileds.kingMonthReward.platformName=渠道
fileds.kingMonthReward.reward=奖励内容