#commonlogbean
logentity.commonlogbean.time=时间
logentity.commonlogbean.roleId=角色ID
logentity.commonlogbean.roleName=角色名

#chatlog
logentity.chatlog.level=等级
logentity.chatlog.channel=聊天类型
logentity.chatlog.receRoleId=接收角色ID
logentity.chatlog.content=聊天内容

#roleloginlog
logentity.roleloginlog.platformName=渠道
logentity.roleloginlog.level=等级
logentity.roleloginlog.onlineTime=在线时长
logentity.roleloginlog.loginRoleIP=IP
logentity.roleloginlog.type=类型

#itemchangelog
logentity.itemchangelog.roleLevel=等级
logentity.itemchangelog.itemId=物品ID
logentity.itemchangelog.modelId=道具ID
logentity.itemchangelog.changeNum=变化数量
logentity.itemchangelog.oldNum=变化前数量
logentity.itemchangelog.newNum=变化后数量
logentity.itemchangelog.reason=原因码
logentity.itemchangelog.actionId=关联ID
logentity.itemchangelog.changeAction=变化类型
logentity.itemchangelog.coinType=消耗货币类型
logentity.itemchangelog.coinNum=消耗货币数量

#expchangelog
logentity.expchangelog.roleLevel=等级
logentity.expchangelog.changeNum=变化量
logentity.expchangelog.reason=原因码
logentity.expchangelog.beforeNum=变化前经验
logentity.expchangelog.afterNum=变化后经验
logentity.expchangelog.actionId=关联ID
logentity.expchangelog.upLevelExp=升级经验

#goldchangelog
logentity.goldchangelog.roleLevel=等级
logentity.goldchangelog.changeNum=变化量
logentity.goldchangelog.reason=原因码
logentity.goldchangelog.beforeNum=变化前元宝数
logentity.goldchangelog.afterNum=变化后元宝数
logentity.goldchangelog.actionId=关联ID
logentity.goldchangelog.loginIp=IP

#guildbaselog
logentity.guildbaselog.guildId=公会ID
logentity.guildbaselog.guildName=公会名称
logentity.guildbaselog.type=操作类型
logentity.guildbaselog.actId=目标玩家ID
logentity.guildbaselog.actName=目标玩家名字
logentity.guildbaselog.param=其他参数
logentity.guildbaselog.actionId=关联ID

#achievementawardlog
logentity.achievementrewardlog.confId=配置表ID
logentity.achievementrewardlog.itemStr=奖励物品
logentity.achievementrewardlog.bindGold=获得绑元
logentity.achievementrewardlog.value=获得成就值
logentity.achievementrewardlog.actionId=关联ID

#crosscloneenterlog
logentity.crosscloneenterlog.fightId=房间ID
logentity.crosscloneenterlog.platsid=服务器ID
logentity.crosscloneenterlog.campNo=阵营
logentity.crosscloneenterlog.cloneId=副本ID
logentity.crosscloneenterlog.cloneName=副本名字
logentity.crosscloneenterlog.level=玩家等级

#crosscloneendlog
logentity.crosscloneendlog.roomId=房间ID
logentity.crosscloneendlog.modelId=副本ID
logentity.crosscloneendlog.CreateTime=副本创建时间
logentity.crosscloneendlog.success=成功
logentity.crosscloneendlog.failure=失败
logentity.crosscloneendlog.condition=条件

#fightrewardcreatelog
logentity.fightrewardcreatelog.key=服务器ID
logentity.fightrewardcreatelog.data=奖励数据

#fightrewardremovelog
logentity.fightrewardremovelog.key=服务器ID
logentity.fightrewardremovelog.data=奖励数据

#fightroomcreatelog
logentity.fightroomcreatelog.roleId=房间ID
logentity.fightroomcreatelog.roleName=副本ID
logentity.fightroomcreatelog.plat=副本创建时间
logentity.fightroomcreatelog.fid=成功
logentity.fightroomcreatelog.modelId=失败
logentity.fightroomcreatelog.sid=条件
logentity.fightroomcreatelog.power=成功
logentity.fightroomcreatelog.isAuto=失败

#fightroomcreatelog
logentity.fightroomdeletelog.fid=房间ID
logentity.fightroomdeletelog.modelId=副本ID
logentity.fightroomdeletelog.state=状态值
logentity.fightroomdeletelog.typeRange=类型值
logentity.fightroomdeletelog.data=玩家数据

#fightroomcreatelog
logentity.playerenterroomlog.roleId=角色ID
logentity.playerenterroomlog.roleName=角色名字
logentity.playerenterroomlog.plat=平台
logentity.playerenterroomlog.fid=房间ID
logentity.playerenterroomlog.modelId=副本ID
logentity.playerenterroomlog.sid=服务器ID
logentity.playerenterroomlog.sizeNo=点位值
logentity.playerenterroomlog.level=等级
logentity.playerenterroomlog.power=战斗力

#questionnirelog
logentity.questionnirelog.roleId=角色ID
logentity.questionnirelog.userId=用户ID
logentity.questionnirelog.data=答题数据

#rechargelog
logentity.rechargelog.orderNo=订单编号
logentity.rechargelog.userId=用户ID
logentity.rechargelog.roleId=角色ID
logentity.rechargelog.sid=服务器ID
logentity.rechargelog.goodsId=商品ID
logentity.rechargelog.goodsType=商品类型
logentity.rechargelog.goodsExt=商品额外参数
logentity.rechargelog.totalFee=金额（分）
logentity.rechargelog.itemId=道具ID
logentity.rechargelog.gameMoney=货币数
logentity.rechargelog.extParam=额外参数
logentity.rechargelog.status=状态
logentity.rechargelog.statusReason=状态码


#questionnirelog
logentity.changerolenamelog.playerId=角色ID
logentity.changerolenamelog.userId=账号ID
logentity.changerolenamelog.sid=区服
logentity.changerolenamelog.oldName=改名前角色名
logentity.changerolenamelog.newName=改名后角色名
logentity.changerolenamelog.modelId=道具ID
logentity.changerolenamelog.platformName=平台名字

#bossdierelivelog
logentity.bossdierelivelog.bossId=BossID
logentity.bossdierelivelog.mapId=地图ID
logentity.bossdierelivelog.type=类型
logentity.bossdierelivelog.param=击杀者

#ranklistlog
logentity.ranklistlog.data=日期
logentity.ranklistlog.rankKind=排行榜类型
logentity.ranklistlog.rank=排名
logentity.ranklistlog.roleId=角色Id
logentity.ranklistlog.roleName=角色名
logentity.ranklistlog.rankData=排行数据
logentity.ranklistlog.platformName=渠道

#coinchangelog
logentity.coinchangelog.roleLevel=玩家等级
logentity.coinchangelog.loginIp=登录ip
logentity.coinchangelog.moneyType=货币类型
logentity.coinchangelog.changeNum=变化数量
logentity.coinchangelog.reason=原因码
logentity.coinchangelog.beforeNum=变化前数量
logentity.coinchangelog.afterNum=变化后数量
logentity.coinchangelog.actionId=关联ID

#maillog
logentity.maillog.mailAction=邮件操作类型
logentity.maillog.type=邮件类型
logentity.maillog.mailId=邮件唯一Id
logentity.maillog.receiveTime=邮件收到时间
logentity.maillog.mailTitle=邮件标题
logentity.maillog.mailContend=邮件内容
logentity.maillog.receiverId=收件人ID
logentity.maillog.receiverName=收件人
logentity.maillog.attachment=附件

