#物品变化理由itemChangeReason
reason.itemChange_-1=移动
reason.itemChange_-2=拆分
reason.itemChange_-3=合并
reason.itemChange_-4=出库
reason.itemChange_-5=入库
reason.itemChange_-6=背包整理
reason.itemChange_-7=仓库整理
reason.itemChange_-8=仓库移动
reason.itemChange_1=交易移除,从身上移除
reason.itemChange_2=手动删除
reason.itemChange_3=交任务删除物品
reason.itemChange_4=任务完成赠送玩家物品
reason.itemChange_5=任务完成的在可领取区域获得物品
reason.itemChange_6=穿上装备
reason.itemChange_7=卸下装备
reason.itemChange_8=杀怪掉落
reason.itemChange_9=开启背包格子
reason.itemChange_10=开启仓库格子
reason.itemChange_11=物品拾取
reason.itemChange_12=技能等级升级
reason.itemChange_13=装备培养
reason.itemChange_14=装备一键强化
reason.itemChange_15=坐骑进阶
reason.itemChange_16=装备升星
reason.itemChange_17=手动使用物品
reason.itemChange_18=坐骑幻化
reason.itemChange_19=任务一键完成删除元宝
reason.itemChange_20=激活码
reason.itemChange_21=坐骑技能升阶
reason.itemChange_22=充值获得元宝
reason.itemChange_23=交易获得元宝
reason.itemChange_24=交易消耗元宝
reason.itemChange_25=使用物品的效果
reason.itemChange_26=卖出物品
reason.itemChange_27=使用物品时所需物品扣除
reason.itemChange_28=转职
reason.itemChange_29=任务加倍完成
reason.itemChange_30=技能一键升级
reason.itemChange_31=骑兵升阶
reason.itemChange_32=掉落获得
reason.itemChange_33=分解装备
reason.itemChange_34=激活骑兵
reason.itemChange_35=升级骑兵技能
reason.itemChange_36=离线修炼
reason.itemChange_37=商城消费元宝
reason.itemChange_38=商城消费
reason.itemChange_39=刷新商城需要元宝
reason.itemChange_40=刷新商城消费
reason.itemChange_41=达成成就
reason.itemChange_42=升级成就勋章
reason.itemChange_43=复活消耗
reason.itemChange_44=邮件附件领取所得
reason.itemChange_45=购买市集的物品
reason.itemChange_46=贩卖市集的物品所得
reason.itemChange_47=市集中上架物品扣除
reason.itemChange_48=交易失败货币返回
reason.itemChange_49=集市邮件的附件领取所得
reason.itemChange_50=披风进阶
reason.itemChange_51=披风技能升级
reason.itemChange_52=增加师徒值或良师值
reason.itemChange_53=良师值兑换
reason.itemChange_54=结婚
reason.itemChange_55=升级夫妻属性
reason.itemChange_56=升级夫妻技能
reason.itemChange_57=升级夫妻信物戒指
reason.itemChange_58=崇拜排行榜玩家奖励
reason.itemChange_59=申诉离婚
reason.itemChange_60=强制离婚
reason.itemChange_61=通关副本获得
reason.itemChange_62=图鉴吞噬
reason.itemChange_63=图鉴领奖
reason.itemChange_64=创建帮会
reason.itemChange_65=帮会改名
reason.itemChange_66=帮会翰林属性升级
reason.itemChange_67=弹劾会长
reason.itemChange_68=帮会捐献
reason.itemChange_69=帮会膜拜
reason.itemChange_70=宠物升级
reason.itemChange_71=宠物激活
reason.itemChange_72=副本奖励时元宝扣除
reason.itemChange_73=副本的采集获取
reason.itemChange_74=装备重铸
reason.itemChange_75=签到奖励
reason.itemChange_76=连续登录奖励
reason.itemChange_77=今日在线奖励
reason.itemChange_78=今日活跃奖励
reason.itemChange_79=等级奖励
reason.itemChange_80=副本积分档次获得
reason.itemChange_81=战魂激活猎魂师
reason.itemChange_82=扫荡副本获得
reason.itemChange_83=通关副本抽奖获得
reason.itemChange_84=神秘商店刷新花费元宝
reason.itemChange_85=神秘商店购买
reason.itemChange_86=装备重生
reason.itemChange_87=初级寻宝一次消耗扣除
reason.itemChange_88=初级寻宝十次消耗扣除
reason.itemChange_89=高级寻宝一次消耗扣除
reason.itemChange_90=高级寻宝十次消耗扣除
reason.itemChange_91=免费初级寻宝所得
reason.itemChange_92=非免费初级寻宝所得
reason.itemChange_93=高级寻宝所得
reason.itemChange_94=非免费高级寻宝所得
reason.itemChange_95=激活称号
reason.itemChange_96=竞技场每日奖励
reason.itemChange_97=vip礼包
reason.itemChange_98=元宝祈福消耗扣除
reason.itemChange_99=绑定元宝祈福消耗扣除
reason.itemChange_100=绑定金币祈福消耗扣除
reason.itemChange_101=元宝祈福所得
reason.itemChange_102=绑定元宝祈福所得
reason.itemChange_103=绑定金币祈福所得
reason.itemChange_104=充值活动获得
reason.itemChange_105=消费活动获得
reason.itemChange_106=兑换活动获得
reason.itemChange_107=兑换活动消耗
reason.itemChange_108=小地图传送扣除
reason.itemChange_109=首冲赠送
reason.itemChange_110=充值赠送
reason.itemChange_111=活动掉落奖励
reason.itemChange_112=合成
reason.itemChange_113=鼓舞
reason.itemChange_114=开礼包
reason.itemChange_115=资源找回
reason.itemChange_116=挑战副本扫荡扣元宝
reason.itemChange_117=挑战副本扫荡获得物品
reason.itemChange_118=装备继承消耗
reason.itemChange_119=活动赠送消耗
reason.itemChange_120=洗属性点
reason.itemChange_121=boss之家
reason.itemChange_122=合成失败回滚消费金额！
reason.itemChange_123=点亮婚姻守护生肖点消耗
reason.itemChange_124=Pk
reason.itemChange_125=神秘商店元宝购买物品记录
reason.itemChange_126=角色改名消耗改名卡道具
reason.itemChange_127=更新有礼获得
reason.itemChange_128=我要变强的每日充值专属礼包
reason.itemChange_129=举办婚宴
reason.itemChange_130=参加婚宴
reason.itemChange_131=使用道具魅力值增加
reason.itemChange_132=升级戒指魅力值增加
reason.itemChange_133=发送密语魅力值增加
reason.itemChange_134=升级亲密(魅力)等级魅力值扣除
reason.itemChange_135=升级守护生肖魅力值扣除
reason.itemChange_136=使用道具良师值增加
reason.itemChange_137=升级师门等级导师积分扣除
reason.itemChange_138=激活圣痕导师积分扣除
reason.itemChange_139=兑换物品良师值扣除
reason.itemChange_140=城市报名
reason.itemChange_141=城市补给
reason.itemChange_142=王府捐献扣除
reason.itemChange_143=捐献获得
reason.itemChange_144=城市报名返回
reason.itemChange_145=首充赠送
reason.itemChange_146=城市战场奖励
reason.itemChange_147=掉落获得
reason.itemChange_148=成就符文升级
reason.itemChange_149=升级称号符文消耗
reason.itemChange_150=披风符文升星进阶
reason.itemChange_151=培养时装
reason.itemChange_152=GM后台移除物品
reason.itemChange_153=GM后台回撤移除物品
reason.itemChange_154=赦免
reason.itemChange_155=限购活动扣除
reason.itemChange_156=限购活动获得
reason.itemChange_157=交易扣除
reason.itemChange_158=交易获得
reason.itemChange_159=交易卸下
reason.itemChange_160=交易取消
reason.itemChange_161=交易失败
reason.itemChange_162=交易异常(交易过程中突然掉线的情况)后返还交易栏物品
reason.itemChange_163=激活神兽消耗
reason.itemChange_164=培养神兽消耗
reason.itemChange_165=抽取神兽碎片
reason.itemChange_166=帮会召集
reason.itemChange_167=新手豪礼
reason.itemChange_168=篝火消耗
reason.itemChange_169=帮会寻宝
reason.itemChange_170=元宝卡的使用加元宝
reason.itemChange_171=跨服竞技场挑战
reason.itemChange_172=王府创建
reason.itemChange_173=王府修改
reason.itemChange_174=宝库抽奖消耗元宝
reason.itemChange_175=宝库抽奖获得
reason.itemChange_176=宝库兑换消耗宝库积分
reason.itemChange_177=宝库物品添加至背包中
reason.itemChange_178=翅膀幻化
reason.itemChange_179=翅膀升星
reason.itemChange_180=翅膀技能升级
reason.itemChange_181=好友添加体力
reason.itemChange_182=好友物品培养增加亲密度
reason.itemChange_183=创建角色时送的数据值
reason.itemChange_184=心跳加体力的值
reason.itemChange_185=精灵球升级消耗
reason.itemChange_186=精灵球符文升级消耗
reason.itemChange_187=击杀Boss活动获得
reason.itemChange_188=篝火获取经验
reason.itemChange_189=激活灵羽消耗
reason.itemChange_190=培养灵羽消耗
reason.itemChange_191=抽取灵羽碎片
reason.itemChange_192=宠物岛捕捉精魄怪获得
reason.itemChange_193=探索精魄怪扣除体力
reason.itemChange_194=进入副本删除道具
reason.itemChange_195=装备升星
reason.itemChange_196=装备融合
reason.itemChange_197=装备学习技能
reason.itemChange_198=装备洗练
reason.itemChange_199=装备出售
reason.itemChange_200=装备精炼
reason.itemChange_201=装备培养
reason.itemChange_202=领取活跃度奖励
reason.itemChange_203=升级活跃符文
reason.itemChange_204=完成活跃项
reason.itemChange_205=时装激活
reason.itemChange_206=采集掉落
reason.itemChange_207=首席竞技场
reason.itemChange_208=经验池增加
reason.itemChange_209=荣耀之战领奖
reason.itemChange_210=军衔的击杀任务领奖
reason.itemChange_211=军衔的升级扣除
reason.itemChange_212=公会研究技能
reason.itemChange_213=玩家学习公会技能
reason.itemChange_214=答题回答问题
reason.itemChange_215=题目最后结算
reason.itemChange_216=玩家发送题目
reason.itemChange_217=公会答题奖励
reason.itemChange_218=帮会入侵
reason.itemChange_219=星辰升阶或升星
reason.itemChange_220=创世神殿的捐献提交
reason.itemChange_221=创世神殿的捐献获得
reason.itemChange_222=创世神殿的积分获得
reason.itemChange_223=帮会试炼界面捐献扣除
reason.itemChange_224=熔炼魔盒重置消耗
reason.itemChange_225=熔炼魔盒消耗
reason.itemChange_226=熔炼魔盒获得
reason.itemChange_227=多人副本奖励
reason.itemChange_228=资源找回
reason.itemChange_229=战场任务刷新消耗
reason.itemChange_229=公会战会长发送的奖励
reason.itemChange_230=翅膀激活
reason.itemChange_231=单服限量购买扣除
reason.itemChange_232=单服限量购买获得
reason.itemChange_233=充值获得道具
reason.itemChange_234=公会战结束奖励
reason.itemChange_235=主线任务奖励
reason.itemChange_236=直线任务奖励
reason.itemChange_237=转职任务奖励
reason.itemChange_238=领取月卡每日奖励
reason.itemChange_239=领取终身卡每日奖励
reason.itemChange_240=充值月卡增加体力值
reason.itemChange_241=充值终身卡增加体力值
reason.itemChange_242=升级圣痕导师积分扣除
reason.itemChange_243=学徒毕业导师增加
reason.itemChange_244=开服活动奖励领取
reason.itemChange_245=随机选择阵营奖励
reason.itemChange_246=装备技能继承
reason.itemChange_247=点击红包获得的金币值
reason.itemChange_248=提交红包扣除的货币值
reason.itemChange_249=使用元宝激活成长基金
reason.itemChange_250=领取成长基金
reason.itemChange_251=任务提交道具
reason.itemChange_252=乱斗领取每日胜利奖励
reason.itemChange_253=上周段位奖励领取
reason.itemChange_254=乱斗之王战斗奖励
reason.itemChange_255=乱斗之王战斗奖励
reason.itemChange_256=花蓝钻转阵营
reason.itemChange_257=参加公会物品竞拍
reason.itemChange_258=离线挂机获得
reason.itemChange_259=击杀定时刷新的entity获得
reason.itemChange_260=装备熔炼
reason.itemChange_261=扣除钻石获取副本的可收益次数
reason.itemChange_262=钻石投资扣除钻石
reason.itemChange_263=钻石投资领取绑金
reason.itemChange_264=领取每日礼包
reason.itemChange_265=跨服排行获得
reason.itemChange_266=神秘商人兑换获得
reason.itemChange_267=神秘商人兑换扣除
reason.itemChange_268=删除测试时，返还玩家的VIP及元宝值
reason.itemChange_269=装备技能书合成
reason.itemChange_270=租赁翅膀蓝钻扣除
reason.itemChange_271=装备神炼
reason.itemChange_272=消费元宝卡获得元宝值
reason.itemChange_273=GM来增加元宝
reason.itemChange_274=后台过来增加元宝
reason.itemChange_275=技能进化激活点
reason.itemChange_276=技能进化重置还原
reason.itemChange_277=圣器模型激活
reason.itemChange_278=圣器升阶
reason.itemChange_288=使用符石
reason.itemChange_289=使用物品升级神物
reason.itemChange_290=使用卡卷
reason.itemChange_291=背包到公会仓库
reason.itemChange_292=公会仓库兑换
reason.itemChange_293=装备合成
reason.itemChange_294=公会退出
reason.itemChange_295=加入公会
reason.itemChange_296=公会每日领取道具
reason.itemChange_297=圣器模型培养
reason.itemChange_298=魔法纹章续费
reason.itemChange_299=魔法纹章试用
reason.itemChange_300=魔法纹章穿戴
reason.itemChange_301=魔法纹章卸下
reason.itemChange_302=装备合成退还技能书
reason.itemChange_303=创世神殿的清理以前所得积分
reason.itemChange_304=金币本的经验增加
reason.itemChange_305=任务掉落进书包
reason.itemChange_306=师姐答题最后结算
reason.itemChange_307=转职任务一键完成的时候扣除
reason.itemChange_308=装备技能不加载
reason.itemChange_309=收集任务提交道具
reason.itemChange_310=圣启之战活动发送
reason.itemChange_311=勇者巅峰奖励
reason.itemChange_312=花钻石清理经验部分的CD值
reason.itemChange_313=时装强化消费
reason.itemChange_314=领取护送任务消耗
reason.itemChange_315=晋升神格
reason.itemChange_316=王者对决副本
reason.itemChange_317=限时购买礼包扣除蓝钻
reason.itemChange_318=限时购买礼包获取礼包物品
reason.itemChange_319=领取王者的功勋奖励
reason.itemChange_320=王者，每日奖励
reason.itemChange_321=参与云购扣除蓝钻
reason.itemChange_322=参与云购获得奖励
reason.itemChange_323=云购活动获取幸运大奖
reason.itemChange_324=回收时移除
reason.itemChange_325=全民boss奖励
reason.itemChange_326=女神徽章的获得物品
reason.itemChange_327=公会怪物攻击获得
reason.itemChange_328=扫荡副本消耗道具
reason.itemChange_329=王者对决每日宝箱
reason.itemChange_330=万人之上
reason.itemChange_331=王者购买数量
reason.itemChange_332=激活命星
reason.itemChange_333=升级灵魂消耗
reason.itemChange_10000=后台功能扣除元宝值
reason.itemChange_100000=gm获得
#货币类型
reason.moneyType_1=已废弃货币
reason.moneyType_2=绑定金币
reason.moneyType_3=蓝钻
reason.moneyType_4=火钻
reason.moneyType_5=首席积分
reason.moneyType_6=科技点
reason.moneyType_7=善恶值
reason.moneyType_8=经验值
reason.moneyType_9=体力
reason.moneyType_10=成就
reason.moneyType_11=会贡
reason.moneyType_12=竞技场积分
reason.moneyType_13=勇气值
reason.moneyType_14=战魂点
reason.moneyType_15=导师积分
reason.moneyType_16=魅力值
reason.moneyType_17=龙灵值
reason.moneyType_18=创世积分
reason.moneyType_19=宝库积分
reason.moneyType_20=荣誉之战积分
reason.moneyType_21=活跃点
reason.moneyType_22=额外经验值
reason.moneyType_23=学分
reason.moneyType_24=荣誉值
reason.moneyType_25=军功
reason.moneyType_26=特权经验
reason.moneyType_27=乱斗点数
reason.moneyType_28=技能点
reason.moneyType_29=仓库积分
reason.moneyType_30=竞技积分
reason.moneyType_31=功勋值
reason.moneyType_32=货币配置表id应小于的值，每次新增货币需加1
#商城ID
reason.shop_-1=神秘商店
reason.shop_1=NPC商店
reason.shop_2=游戏商城
reason.shop_3=未知
reason.shop_4=百宝阁
#充值理由
reason.recharge_0=充值流程记录
reason.recharge_1=充值成功
reason.recharge_2=元宝卡充值
reason.recharge_3=GM命令充值
reason.recharge_4=GM后台充值
#充值步骤
reason.rechargeProcess_-1=重复订单
reason.rechargeProcess_-2=不是属于自己的订单
reason.rechargeProcess_-3=订单状态不对
reason.rechargeProcess_-4=平台验证失败
reason.rechargeProcess_-5=世界服验证的时候玩家掉线了
reason.rechargeProcess_-6=世界服返回给游戏服时玩家掉线了
reason.rechargeProcess_0=收到客户端订单消息
reason.rechargeProcess_1=开始发送消息到世界服
reason.rechargeProcess_2=世界服收到消息开始验证
reason.rechargeProcess_3=验证后返回结果到游戏服
reason.rechargeProcess_4=游戏服收到世界服的返回
reason.rechargeProcess_5=游戏服判断成功后给元宝
#坐骑升级结果
reason.horseUpResult_0=失败
reason.horseUpResult_1=成功
#披风升级结果
reason.cloakUpResult_0=失败
reason.cloakUpResult_1=成功
#装备强化类型
reason.equipStrengType_0=普通强化
reason.equipStrengType_1=一键强化
#角色技能升级
reason.skillUp_-1=移除
reason.skillUp_0=学习
reason.skillUp_1=升级
#角色属性点变化
reason.playerAttPointChange_0=洗点
reason.playerAttPointChange_1=自动
reason.playerAttPointChange_2=手动
reason.playerAttPointChange_3=果实
reason.playerAttPointChange_4=buff
#邮件类型
reason.mailType_1=系统
reason.mailType_2=后台
reason.mailType_3=交易行(集市)
#邮件操作
reason.mailAction_1=邮件收取
reason.mailAction_2=邮件读取
reason.mailAction_3=邮件附件领取
reason.mailAction_4=玩家一键删除邮件
reason.mailAction_5=邮件到期系统删除
#祈福类型
reason.prayType_1=元宝祈福
reason.prayType_2=绑定元宝祈福
reason.prayType_3=绑定金币祈福
#背包类型
reason.bagCellType_1=包裹
reason.bagCellType_2=仓库
#背包操作类型
reason.bagActionType_0=时间开启
reason.bagActionType_1=元宝开启
reason.bagActionType_2=完成任务自动开启
#副本扫荡类型
reason.copyMapSweepType_0=手动
reason.copyMapSweepType_1=自动
reason.copyMapSweepType_2=连续扫荡
reason.copyMapSweepType_3=多人副本
reason.copyMapSweepType_101=阵营1
reason.copyMapSweepType_102=阵营2
#聊天类型
reason.chatType_0=世界聊天
reason.chatType_1=公会聊天
reason.chatType_2=队伍聊天
reason.chatType_3=私人聊天
#活动类型
reason.activity_1=普通充值活动
reason.activity_2=普通消费活动
reason.activity_3=兑换活动
reason.activity_4=掉落活动
reason.activity_5=刷怪活动
reason.activity_6=循环充值活动
reason.activity_7=循环消费活动
reason.activity_8=领取活动
reason.activity_9=节日赠送
reason.activity_10=节日收取
reason.activity_11=排行榜奖励活动
reason.activity_12=消费活动排行
reason.activity_13=赠送排行榜
reason.activity_14=接收排行榜
reason.activity_15=登录邮件活动
reason.activity_16=活动查询
reason.activity_17=限购活动
reason.activity_18=韩国直冲购物活动
reason.activity_19=野外怪经验翻倍活动
reason.activity_20=天启宝库活动
reason.activity_22=击杀boss活动
reason.activity_23=单服限量购买活动
reason.activity_24=充值额外赠送元宝
reason.activity_25=充值活动模板列表
reason.activity_26=普通活动模板列表
reason.activity_27=连续充值活动
reason.activity_28=跨服排行活动
reason.activity_29=充值排行（多服）活动
reason.activity_30=消费排行（多服）活动
reason.activity_32=首杀活动
reason.activity_33=限时购买活动
reason.activity_34=云购活动
#婚礼类型
reason.marriageType_0=结婚类型0普通离婚
reason.marriageType_1=结婚类型1或申诉
reason.marriageType_2=结婚类型2或强制离婚
reason.marriageType_3=结婚类型3或角色删除离婚
reason.marriageType_4=结婚类型4或角色删除离婚
#婚礼操作
reason.marriageAction_0=结婚
reason.marriageAction_1=离婚
#玩家交易动作
reason.tradeAction_1=交易申请
reason.tradeAction_2=交易取消
reason.tradeAction_3=交易锁定
reason.tradeAction_4=交易失败
reason.tradeAction_5=交易成功
reason.tradeAction_6=交易异常(交易中掉线情况)
#城市战阵营，防守方0、攻方1、攻方2
reason.cityWarCamp_0=防守方
reason.cityWarCamp_1=攻方1
reason.cityWarCamp_2=攻方2
#王府官员类型
reason.kpOfficialType_0=普通成员
reason.kpOfficialType_1=王爷
reason.kpOfficialType_2=王妃
reason.kpOfficialType_3=军师
reason.kpOfficialType_4=辅国将军
reason.kpOfficialType_5=辅政将军
#王府捐献类型
reason.kpDonateType_1=100物资捐献
reason.kpDonateType_2=100元宝捐献
reason.kpDonateType_3=600物资捐献
#王府基本信息修改类型
reason.kpBaseInfoModifyType_0=普通修改
reason.kpBaseInfoModifyType_1=修改旗帜
reason.kpBaseInfoModifyType_2=修改王府名
#公会信息
reason.guildAction_1=公会创建
reason.guildAction_2=公会解散
reason.guildAction_3=加入公会
reason.guildAction_4=主动退会
reason.guildAction_5=提出公会
reason.guildAction_6=公会设置
reason.guildAction_7=公会改名
reason.guildAction_8=弹劾会长