#
jsp.role.title=角色信息查询
jsp.role.norole=没有找到角色信息
jsp.role.nouserid=没有找到帐号ID
jsp.role.noaccount=没有找到帐号信息
jsp.role.nolslog=无法获取LoginServerLog数据库连接
jsp.role.dataerror=数据异常，请联系管理员
jsp.role.showdetail=查看角色详情
jsp.role.logoff=注销
jsp.role.nologoff=未注销
jsp.role.logouttime=注销时间
jsp.rolelog.nodata=没有找到数据
jsp.rolelog.noroleid=请输入roleId
jsp.role.roledetail=角色详细信息查询页面
jsp.role.pleasetypenum=请输入数字!
jsp.role.searchcon=查询条件
jsp.role.rolename=角色名称
jsp.role.account=帐号名
jsp.role.roleid=角色ID
jsp.role.roleidIn10=角色ID(10进制)
jsp.role.roleidIn36=角色ID(36进制)
jsp.role.userid=帐号ID
jsp.role.search=查询
jsp.role.out=注销
jsp.role.noout=未注销
jsp.role.roleinfo=角色信息
jsp.role.level=等级
jsp.role.sex=性别
jsp.role.career=职业
jsp.role.money=金钱
jsp.role.gold=元宝
jsp.role.groupNo=出生阵营
jsp.role.iron=体力
jsp.role.server=区服
jsp.role.rechargegold=充值元宝
jsp.role.ct=创建时间
jsp.role.ip=角色登录IP
jsp.role.isdelete=是否注销
jsp.role.fcaccount=帐号名
jsp.role.channel=渠道
jsp.role.moonCardDay=月卡天数
jsp.role.action=操作
jsp.role.acinfo=帐号信息
jsp.role.acname=帐号名
jsp.role.acid=账号ID
jsp.role.acpfaccount=渠道帐号
jsp.role.acplatform=渠道名称
jsp.role.acct=创建时间
jsp.role.aclt=最近登录时间
jsp.role.acip=登录IP
jsp.role.mac=mac地址
jsp.role.imei=imei
jsp.role.machineCode=机器唯一码
jsp.role.sdateempty=开始日期不能为空！
jsp.role.edateempty=结束日期不能为空！
jsp.role.sdatelessthanedate=结束日期不能小于开始日期！
jsp.rolelog.searchDate=日志查询时间
jsp.rolelog.no=否
jsp.rolelog.yes=是
jsp.rolelog.power=力道:
jsp.rolelog.vigour=元气:
jsp.rolelog.body=身法:
jsp.rolelog.phy=体质:
jsp.rolelog.material=升星所需的材料:
jsp.rolelog.num=所需材料的数量:
#
jsp.rolelog.rolelogin=登录日志
jsp.rolelog.rolelogout=登出日志
jsp.rolelogout.platform=渠道
jsp.rolelogout.server=区服
jsp.rolelogout.level=等级
jsp.rolelogout.career=职业
jsp.rolelogout.time=时间
jsp.rolelogout.ip=IP
#
jsp.rolelog.bindgoldchange=绑定元宝日志
jsp.bindgoldchange.platform=渠道
jsp.bindgoldchange.server=区服
jsp.bindgoldchange.level=等级
jsp.bindgoldchange.before=变化前
jsp.bindgoldchange.after=变化后
jsp.bindgoldchange.num=变化量
jsp.bindgoldchange.reason=原因
jsp.bindgoldchange.time=时间
jsp.bindgoldchange.ip=IP
jsp.bindgoldchange.actionid=唯一标识
#
jsp.rolelog.goldchange=元宝日志
jsp.goldchange.platform=渠道
jsp.goldchange.server=区服
jsp.goldchange.level=等级
jsp.goldchange.before=变化前
jsp.goldchange.after=变化后
jsp.goldchange.num=变化量
jsp.goldchange.reason=原因
jsp.goldchange.time=时间
jsp.goldchange.ip=IP
jsp.goldchange.actionid=唯一标识
#
jsp.rolelog.moneychange=金币变化日志
jsp.moneychange.platform=渠道
jsp.moneychange.server=区服
jsp.moneychange.level=等级
jsp.moneychange.before=变化前
jsp.moneychange.after=变化后
jsp.moneychange.num=变化量
jsp.moneychange.moneytype=货币类型
jsp.moneychange.reason=原因
jsp.moneychange.time=时间
jsp.moneychange.ip=IP
jsp.moneychange.actionid=唯一标识
#
jsp.rolelog.coinchange=货币变化日志
jsp.coinchange.platform=渠道
jsp.coinchange.server=区服
jsp.coinchange.level=等级
jsp.coinchange.before=变化前
jsp.coinchange.after=变化后
jsp.coinchange.num=变化量
jsp.coinchange.moneytype=货币类型
jsp.coinchange.reason=原因
jsp.coinchange.time=时间
jsp.coinchange.ip=IP
jsp.coinchange.actionid=唯一标识
#
jsp.rolelog.zhenqiandtiechange=军功和荣誉值变化日志
jsp.zhenqiandtiechange.platform=渠道
jsp.zhenqiandtiechange.server=区服
jsp.zhenqiandtiechange.level=等级
jsp.zhenqiandtiechange.before=变化前
jsp.zhenqiandtiechange.after=变化后
jsp.zhenqiandtiechange.num=变化量
jsp.zhenqiandtiechange.moneytype=货币类型
jsp.zhenqiandtiechange.reason=原因
jsp.zhenqiandtiechange.time=时间
jsp.zhenqiandtiechange.ip=IP
jsp.zhenqiandtiechange.actionid=唯一标识
#
jsp.rolelog.itemchange=物品日志
jsp.itemchange.platform=渠道
jsp.itemchange.server=区服
jsp.itemchange.level=等级
jsp.itemchange.before=变化前
jsp.itemchange.after=变化后
jsp.itemchange.num=变化量
jsp.itemchange.modelid=物品ID
jsp.itemchange.reason=原因
jsp.itemchange.time=时间
jsp.itemchange.changeaction=执行动作
jsp.itemchange.actionid=唯一标识
#
jsp.rolelog.shopbuy=商店购买日志
jsp.shopbuy.platform=渠道
jsp.shopbuy.server=区服
jsp.shopbuy.level=等级
jsp.shopbuy.shopid=商城ID
jsp.shopbuy.itemmodelid=商品道具ID
jsp.shopbuy.buyTimes=购买次数
jsp.shopbuy.realnum=购买数量
jsp.shopbuy.moneytype=货币类型
jsp.shopbuy.moneynum=货币数量
jsp.shopbuy.sellId=商品ID
jsp.shopbuy.reasoncode=原因码
jsp.shopbuy.fromsrc=商品标签页ID
jsp.shopbuy.time=时间
jsp.shopbuy.actionid=唯一标识
#
jsp.rolelog.buy=交易所买入日志
jsp.buy.itemId=道具唯一ID
jsp.buy.itemmodelid=道具ID
jsp.buy.num=交易数量
jsp.buy.trantype=交易类型
jsp.buy.coinnum=货币消耗
jsp.buy.cointype=货币类型
jsp.buy.sellrolename=卖家名称
jsp.buy.sellplatform=卖家渠道
jsp.buy.time=时间
jsp.buy.actionid=唯一标识
#
jsp.rolelog.sell=交易所卖出日志
jsp.sell.itemId=道具唯一ID
jsp.sell.itemmodelid=道具ID
jsp.sell.num=交易数量
jsp.sell.trantype=交易类型
jsp.sell.coinnum=货币消耗
jsp.sell.cointype=货币类型
jsp.sell.buyrolename=买家名称
jsp.sell.buyplatform=买家渠道
jsp.sell.time=时间
jsp.sell.actionid=唯一标识
#
jsp.rolelog.levelchange=角色等级变化日志
jsp.levelchange.server=区服
jsp.levelchange.beforeexp=变化前经验
jsp.levelchange.afterexp=变化后经验
jsp.levelchange.changeexp=经验变化量
jsp.levelchange.oldlevel=变化前等级
jsp.levelchange.nowlevel=变化后等级
jsp.levelchange.reason=原因
jsp.levelchange.time=时间
jsp.levelchange.actionid=唯一标识
#
jsp.rolelog.skill=技能升级日志
jsp.skill.server=区服
jsp.skill.skillid=技能
jsp.skill.level=等级
jsp.skill.action=行为
jsp.skill.consume=消耗
jsp.skill.time=时间
jsp.skill.actionid=唯一标识
#
jsp.rolelog.rechargesuccess=充值日志
jsp.rechargesuccess.platformName=渠道名称
jsp.rechargesuccess.orderId=订单id
jsp.rechargesuccess.amount=充值金额
jsp.rechargesuccess.currency=充值币种
jsp.rechargesuccess.sid=区服
jsp.rechargesuccess.gold=充值获得元宝数
jsp.rechargesuccess.gift=赠送的绑定元宝
jsp.rechargesuccess.actionId=关联Id
jsp.rechargesuccess.oid=渠道订单号
jsp.rechargesuccess.itemId=充值物品ID
jsp.rechargesuccess.level=充值等级
jsp.rechargesuccess.isMoon=是否为月卡
jsp.rechargesuccess.time=充值时间
jsp.rechargesuccess.allAmount=充值总额
jsp.rechargesuccess.allGold=充值总元宝
jsp.rechargesuccess.moon=月卡
jsp.rechargesuccess.noMoon=非月卡
#
jsp.rolelog.dragoonup=骑兵升级日志
jsp.dragoonup.server=区服
jsp.dragoonup.beforeupnum=之前升级数量
jsp.dragoonup.afterupnum=之后升级数量
jsp.dragoonup.beforekey=升级前阶数
jsp.dragoonup.afterkey=升级后阶数
jsp.dragoonup.beforebless=升级前祝福值
jsp.dragoonup.afterbless=升级后祝福值
jsp.dragoonup.costbindedgold=消耗绑定元宝
jsp.dragoonup.costgold=消耗元宝
jsp.dragoonup.time=时间
jsp.dragoonup.actionid=唯一标识
#
jsp.rolelog.dragoonskillup=骑兵技能升级日志
jsp.dragoonskillup.server=区服
jsp.dragoonskillup.beforeexp=升级前经验
jsp.dragoonskillup.afterexp=升级后经验
jsp.dragoonskillup.beforelevel=升级前等级
jsp.dragoonskillup.afterlevel=升级后等级
jsp.dragoonskillup.skilldataid=技能ID
jsp.dragoonskillup.time=时间
jsp.dragoonskillup.actionid=唯一标识
#
jsp.rolelog.horseup=坐骑升级日志
jsp.horseup.server=区服
jsp.horseup.beforebless=升级前祝福值
jsp.horseup.afterbless=升级后祝福值
jsp.horseup.addbless=祝福增长值
jsp.horseup.upitemid=消耗道具ID
jsp.horseup.upitemnum=消耗道具数量
jsp.horseup.curuptimes=当前升级次数
jsp.horseup.beforehorselayer=升级前坐骑阶数
jsp.horseup.upresult=升级结果
jsp.horseup.time=时间
#
jsp.rolelog.horseskillup=坐骑技能升级日志
jsp.horseskillup.server=区服
jsp.horseskillup.beforeexp=升级前经验
jsp.horseskillup.afterexp=升级后经验
jsp.horseskillup.addexp=经验增加量
jsp.horseskillup.skillid=技能ID
jsp.horseskillup.isskilllevelup=是否升级
jsp.horseskillup.skilllevel=提升后等级
jsp.horseskillup.upitemid=消耗道具ID
jsp.horseskillup.upitemnum=消耗道具数量
jsp.horseskillup.time=时间
#
jsp.rolelog.cloakup=披风升级日志
jsp.cloakup.server=区服
jsp.cloakup.beforebless=升级前祝福值
jsp.cloakup.afterbless=升级后祝福值
jsp.cloakup.addbless=祝福增长值
jsp.cloakup.upitemid=消耗道具ID
jsp.cloakup.upitemnum=消耗道具数量
jsp.cloakup.curuptimes=当前升级次数
jsp.cloakup.beforecloaklayer=升级前坐骑阶数
jsp.cloakup.upresult=升级结果
jsp.cloakup.skillactivated=激活技能
jsp.cloakup.time=时间
#
jsp.rolelog.cloakskillup=披风技能升级日志
jsp.cloakskillup.server=区服
jsp.cloakskillup.beforeexp=升级前经验
jsp.cloakskillup.afterexp=升级后经验
jsp.cloakskillup.addexp=经验增加量
jsp.cloakskillup.skillId=技能ID
jsp.cloakskillup.isskilllevelup=是否升级
jsp.cloakskillup.skilllevel=提升后等级
jsp.cloakskillup.upitemid=消耗道具ID
jsp.cloakskillup.upitemnum=消耗道具数量
jsp.cloakskillup.time=时间
#
jsp.rolelog.equipstreng=装备强化日志
jsp.equipstreng.server=区服
jsp.equipstreng.platformName=平台名称
jsp.equipstreng.equipId1=培养装备唯一ID
jsp.equipstreng.modelid1=培养装备模型ID
jsp.equipstreng.equipId2=材料装备唯一ID
jsp.equipstreng.modelid2=材料装备模型ID
jsp.equipstreng.equipId2Att=材料装备属性
jsp.equipstreng.expend=消耗材料
jsp.equipstreng.time=时间
jsp.equipstreng.actioinid=唯一标识
#
jsp.rolelog.equipupstar=装备升星日志
jsp.equipupstar.server=区服
jsp.equipupstar.expend=消耗材料
jsp.equipupstar.part=升星部位
jsp.equipupstar.startlv=升星前等级
jsp.equipupstar.endlv=升星后等级
jsp.equipupstar.time=时间
jsp.equipupstar.actioinId=唯一标识
#
jsp.rolelog.expchange=经验变化日志
jsp.expchange.server=区服
jsp.expchange.beforenum=升级前经验
jsp.expchange.afternum=升级后经验
jsp.expchange.changenum=经验变化量
jsp.expchange.rolelevel=变化后等级
jsp.expchange.reason=原因
jsp.expchange.time=时间
jsp.expchange.actionId=唯一标识
#
jsp.rolelog.playerattpointchange=角色属性点变化日志
jsp.playerattpointchange.type=变化类型
jsp.playerattpointchange.beforev=变化前属性
jsp.playerattpointchange.afterv=变化后属性
jsp.playerattpointchange.remain=保留属性
jsp.playerattpointchange.time=时间
jsp.playerattpointchange.actionid=唯一标识
#
jsp.rolelog.maintask=主线任务日志
jsp.maintask.sid=区服
jsp.maintask.platfromname=渠道
jsp.maintask.accmodelid=接受任务ID
jsp.maintask.acclevel=接受任务时人物等级
jsp.maintask.accmoney=接受任务时人物金币
jsp.maintask.acconlinetime=接受任务时的在线时间（单位：ms）
jsp.maintask.fshmodelid=完成任务ID
jsp.maintask.fshlevel=完成任务时人物等级
jsp.maintask.fshmoney=完成任务时人物金币
jsp.maintask.fshonlinetime=完成任务时的在线时间（单位：ms）
jsp.maintask.accbeforereceiveable=accbeforeReceiveAble
jsp.maintask.accafterreceiveable=accafterReceiveAble
jsp.maintask.time=时间
#
jsp.rolelog.mail=邮件日志
jsp.mail.mailid=邮件ID
jsp.mail.mailtitle=邮件标题
jsp.mail.mailvontend=邮件内容
jsp.mail.receivetime=接收时间
jsp.mail.sender=发送者
jsp.mail.mailaction=邮件操作
jsp.mail.isread=是否阅读
jsp.mail.hasattachment=是否存在附件
jsp.mail.attachment=附件
jsp.mail.isattachreceived=是否领取附件
jsp.mail.time=时间
jsp.mail.sendInterval=发送间隔
jsp.mail.type=邮件类型
#
jsp.rolelog.pray=祈福日志
jsp.pray.sid=区服
jsp.pray.type=祈福类型
jsp.pray.prayitems=祈福道具
jsp.pray.time=时间
#
jsp.rolelog.worship=膜拜日志
jsp.worship.worshipday=膜拜天数
jsp.worship.worshipplayerid=膜拜角色
jsp.worship.todayworshipnum=膜拜次数
jsp.worship.worshippedplayeridset=膜拜记录
jsp.worship.time=时间
#
jsp.rolelog.cellopen=背包开启日志
jsp.cellopen.sid=区服
jsp.cellopen.beforecells=之前格子数
jsp.cellopen.aftercells=之后格子数
jsp.cellopen.celltype=格子类型
jsp.cellopen.actiontype=操作类型
jsp.cellopen.resumgold=消耗元宝
jsp.cellopen.time=时间
jsp.cellopen.actionid=唯一标识
#
jsp.rolelog.chat=聊天日志
jsp.chat.sid=区服
jsp.chat.channel=频道
jsp.chat.content=内容
jsp.chat.receroleid=消息接受者ID
jsp.chat.time=时间
#
jsp.rolelog.horseillusion=坐骑幻化日志
jsp.horseillusion.createsid=区服
jsp.horseillusion.curHighestLayer=当前最高阶数
jsp.horseillusion.afterIllusionLevel=幻化后等级
jsp.horseillusion.illusionItemId=消耗道具ID
jsp.horseillusion.illusionItemNum=消耗道具数量
jsp.horseillusion.time=时间
#
jsp.rolelog.conquertaskaccept=讨伐任务接受日志
jsp.conquertaskaccept.sid=区服
jsp.conquertaskaccept.platformName=平台名称
jsp.conquertaskaccept.taskmodelid=任务ID
jsp.conquertaskaccept.taskinfo=任务信息
jsp.conquertaskaccept.taskCount=当前处于第几环
jsp.conquertaskaccept.time=时间
#
jsp.rolelog.vipgetgift=VIP奖励获取日志
jsp.vipgetgift.sid=区服
jsp.vipgetgift.getvipgift=奖励级别
jsp.vipgetgift.nowviplevel=当前VIP等级
jsp.vipgetgift.time=时间
jsp.vipgetgift.actionid=唯一标识
#
jsp.rolelog.baokutanmi=资源争夺战日志
jsp.baokutanmi.sid=区服
jsp.baokutanmi.platform=平台
jsp.baokutanmi.gatherid=收集道具
jsp.baokutanmi.gathertimes=收集次数
jsp.baokutanmi.reward=奖励
jsp.baokutanmi.rewardbei=奖励倍数
jsp.baokutanmi.time=时间
#
jsp.rolelog.challengefirstreward=竞技场第一名奖励日志
jsp.challengefirstreward.sid=区服
jsp.challengefirstreward.platform=平台
jsp.challengefirstreward.reward=奖励
jsp.challengefirstreward.type=类型
jsp.challengefirstreward.oldlevel=之前等级
jsp.challengefirstreward.changelevel=等级变化
jsp.challengefirstreward.time=时间
jsp.challengefirstreward.actionid=唯一标识
#
jsp.rolelog.conloginreward=连续登陆奖励日志
jsp.conloginreward.sid=区服
jsp.conloginreward.curconlogindays=当前登录天数
jsp.conloginreward.rewardday=领取奖励天数
jsp.conloginreward.rewarditems=奖励道具
jsp.conloginreward.time=时间
#
jsp.rolelog.copymaplogrecord=副本奖励日志
jsp.copymaplogrecord.sid=区服
jsp.copymaplogrecord.platform=平台
jsp.copymaplogrecord.zonemodelid=副本ID
jsp.copymaplogrecord.issuccess=是否成功
jsp.copymaplogrecord.type=扫荡类型
jsp.copymaplogrecord.score=评分
jsp.copymaplogrecord.copyovertime=副本结束时间
jsp.copymaplogrecord.reward=奖励
jsp.copymaplogrecord.dcreward=档次奖励
jsp.copymaplogrecord.time=时间
jsp.copymaplogrecord.actionid=唯一标识
#
jsp.rolelog.cpmutilreward=多人副本奖励日志
jsp.cpmutilreward.sid=区服
jsp.cpmutilreward.platform=渠道
jsp.cpmutilreward.cpid=副本唯一ID
jsp.cpmutilreward.cpmodelid=副本ID
jsp.cpmutilreward.reward=奖励
jsp.cpmutilreward.needgold=需要元宝
jsp.cpmutilreward.beinum=奖励倍数
jsp.cpmutilreward.time=时间
jsp.cpmutilreward.actionid=唯一标识
#
jsp.rolelog.levelreward=等级奖励日志
jsp.levelreward.sid=区服
jsp.levelreward.rewarditems=奖励
jsp.levelreward.curlevel=当前等级
jsp.levelreward.rewardlevel=奖励等级
jsp.levelreward.curtransferdegree=当前角色等级阶数
jsp.levelreward.time=时间
#
jsp.rolelog.onlinereward=在线奖励日志
jsp.onlinereward.sid=区服
jsp.onlinereward.rewarditems=奖励
jsp.onlinereward.curonlinetime=当前在线时长
jsp.onlinereward.rewardonlinetime=领取所需时长
jsp.onlinereward.time=时间
#
jsp.rolelog.seektreasure=寻宝奖励日志
jsp.seektreasure.sid=区服
jsp.seektreasure.rewarditems=奖励
jsp.seektreasure.type=类型
jsp.seektreasure.consumeitemid=消耗道具ID
jsp.seektreasure.consumeitemnum=道具消耗数量
jsp.seektreasure.time=时间
#
jsp.rolelog.signreward=月卡奖励领取日志
jsp.signreward.sid=区服
jsp.signreward.rewarditems=奖励
jsp.signreward.curmonth=当前月份
jsp.signreward.cursignnum=当月签到次数
jsp.signreward.curtotalsignnum=当月总签到次数
jsp.signreward.time=时间
#
jsp.rolelog.dailyrechargerewardget=每日专属福利领取日志
jsp.dailyrechargerewardget.sid=区服
jsp.dailyrechargerewardget.rewardId=奖励档次
jsp.dailyrechargerewardget.rewardItems=奖励
jsp.dailyrechargerewardget.time=时间
#
jsp.rolelog.pet=宠物日志
jsp.pet.sid=区服
jsp.pet.petID=宠物ID
jsp.pet.level=宠物等级
jsp.pet.actionType=操作方式
jsp.pet.time=时间