jsp.shoplist.id=ID товара
jsp.shoplist.type=Тип конфигурации
jsp.shoplist.itemID=Предмет
jsp.shoplist.shopID=Магазин
jsp.shoplist.shopType=Тег магазина
jsp.shoplist.labelID=ID тега
jsp.shoplist.level=Требуемый уровень
jsp.shoplist.guildLevel=Требуемый уровень гильдии
jsp.shoplist.guildShopLvl=Требуемый уровень альянса
jsp.shoplist.vipLevel=Требуемый уровень развития
jsp.shoplist.occupation=Ограничение по классу
jsp.shoplist.limitType=Тип ограничения покупок
jsp.shoplist.buyNum=Количество покупок
jsp.shoplist.currencyID=Валюта
jsp.shoplist.price=Цена до скидки
jsp.shoplist.discountPrice=Цена после скидки
jsp.shoplist.discount=Размер скидки
jsp.shoplist.promotion=Промо-тег
jsp.shoplist.sort=Приоритет отображения
jsp.shoplist.upTime=Время появления
jsp.shoplist.downTime=Время исчезновения
jsp.shoplist.bind=Привязка
jsp.shoplist.refreshCurrency=Тип валюты для обновления
jsp.shoplist.refreshNum=Стоимость обновления
jsp.shoplist.worldLvl=Требуемый мировой уровень
jsp.shoplist.isDiscount=Скидка на совершенствование

jsp.shoplist.chooseShopType=Тип магазина
jsp.shoplist.shopId0=Все
jsp.shoplist.shopId1=Магазин за монеты
jsp.shoplist.shopId2=Обменный магазин
jsp.shoplist.shopId3=Магазин очков удачи
jsp.shoplist.shopId4=Магазин вклада в альянс

jsp.shoplist.career-1=Без ограничений
jsp.shoplist.career0=Меч Теней
jsp.shoplist.career1=Небесный Герой
jsp.shoplist.career2=Земное Сокровище
jsp.shoplist.career3=Ракшаса

jsp.shoplist.limit0=Без ограничений
jsp.shoplist.limit1=В день
jsp.shoplist.limit2=В неделю
jsp.shoplist.limit3=В месяц
jsp.shoplist.limit4=В год
jsp.shoplist.limit5=Навсегда

jsp.shoplist.promotion0=Нет
jsp.shoplist.promotion1=Скидка
jsp.shoplist.promotion2=Рекомендуется
jsp.shoplist.promotion3=Новинка
jsp.shoplist.promotion4=Хит

jsp.shoplist.plat=Платформа
jsp.shoplist.server=Сервер
jsp.shoplist.operate=Действие
jsp.shoplist.unknow=Неизвестно
jsp.shoplist.yes=Да
jsp.shoplist.no=Нет
jsp.shoplist.isbind=Привязано
jsp.shoplist.nobind=Не привязано