#充值排行榜
rank.pay.pagetitle=充值排行榜
rank.pay.number=排名
rank.pay.paysumis=充值总金额为
rank.pay.userid=用户ID
rank.pay.roleid=角色ID
rank.pay.rolename=角色名字
rank.pay.currencyType=货币类型
rank.pay.payAmount=充值金额
rank.pay.payTime=充值时间
rank.pay.payRank=用户充值排行
rank.pay.rolePayRank=角色充值排行
rank.pay.lastLoginTime=最后登录时间
rank.pay.payCount=充值次数
rank.pay.paySum=充值总金额
rank.pay.firstpayAmount=首充金额
rank.pay.firstpayTime=首充时间
rank.pay.sortType=排序
rank.pay.sortMoney=金额
rank.pay.sortCount=次数
rank.pay.payRecord=用户充值记录
rank.pay.lookat=查看
rank.pay.button.close=关闭
rank.pay.playerInfo=玩家信息
rank.pay.table.rolename=角色名字
rank.pay.table.serverId=区服ID
rank.pay.oid=渠道订单号
rank.pay.table.level=等级
rank.pay.table.attack=战斗力
rank.pay.table.career=职业
rank.pay.table.consumeGold=消耗蓝钻
#功能开关
sysswitch.open=开启
sysswitch.close=关闭
sysswitch.number=编号
sysswitch.funame=功能名称
sysswitch.serverName=所属区服
sysswitch.fustate=功能状态
sysswitch.option=操作
#统计功能,public
statistic.public.platform=平台
statistic.public.server=区服
statistic.public.time=时间
statistic.public.prop=道具
statistic.public.date=日期
statistic.public.selectAll=全选
statistic.public.syspromt.time=系统提示：未选择时间！
statistic.public.syspromt.server=系统提示：未选择区服！
statistic.public.playercount=人数
statistic.public.content=统计内容
statistic.public.exportExcel=导出Excel
statistic.public.isblack=是否剔除黑名单
statistic.public.Channel=渠道名称
statistic.public.reason=原因
#充值分布统计
statistic.payDistribute.pagetitle=充值金额分布统计
statistic.payDistribute.money=金额
statistic.payDistribute.timesection=时间段
statistic.payDistribute.paydis=充值档位分布
statistic.payDistribute.paydaymoney=每日充值金额
statistic.payDistribute.content1=选定时间段内，充值档次以及人数
statistic.payDistribute.content2=各个时间段中充值金额以及人数
#宝贝阶数分布统计
statistic.lvDistribute.pagetitle=宝贝阶数分布统计
statistic.lvDistribute.lvcount=升阶人次
statistic.lvDistribute.weaponId=神兵ID
statistic.lvDistribute.weaponlv=神兵阶数
statistic.lvDistribute.cloaklv=披风阶数
statistic.lvDistribute.horselv=坐骑阶数
statistic.lvDistribute.weaponData=神兵阶数统计
statistic.lvDistribute.horseData=坐骑阶数统计
statistic.lvDistribute.cloakData=披风阶数统计
#坐骑升阶统计
statistic.horseadvance.pagetitle=坐骑升阶统计
statistic.horseadvance.lvnumber=坐骑阶数
statistic.horseadvance.itemuseinfo=消耗道具
statistic.horseadvance.clickcount=点击次数
statistic.horseadvance.lvercount=升阶人次
statistic.horseadvance.itemcount=道具消费数量
statistic.horseadvance.horseUpstar=坐骑升星丹
statistic.horseadvance.horseTransmogrification=坐骑幻化丹
statistic.horseadvance.rabbitPiece=御风神兔碎片
statistic.horseadvance.dragonPiece=神威巨龙碎片
statistic.horseadvance.frostPiece=冰霜巨龙碎片
statistic.horseadvance.sowosskyPiece=青翼蝠龙碎片
statistic.horseadvance.pandaPiece=熊猫胖胖碎片
statistic.horseadvance.weddingPiece=欢庆婚车碎片
statistic.horseadvance.horsePiece=灵翼飞马碎片
statistic.horseadvance.bumblebeePiece=大黄蜂碎片
statistic.horseadvance.armourPiece=铁甲威龙碎片
statistic.horseadvance.snailPiece=蒸汽蜗牛碎片
statistic.horseadvance.enginePiece=朋克机车碎片
statistic.horseadvance.horselv=坐骑进阶
#玩家流失统计
statistic.playerLeave.pagetitle=玩家流失统计
statistic.playerLeave.ordfcount=登录用户总数
statistic.playerLeave.ordlcount=用户流失数
statistic.playerLeave.ordrate=用户流失率
statistic.playerLeave.vipfcount=付费用户
statistic.playerLeave.viplcount=付费用户流失数
statistic.playerLeave.viprate=付费用户流失率
statistic.playerLeave.lvdistri=等级分布
statistic.playerLeave.amountSum=累计金额
statistic.playerLeave.lvpaysum=账号数
statistic.playerLeave.lvpaymoney=流失用户充值总金额
statistic.playerLeave.playerLeaveCount=流失用户统计
statistic.playerLeave.playerLeaveRank=流失用户等级分布
statistic.playerLeave.playerLeaveAmount=流失用户付费金额与次数统计
statistic.playerLeave.content1=用户流失数，用户流失率，付费用户流失数，付费用户流失率
statistic.playerLeave.content2=付费用户等级分布
statistic.playerLeave.content3=流失用户付费金额分布，付费次数分布
#玩家Ltv统计
statistic.playerLtv.pagetitle=玩家Ltv统计
statistic.playerLtv.addnewer=新增人数
statistic.playerLtv.ltvs=LTV统计
statistic.playerLtv.content1=用户LTV生命值统计
#玩家充值统计
statistic.playerPay.pagetitle=玩家充值统计
statistic.playerPay.addnewer=新增角色
statistic.playerPay.addvipnewer=新增付费角色
statistic.playerPay.addpaymoney=新增付费金额
statistic.playerPay.activeCount=用户日活跃数
statistic.playerPay.daypayCount=日付费数
statistic.playerPay.daypayRate=日付费率
statistic.playerPay.firstdaypayCount=首日付费数
statistic.playerPay.firstdaypayRate=首日付费率
statistic.playerPay.firstweekpayCount=首周付费数
statistic.playerPay.firstweekpayRate=首周付费率
statistic.playerPay.firstmonthpayCount=首月付费数
statistic.playerPay.firstmonthRate=首月付费率
statistic.playerPay.dayweekmonthfp=日月周首付统计
statistic.playerPay.payRank=付费等级
statistic.playerPay.payLevel=等级分布
statistic.playerPay.payRoleCount=付费角色数
statistic.playerPay.payAmount=付费总额
statistic.playerPay.paycounts=付费次数
statistic.playerPay.payInterval=付费间隔
statistic.playerPay.timeGap=间隔时间
statistic.playerPay.firstRechargeRole=首充充值角色数
statistic.playerPay.secondRechargeRole=二次充值角色数
statistic.playerPay.thirdRechargeRole=三次充值角色数
statistic.playerPay.onedayfirstpay=单日首付统计
statistic.playerLtv.content2=付费率，首日付费率，首周付费率，首月付费率
statistic.playerLtv.content3=付费等级—金额，付费等级—次数
statistic.playerLtv.content4=付费间隔—首次，付费间隔—二次，付费间隔—三次
statistic.playerLtv.content5=首付统计—时间，首付统计—金额
#绑定元宝充值
statistic.bindgold.pagetitle=绑定元宝统计
statistic.bindgold.sid=对应区服
statistic.bindgold.itemModelId=道具ID
statistic.bindgold.itemName=道具名称
statistic.bindgold.userCount=购买人数
statistic.bindgold.itemCount=购买数量
statistic.bindgold.itemSum=消费元宝
statistic.bindgold.payCount=消费次数
statistic.bindgold.bindgoldUsage=绑定元宝统计用途
statistic.bindgold.bindgoldSummar=绑定元宝使用汇总
#玩家在线时长统计
statistic.onlinetime.pagetitle=玩家在线时长
statistic.onlinetime.dailyOnline=玩家在线时长详细
statistic.onlinetime.onlineTime=在线时长
statistic.onlinetime.time=最后登录时间
statistic.onlinetime.rolecount=角色数
statistic.onlinetime.onlineInfo=玩家在线时长统计
statistic.onlinetime.dailyOnlineInfo=玩家在线时长详细记录
statistic.onlinetime.userId=玩家账号ID
statistic.onlinetime.roleId=玩家角色ID
statistic.onlinetime.roleName=玩家角色名称
statistic.onlinetime.createTime=角色注册时间
statistic.onlinetime.level=角色等级
statistic.onlinetime.platformName=渠道名称
statistic.onlinetime.serverId=区服ID
statistic.onlinetime.condition=选择条件
statistic.onlinetime.allplayer=所有玩家
statistic.onlinetime.payPlayer=付费玩家
statistic.onlinetime.player=普通玩家
statistic.onlinetime.losePlayer=流失玩家
statistic.onlinetime.loseRechargePlayer=流失充值玩家
statistic.onlinetime.minPay=付费最低值
statistic.onlinetime.maxPay=付费最高值
#玩家元宝消费统计
statistic.goldconsume.pagetitle=元宝用途统计
statistic.goldconsume.reason=消耗途径
statistic.goldconsume.users=消耗人数（帐号）
statistic.goldconsume.totalConsume=消耗数量
statistic.goldconsume.gold=元宝
statistic.goldconsume.bindgold=绑定元宝
statistic.goldconsume.sid=所属服务器
#全服角色信息统计
jsp.roleStatistic.platformName=渠道
jsp.roleStatistic.createsid=创建区服ID
jsp.roleStatistic.funcellUUid=账号名
jsp.roleStatistic.userId=用户ID
jsp.roleStatistic.roleId=角色ID
jsp.roleStatistic.roleName=角色名称
jsp.roleStatistic.level=角色等级
jsp.roleStatistic.onlineTime=在线时长(单位：秒)
jsp.roleStatistic.rechargeGold=充值元宝
jsp.roleStatistic.gold=剩余元宝
jsp.roleStatistic.createTime=角色创建时间
jsp.roleStatistic.lastLoginTime=最后登录时间
jsp.roleStatistic.isDelete=注销时间
jsp.roleStatistic.ts=最后更新时间
#玩家副本活跃度统计
statistic.playeractive.title=玩家副本活跃度统计
statistic.playeractive.row=行数
statistic.playeractive.userId=玩家账号ID
statistic.playeractive.roleId=角色ID
statistic.playeractive.roleName=角色名称
statistic.playeractive.platformName=渠道名称
statistic.playeractive.level=角色等级
statistic.playeractive.serverId=区服ID
statistic.playeractive.cloneName=副本名称
statistic.playeractive.camp=阵营
statistic.playeractive.count=统计次数
statistic.playeractive.date=统计日期
statistic.playeractive.cloneType=副本类型
statistic.playeractive.userRoleCount=统计玩家角色进入副本数
statistic.playeractive.userCount=统计玩家进入副本数
statistic.playeractive.userRoleCountContent=每个玩家下的每一个角色参加此副本的次数
statistic.playeractive.userCountContent=每个玩家参加此副本的次数
#玩家每日登录记录统计
statistic.dailyLogin.title=玩家每日登录记录统计
statistic.dailyLogin.row=行数
statistic.dailyLogin.userId=玩家账号ID
statistic.dailyLogin.roleId=角色ID
statistic.dailyLogin.roleName=角色名称
statistic.dailyLogin.createTime=角色注册时间
statistic.dailyLogin.level=角色等级
statistic.dailyLogin.time=角色当天最后一次登录的时间
statistic.dailyLogin.data=结果数据
statistic.dailyLogin.condition=选择查询条件
statistic.dailyLogin.conditionContent=输入选择条件内容
statistic.dailyLogin.attention=输入的格式为'xxx','xxx' 其中的xxx可以为账号ID、角色ID、以及角色名称
statistic.dailyLogin.queryContent=选择查询内容
statistic.dailyLogin.userLogin=指定玩家新建角色在某日登录情况
statistic.dailyLogin.roleLogin=指定玩家在某日登录情况
#首充统计
statistic.firstRecharge.title=首充统计
statistic.firstRecharge.project=首充项目统计
statistic.firstRecharge.roleLevel=首充角色等级统计
statistic.firstRecharge.rechargeOnlineTime=首充角色付费时间统计
statistic.firstRecharge.date=日期
statistic.firstRecharge.firstRechargeRoles=首充人数
statistic.firstRecharge.proportion=占比（全服付费人数）
statistic.firstRecharge.firstRechargeAmount6=首充6元
statistic.firstRecharge.firstRechargeAmount30=首充30元
statistic.firstRecharge.firstRechargeAmount68=首充68元
statistic.firstRecharge.firstRechargeAmount98=首充98元
statistic.firstRecharge.firstRechargeAmount128=首充128元
statistic.firstRecharge.firstRechargeAmount188=首充188元
statistic.firstRecharge.firstRechargeAmount258=首充258元
statistic.firstRecharge.firstRechargeAmount328=首充328元
statistic.firstRecharge.firstRechargeAmount648=首充648元
statistic.firstRecharge.firstRechargeisMoon1=首充月卡
statistic.firstRecharge.firstRechargeisMoon2=首充尊享卡
statistic.firstRecharge.smallRolesProportion=小号占比
statistic.firstRecharge.roleLevel=角色等级
statistic.firstRecharge.roleCounts=人数
statistic.firstRecharge.time=时间
statistic.firstRecharge.channelRoleCounts=渠道人数
statistic.firstRecharge.serverRoleCounts=服务器人数
#物品、货币流向统计
statistic.itemChange.condition=物品、货币类型选择
statistic.itemChange.reason=原因
statistic.itemChange.consumeAndOutput=产出消耗
statistic.itemChange.consume=消耗
statistic.itemChange.output=产出
#付费次数统计
statistic.rechargeCounts.titile=付费次数统计
statistic.rechargeCounts.rechargeCounts=付费次数
statistic.rechargeCounts.UserCounts=人数
statistic.rechargeCounts.rechargePayment=付费总额
#累充统计
statistic.accumulateRecharge.title=累充统计
statistic.accumulateRecharge.amount=累充金额
statistic.accumulateRecharge.userCounts=人数
statistic.accumulateRecharge.amountAll=充值金额
#二次付费统计
statistic.secondRecharge.data=二次付费统计
statistic.secondRecharge.gap=二次付费间隔统计
statistic.secondRecharge.project=二次付费项目统计
statistic.secondRecharge.gapDays=间隔天数
statistic.secondRecharge.userCounts=人数
statistic.secondRecharge.projects=二次付费项目
#DAU
statistic.dau.date=日期
statistic.dau.DAU=DAU
statistic.dau.titile=DAU统计
statistic.dau.level=统计DAU的等级
#商业化内容统计
statistic.businessContent.buyNum=各时期领取/购买项目人数
statistic.businessContent.continuityBuy=连续购买项
statistic.businessContent.date=日期
statistic.businessContent.one=首冲
statistic.businessContent.two=续冲1
statistic.businessContent.three=续冲2
statistic.businessContent.four=续冲3
statistic.businessContent.five=续冲4
statistic.businessContent.six=续冲5
statistic.businessContent.seven=续冲6
statistic.businessContent.eight=续冲7
statistic.businessContent.nine=续冲8
statistic.businessContent.dayGift=每日礼包
statistic.businessContent.oneGift=1元礼包
statistic.businessContent.threeGift=3元礼包
statistic.businessContent.eightGift=8元礼包
statistic.businessContent.buyRoleNumber=购买人数
statistic.businessContent.continuityRoleNumber=连续购买人数
statistic.businessContent.continuityOne=连续购买1次
statistic.businessContent.continuityTwo=连续购买2次
statistic.businessContent.continuityThree=连续购买3次
statistic.businessContent.continuitySeven=连续购买7次
statistic.businessContent.continuityFourteen=连续购买14次
statistic.businessContent.dailyRecharge=每日累充
statistic.businessContent.dailyRecharge60=60蓝钻
statistic.businessContent.dailyRecharge300=300蓝钻
statistic.businessContent.dailyRecharge680=680蓝钻
#通用
statistic.ConfirmEdit=确认修改？
statistic.configEditSuccess=配置修改成功
statistic.configAddSuccess=配置添加成功
statistic.configEditOrAddFail=配置修改/添加失败
statistic.ConfirmDelete=确认删除？
statistic.configDeleteSuccess=配置删除成功
statistic.configDeleteFail=配置删除失败
statistic.delete=删除
statistic.action=操作
statistic.tips=备注说明
#模型库
statistic.model.modelConfig=模型库配置
statistic.model.modelId=模型ID
statistic.model.scale=模型大小倍数
statistic.model.rotX=旋转参数x
statistic.model.rotY=旋转参数y
statistic.model.rotZ=旋转参数z
statistic.model.posX=位置参数x
statistic.model.posY=位置参数y
statistic.model.tips=模型库的备注
#充值配置
statistic.recharge.rechargeConfig=充值配置
statistic.recharge.id=充值ID
statistic.recharge.systemCfgId=游戏内部配置ID
statistic.recharge.goodsDesc=商品名字描述（主要用于BI后台数据）
statistic.recharge.goods_pay_channel=支付渠道
statistic.recharge.goods_pay_type=支付类型(第三方)
statistic.recharge.type=充值类型
statistic.recharge.subType=充值子类型
statistic.recharge.goodsLimit=充值次数（当前轮每个挡位对应充值的次数)
statistic.recharge.icon=显示的图标的ID
statistic.recharge.money=充值档位对应消耗的真实货币
statistic.recharge.moneyPoint=充值计费点
statistic.recharge.showMoneyIcon=充值默认显示货币
statistic.recharge.reward=充值奖励
statistic.recharge.multiple=充值奖励倍数
statistic.recharge.extraReward=额外奖励
statistic.recharge.extraRewardCount=额外奖励次数
statistic.recharge.isTotalRecharge=是否计入到游戏累充活动
statistic.recharge.totalVipPower=是否增加VIP经验