menu_1=后台管理
menu_2=用户管理
menu_3=用户列表
menu_4=权限管理
menu_5=道具字典
menu_6=菜单管理
menu_7=菜单列表
menu_8=客服管理
menu_9=玩家数据
menu_10=账号角色互查
menu_11=运营管理
menu_12=运营工具
menu_13=充值流程日志
menu_14=激活码生成
menu_15=绑定元宝变化日志
menu_16=用户操作日志
menu_17=日志管理
menu_18=日志查询
menu_19=商城购买日志
menu_20=元宝变化日志
menu_21=活跃奖励日志
menu_22=活动获取日志
menu_23=留存统计
menu_24=公告管理
menu_25=封禁管理
menu_26=踢人下线
menu_27=玩家禁言
menu_28=玩家封号
menu_29=禁言解除
menu_30=帐号解封
menu_31=即时公告
menu_32=邮件管理
menu_33=副本奖励日志
menu_34=邮件发送
menu_35=邮件列表
menu_36=循环公告
menu_37=公会信息
menu_38=日常数据
menu_39=登录邮件
menu_40=在线信息(单服)
menu_41=激活码查询
menu_42=排行榜日志
menu_43=运营活动
menu_44=普通充值活动
menu_45=循环充值活动
menu_46=普通消费活动
menu_47=循环消费活动
menu_48=兑换活动
menu_49=掉落活动
menu_50=刷怪活动
menu_51=领取活动
menu_52=节日赠送活动
menu_53=节日收取活动
menu_54=充值排行活动（单服）
menu_55=消费排行活动
menu_56=赠送排行活动
menu_57=收取排行活动
menu_58=活动验证
menu_59=游戏操作
menu_60=充值成功日志
menu_61=GM命令执行
menu_62=服务器列表
menu_63=日志库列表
menu_64=白名单管理
menu_65=公会成员信息
menu_66=公会动态信息
menu_67=监控条件增删
menu_68=商城购买统计
menu_69=等级分布
menu_70=职业分布
menu_71=排行榜
menu_72=战斗力排行榜
menu_73=等级排行榜
menu_74=在线信息(全服)
menu_75=后台数据
menu_76=后台数据加载
menu_77=DAU统计
menu_78=角色详情(角色ID)
menu_79=财富排行榜
menu_80=竞技排行榜
menu_81=坐骑排行榜
menu_82=骑兵排行榜
menu_83=披风排行榜
menu_84=二次付费统计
menu_85=付费次数统计
menu_86=累充统计
menu_87=宠物升级统计
menu_88=聊天日志查询
menu_89=后台充值
menu_90=角色列表
menu_91=系统开关
menu_92=礼包列表
menu_93=角色转移
menu_94=城市战报名日志
menu_95=进出战场日志
menu_96=活动查询
menu_97=数据统计
menu_98=角色改名日志
menu_99=玩家交易日志
menu_100=后台配置活动查询
menu_101=充值活动模版管理
menu_102=普通活动模版管理
menu_103=玩家结婚日志
menu_104=跨服GM命令执行
menu_105=道具扣除
menu_106=运维工具
menu_107=玩家流失统计
menu_108=玩家充值统计
menu_109=充值排行榜
menu_110=绑定元宝统计
menu_111=坐骑进阶统计
menu_112=黑名单
menu_113=限购活动
menu_114=LTV统计
menu_115=充值金额分布统计
menu_116=阶数分布统计
menu_117=充值发送道具
menu_118=在线时长统计
menu_119=元宝用途统计
menu_120=野怪经验翻倍活动
menu_121=屏蔽关键字
menu_122=元宝扣除
menu_123=天启宝库活动
menu_124=城市争夺战日志
menu_125=王府列表
menu_126=王府信息
menu_127=王府成员
menu_128=王府动态
menu_129=GM命令执行记录
menu_130=全服角色信息统计
menu_131=BOSS存活时间日志
menu_132=击杀BOSS活动
menu_133=跨服副本进入日志
menu_134=跨服副本结束日志
menu_135=跨服日志查询
menu_136=跨服战角色日志
menu_137=战斗奖励创建日志
menu_138=战斗奖励删除日志
menu_139=战斗房间创建日志
menu_140=战斗房间删除日志
menu_141=玩家进入房间日志
menu_142=单服限量购买活动
menu_143=副本进入日志
menu_144=设置充值翻倍
menu_145=充值翻倍活动
menu_146=提供对单个连接的数据库查询
menu_147=服务器参数设置
menu_148=玩家副本活跃度统计
menu_149=悬赏任务日志
menu_150=精英boss日志
menu_151=绑定金币日志
menu_152=荣誉值和军功日志
menu_153=其它货币日志
menu_154=主线任务日志
menu_155=指定玩家每日登录记录
menu_156=装备培养日志
menu_157=装备升星日志
menu_158=玩家收集统计
menu_159=连续充值活动
menu_160=跨服排行活动
menu_161=首杀活动
menu_162=付费总览
menu_163=首充统计
menu_164=物品、货币流向统计
menu_165=限时购买活动
menu_166=云购活动
menu_167=背包查询
menu_168=服务器分组
menu_169=连续登录活动
menu_170=荣耀点活动
menu_171=提交材料活动
menu_172=VIP变化日志
menu_173=王者对决赛奖励日志
menu_175=跨服分区
menu_176=构建分区
menu_177=分区情况
menu_178=商业化内容统计
menu_179=节日活动
menu_180=分享活动
menu_181=后台充值
menu_182=后台充值审核
menu_183=后台充值列表
menu_184=滚服数据统计
menu_185=充值服务器列表有效性
menu_186=头像审核
menu_187=自定义头像
menu_188=头像审核开关