#
jsp.role.title=Поиск информации о персонаже
jsp.role.norole=Информация о персонаже не найдена
jsp.role.nouserid=ID аккаунта не найден
jsp.role.noaccount=Информация об аккаунте не найдена
jsp.role.nolslog=Не удалось подключиться к базе данных LoginServerLog
jsp.role.dataerror=Ошибка данных, обратитесь к администратору
jsp.role.showdetail=Показать детали персонажа
jsp.role.logoff=Аннулирован
jsp.role.nologoff=Не аннулирован
jsp.role.logouttime=Время аннулирования
jsp.rolelog.nodata=Данные не найдены
jsp.rolelog.noroleid=Введите ID персонажа
jsp.role.roledetail=Страница детальной информации о персонаже
jsp.role.pleasetypenum=Введите число!
jsp.role.searchcon=Условия поиска
jsp.role.rolename=Имя персонажа
jsp.role.account=Имя аккаунта
jsp.role.roleid=ID персонажа
jsp.role.roleidIn10=ID персонажа (десятичный)
jsp.role.roleidIn36=ID персонажа (36-ричный)
jsp.role.userid=ID аккаунта
jsp.role.search=Поиск
jsp.role.out=Аннулирован
jsp.role.noout=Не аннулирован
jsp.role.roleinfo=Информация о персонаже
jsp.role.level=Уровень
jsp.role.sex=Пол
jsp.role.career=Класс
jsp.role.money=Монеты
jsp.role.gold=Бриллианты
jsp.role.groupNo=Исходный лагерь
jsp.role.iron=Энергия
jsp.role.server=Сервер
jsp.role.rechargegold=Пополнено монет
jsp.role.ct=Время создания
jsp.role.ip=IP входа
jsp.role.isdelete=Аннулирован
jsp.role.fcaccount=Имя аккаунта
jsp.role.channel=Канал
jsp.role.moonCardDay=Дней месячной карты
jsp.role.action=Действие
jsp.role.acinfo=Информация об аккаунте
jsp.role.acname=Имя аккаунта
jsp.role.acid=ID аккаунта
jsp.role.acpfaccount=Аккаунт канала
jsp.role.acplatform=Название канала
jsp.role.acct=Время создания
jsp.role.aclt=Последний вход
jsp.role.acip=IP входа
jsp.role.mac=MAC-адрес
jsp.role.imei=IMEI
jsp.role.machineCode=Уникальный код устройства
jsp.role.sdateempty=Дата начала не может быть пустой!
jsp.role.edateempty=Дата окончания не может быть пустой!
jsp.role.sdatelessthanedate=Дата окончания не может быть меньше даты начала!
jsp.rolelog.searchDate=Время поиска по логам
jsp.rolelog.no=Нет
jsp.rolelog.yes=Да
jsp.rolelog.power=Сила:
jsp.rolelog.vigour=Энергия:
jsp.rolelog.body=Ловкость:
jsp.rolelog.phy=Телосложение:
jsp.rolelog.material=Материал для улучшения звёзд:
jsp.rolelog.num=Количество материала:
#
jsp.rolelog.rolelogin=Логи входа
jsp.rolelog.rolelogout=Логи выхода
jsp.rolelogout.platform=Канал
jsp.rolelogout.server=Сервер
jsp.rolelogout.level=Уровень
jsp.rolelogout.career=Класс
jsp.rolelogout.time=Время
jsp.rolelogout.ip=IP
#
jsp.rolelog.bindgoldchange=Логи изменения бонусных монет
jsp.bindgoldchange.platform=Канал
jsp.bindgoldchange.server=Сервер
jsp.bindgoldchange.level=Уровень
jsp.bindgoldchange.before=До
jsp.bindgoldchange.after=После
jsp.bindgoldchange.num=Изменение
jsp.bindgoldchange.reason=Причина
jsp.bindgoldchange.time=Время
jsp.bindgoldchange.ip=IP
jsp.bindgoldchange.actionid=Уникальный идентификатор
#
jsp.rolelog.goldchange=Логи изменения монет
jsp.goldchange.platform=Канал
jsp.goldchange.server=Сервер
jsp.goldchange.level=Уровень
jsp.goldchange.before=До
jsp.goldchange.after=После
jsp.goldchange.num=Изменение
jsp.goldchange.reason=Причина
jsp.goldchange.time=Время
jsp.goldchange.ip=IP
jsp.goldchange.actionid=Уникальный идентификатор
#
jsp.rolelog.moneychange=Логи изменения монет (золото)
jsp.moneychange.platform=Канал
jsp.moneychange.server=Сервер
jsp.moneychange.level=Уровень
jsp.moneychange.before=До
jsp.moneychange.after=После
jsp.moneychange.num=Изменение
jsp.moneychange.moneytype=Тип валюты
jsp.moneychange.reason=Причина
jsp.moneychange.time=Время
jsp.moneychange.ip=IP
jsp.moneychange.actionid=Уникальный идентификатор
#
jsp.rolelog.coinchange=Логи изменения валюты
jsp.coinchange.platform=Канал
jsp.coinchange.server=Сервер
jsp.coinchange.level=Уровень
jsp.coinchange.before=До
jsp.coinchange.after=После
jsp.coinchange.num=Изменение
jsp.coinchange.moneytype=Тип валюты
jsp.coinchange.reason=Причина
jsp.coinchange.time=Время
jsp.coinchange.ip=IP
jsp.coinchange.actionid=Уникальный идентификатор
#
jsp.rolelog.zhenqiandtiechange=Логи изменения военной заслуги и чести
jsp.zhenqiandtiechange.platform=Канал
jsp.zhenqiandtiechange.server=Сервер
jsp.zhenqiandtiechange.level=Уровень
jsp.zhenqiandtiechange.before=До
jsp.zhenqiandtiechange.after=После
jsp.zhenqiandtiechange.num=Изменение
jsp.zhenqiandtiechange.moneytype=Тип валюты
jsp.zhenqiandtiechange.reason=Причина
jsp.zhenqiandtiechange.time=Время
jsp.zhenqiandtiechange.ip=IP
jsp.zhenqiandtiechange.actionid=Уникальный идентификатор
#
jsp.rolelog.itemchange=Логи предметов
jsp.itemchange.platform=Канал
jsp.itemchange.server=Сервер
jsp.itemchange.level=Уровень
jsp.itemchange.before=До
jsp.itemchange.after=После
jsp.itemchange.num=Изменение
jsp.itemchange.modelid=ID предмета
jsp.itemchange.reason=Причина
jsp.itemchange.time=Время
jsp.itemchange.changeaction=Действие
jsp.itemchange.actionid=Уникальный идентификатор
#
jsp.rolelog.shopbuy=Логи покупок в магазине
jsp.shopbuy.platform=Канал
jsp.shopbuy.server=Сервер
jsp.shopbuy.level=Уровень
jsp.shopbuy.shopid=ID магазина
jsp.shopbuy.itemmodelid=ID предмета
jsp.shopbuy.buyTimes=Количество покупок
jsp.shopbuy.realnum=Количество
jsp.shopbuy.moneytype=Тип валюты
jsp.shopbuy.moneynum=Количество валюты
jsp.shopbuy.sellId=ID товара
jsp.shopbuy.reasoncode=Код причины
jsp.shopbuy.fromsrc=ID вкладки
jsp.shopbuy.time=Время
jsp.shopbuy.actionid=Уникальный идентификатор
#
jsp.rolelog.buy=Логи покупок на бирже
jsp.buy.itemId=Уникальный ID предмета
jsp.buy.itemmodelid=ID предмета
jsp.buy.num=Количество
jsp.buy.trantype=Тип транзакции
jsp.buy.coinnum=Потрачено валюты
jsp.buy.cointype=Тип валюты
jsp.buy.sellrolename=Имя продавца
jsp.buy.sellplatform=Канал продавца
jsp.buy.time=Время
jsp.buy.actionid=Уникальный идентификатор
#
jsp.rolelog.sell=Логи продаж на бирже
jsp.sell.itemId=Уникальный ID предмета
jsp.sell.itemmodelid=ID предмета
jsp.sell.num=Количество
jsp.sell.trantype=Тип транзакции
jsp.sell.coinnum=Потрачено валюты
jsp.sell.cointype=Тип валюты
jsp.sell.buyrolename=Имя покупателя
jsp.sell.buyplatform=Канал покупателя
jsp.sell.time=Время
jsp.sell.actionid=Уникальный идентификатор
#
jsp.rolelog.levelchange=Логи изменения уровня
jsp.levelchange.server=Сервер
jsp.levelchange.beforeexp=Опыт до
jsp.levelchange.afterexp=Опыт после
jsp.levelchange.changeexp=Изменение опыта
jsp.levelchange.oldlevel=Уровень до
jsp.levelchange.nowlevel=Уровень после
jsp.levelchange.reason=Причина
jsp.levelchange.time=Время
jsp.levelchange.actionid=Уникальный идентификатор
#
jsp.rolelog.skill=Логи улучшения навыков
jsp.skill.server=Сервер
jsp.skill.skillid=Навык
jsp.skill.level=Уровень
jsp.skill.action=Действие
jsp.skill.consume=Потребление
jsp.skill.time=Время
jsp.skill.actionid=Уникальный идентификатор
#
jsp.rolelog.rechargesuccess=Логи пополнения
jsp.rechargesuccess.platformName=Название канала
jsp.rechargesuccess.orderId=ID заказа
jsp.rechargesuccess.amount=Сумма пополнения
jsp.rechargesuccess.currency=Валюта
jsp.rechargesuccess.sid=Сервер
jsp.rechargesuccess.gold=Получено монет
jsp.rechargesuccess.gift=Бонусные монеты
jsp.rechargesuccess.actionId=Связанный ID
jsp.rechargesuccess.oid=ID заказа канала
jsp.rechargesuccess.itemId=ID товара
jsp.rechargesuccess.level=Уровень
jsp.rechargesuccess.isMoon=Месячная карта
jsp.rechargesuccess.time=Время
jsp.rechargesuccess.allAmount=Общая сумма
jsp.rechargesuccess.allGold=Всего монет
jsp.rechargesuccess.moon=Месячная карта
jsp.rechargesuccess.noMoon=Не месячная карта
#
jsp.rolelog.dragoonup=Логи улучшения дракона
jsp.dragoonup.server=Сервер
jsp.dragoonup.beforeupnum=Количество улучшений до
jsp.dragoonup.afterupnum=Количество улучшений после
jsp.dragoonup.beforekey=Уровень до
jsp.dragoonup.afterkey=Уровень после
jsp.dragoonup.beforebless=Благословение до
jsp.dragoonup.afterbless=Благословение после
jsp.dragoonup.costbindedgold=Потрачено бонусных монет
jsp.dragoonup.costgold=Потрачено монет
jsp.dragoonup.time=Время
jsp.dragoonup.actionid=Уникальный идентификатор
#
jsp.rolelog.dragoonskillup=Логи улучшения навыков дракона
jsp.dragoonskillup.server=Сервер
jsp.dragoonskillup.beforeexp=Опыт до
jsp.dragoonskillup.afterexp=Опыт после
jsp.dragoonskillup.beforelevel=Уровень до
jsp.dragoonskillup.afterlevel=Уровень после
jsp.dragoonskillup.skilldataid=ID навыка
jsp.dragoonskillup.time=Время
jsp.dragoonskillup.actionid=Уникальный идентификатор
#
jsp.rolelog.horseup=Логи улучшения скакуна
jsp.horseup.server=Сервер
jsp.horseup.beforebless=Благословение до
jsp.horseup.afterbless=Благословение после
jsp.horseup.addbless=Прирост благословения
jsp.horseup.upitemid=ID предмета
jsp.horseup.upitemnum=Количество предметов
jsp.horseup.curuptimes=Количество улучшений
jsp.horseup.beforehorselayer=Уровень скакуна до
jsp.horseup.upresult=Результат
jsp.horseup.time=Время
#
jsp.rolelog.horseskillup=Логи улучшения навыков скакуна
jsp.horseskillup.server=Сервер
jsp.horseskillup.beforeexp=Опыт до
jsp.horseskillup.afterexp=Опыт после
jsp.horseskillup.addexp=Прирост опыта
jsp.horseskillup.skillid=ID навыка
jsp.horseskillup.isskilllevelup=Уровень повышен
jsp.horseskillup.skilllevel=Уровень навыка
jsp.horseskillup.upitemid=ID предмета
jsp.horseskillup.upitemnum=Количество предметов
jsp.horseskillup.time=Время
#
jsp.rolelog.cloakup=Логи улучшения плаща
jsp.cloakup.server=Сервер
jsp.cloakup.beforebless=Благословение до
jsp.cloakup.afterbless=Благословение после
jsp.cloakup.addbless=Прирост благословения
jsp.cloakup.upitemid=ID предмета
jsp.cloakup.upitemnum=Количество предметов
jsp.cloakup.curuptimes=Количество улучшений
jsp.cloakup.beforecloaklayer=Уровень плаща до
jsp.cloakup.upresult=Результат
jsp.cloakup.skillactivated=Навык активирован
jsp.cloakup.time=Время
#
jsp.rolelog.cloakskillup=Логи улучшения навыков плаща
jsp.cloakskillup.server=Сервер
jsp.cloakskillup.beforeexp=Опыт до
jsp.cloakskillup.afterexp=Опыт после
jsp.cloakskillup.addexp=Прирост опыта
jsp.cloakskillup.skillId=ID навыка
jsp.cloakskillup.isskilllevelup=Уровень повышен
jsp.cloakskillup.skilllevel=Уровень навыка
jsp.cloakskillup.upitemid=ID предмета
jsp.cloakskillup.upitemnum=Количество предметов
jsp.cloakskillup.time=Время
#
jsp.rolelog.equipstreng=Логи улучшения экипировки
jsp.equipstreng.server=Сервер
jsp.equipstreng.platformName=Название платформы
jsp.equipstreng.equipId1=Уникальный ID предмета
jsp.equipstreng.modelid1=ID модели предмета
jsp.equipstreng.equipId2=Уникальный ID материала
jsp.equipstreng.modelid2=ID модели материала
jsp.equipstreng.equipId2Att=Атрибуты материала
jsp.equipstreng.expend=Потребление
jsp.equipstreng.time=Время
jsp.equipstreng.actioinid=Уникальный идентификатор
#
jsp.rolelog.equipupstar=Логи улучшения звёзд экипировки
jsp.equipupstar.server=Сервер
jsp.equipupstar.expend=Потребление
jsp.equipupstar.part=Часть
jsp.equipupstar.startlv=Уровень звёзд до
jsp.equipupstar.endlv=Уровень звёзд после
jsp.equipupstar.time=Время
jsp.equipupstar.actioinId=Уникальный идентификатор
#
jsp.rolelog.expchange=Логи изменения опыта
jsp.expchange.server=Сервер
jsp.expchange.beforenum=Опыт до
jsp.expchange.afternum=Опыт после
jsp.expchange.changenum=Изменение опыта
jsp.expchange.rolelevel=Уровень после
jsp.expchange.reason=Причина
jsp.expchange.time=Время
jsp.expchange.actionId=Уникальный идентификатор
#
jsp.rolelog.playerattpointchange=Логи изменения характеристик
jsp.playerattpointchange.type=Тип изменения
jsp.playerattpointchange.beforev=До
jsp.playerattpointchange.afterv=После
jsp.playerattpointchange.remain=Остаток
jsp.playerattpointchange.time=Время
jsp.playerattpointchange.actionid=Уникальный идентификатор
#
jsp.rolelog.maintask=Логи сюжетных заданий
jsp.maintask.sid=Сервер
jsp.maintask.platfromname=Канал
jsp.maintask.accmodelid=ID принятого задания
jsp.maintask.acclevel=Уровень при принятии
jsp.maintask.accmoney=Монет при принятии
jsp.maintask.acconlinetime=Время в сети при принятии (мс)
jsp.maintask.fshmodelid=ID завершённого задания
jsp.maintask.fshlevel=Уровень при завершении
jsp.maintask.fshmoney=Монет при завершении
jsp.maintask.fshonlinetime=Время в сети при завершении (мс)
jsp.maintask.accbeforereceiveable=accbeforeReceiveAble
jsp.maintask.accafterreceiveable=accafterReceiveAble
jsp.maintask.time=Время
#
jsp.rolelog.mail=Логи почты
jsp.mail.mailid=ID письма
jsp.mail.mailtitle=Заголовок
jsp.mail.mailvontend=Содержание
jsp.mail.receivetime=Время получения
jsp.mail.sender=Отправитель
jsp.mail.mailaction=Действие
jsp.mail.isread=Прочитано
jsp.mail.hasattachment=Есть вложение
jsp.mail.attachment=Вложение
jsp.mail.isattachreceived=Вложение получено
jsp.mail.time=Время
jsp.mail.sendInterval=Интервал отправки
jsp.mail.type=Тип письма
#
jsp.rolelog.pray=Логи молитв
jsp.pray.sid=Сервер
jsp.pray.type=Тип молитвы
jsp.pray.prayitems=Предметы молитвы
jsp.pray.time=Время
#
jsp.rolelog.worship=Логи поклонения
jsp.worship.worshipday=Дней поклонения
jsp.worship.worshipplayerid=ID персонажа
jsp.worship.todayworshipnum=Количество поклонений
jsp.worship.worshippedplayeridset=Записи поклонений
jsp.worship.time=Время
#
jsp.rolelog.cellopen=Логи открытия ячеек
jsp.cellopen.sid=Сервер
jsp.cellopen.beforecells=Ячеек до
jsp.cellopen.aftercells=Ячеек после
jsp.cellopen.celltype=Тип ячеек
jsp.cellopen.actiontype=Тип операции
jsp.cellopen.resumgold=Потрачено монет
jsp.cellopen.time=Время
jsp.cellopen.actionid=Уникальный идентификатор
#
jsp.rolelog.chat=Логи чата
jsp.chat.sid=Сервер
jsp.chat.channel=Канал
jsp.chat.content=Содержание
jsp.chat.receroleid=ID получателя
jsp.chat.time=Время
#
jsp.rolelog.horseillusion=Логи иллюзий скакуна
jsp.horseillusion.createsid=Сервер
jsp.horseillusion.curHighestLayer=Максимальный уровень
jsp.horseillusion.afterIllusionLevel=Уровень иллюзии после
jsp.horseillusion.illusionItemId=ID предмета
jsp.horseillusion.illusionItemNum=Количество предметов
jsp.horseillusion.time=Время
#
jsp.rolelog.conquertaskaccept=Логи принятия заданий охоты
jsp.conquertaskaccept.sid=Сервер
jsp.conquertaskaccept.platformName=Название платформы
jsp.conquertaskaccept.taskmodelid=ID задания
jsp.conquertaskaccept.taskinfo=Информация о задании
jsp.conquertaskaccept.taskCount=Номер задания
jsp.conquertaskaccept.time=Время
#
jsp.rolelog.vipgetgift=Логи получения VIP-наград
jsp.vipgetgift.sid=Сервер
jsp.vipgetgift.getvipgift=Уровень награды
jsp.vipgetgift.nowviplevel=Текущий VIP-уровень
jsp.vipgetgift.time=Время
jsp.vipgetgift.actionid=Уникальный идентификатор
#
jsp.rolelog.baokutanmi=Логи битвы за ресурсы
jsp.baokutanmi.sid=Сервер
jsp.baokutanmi.platform=Платформа
jsp.baokutanmi.gatherid=ID собираемого предмета
jsp.baokutanmi.gathertimes=Количество сборов
jsp.baokutanmi.reward=Награда
jsp.baokutanmi.rewardbei=Множитель награды
jsp.baokutanmi.time=Время
#
jsp.rolelog.challengefirstreward=Логи награды за первое место на арене
jsp.challengefirstreward.sid=Сервер
jsp.challengefirstreward.platform=Платформа
jsp.challengefirstreward.reward=Награда
jsp.challengefirstreward.type=Тип
jsp.challengefirstreward.oldlevel=Уровень до
jsp.challengefirstreward.changelevel=Изменение уровня
jsp.challengefirstreward.time=Время
jsp.challengefirstreward.actionid=Уникальный идентификатор
#
jsp.rolelog.conloginreward=Логи наград за непрерывный вход
jsp.conloginreward.sid=Сервер
jsp.conloginreward.curconlogindays=Дней входа
jsp.conloginreward.rewardday=День награды
jsp.conloginreward.rewarditems=Предметы награды
jsp.conloginreward.time=Время
#
jsp.rolelog.copymaplogrecord=Логи наград в подземельях
jsp.copymaplogrecord.sid=Сервер
jsp.copymaplogrecord.platform=Платформа
jsp.copymaplogrecord.zonemodelid=ID подземелья
jsp.copymaplogrecord.issuccess=Успех
jsp.copymaplogrecord.type=Тип прохода
jsp.copymaplogrecord.score=Очки
jsp.copymaplogrecord.copyovertime=Время завершения
jsp.copymaplogrecord.reward=Награда
jsp.copymaplogrecord.dcreward=Награда за ранг
jsp.copymaplogrecord.time=Время
jsp.copymaplogrecord.actionid=Уникальный идентификатор
#
jsp.rolelog.cpmutilreward=Логи наград групповых подземелий
jsp.cpmutilreward.sid=Сервер
jsp.cpmutilreward.platform=Канал
jsp.cpmutilreward.cpid=Уникальный ID подземелья
jsp.cpmutilreward.cpmodelid=ID подземелья
jsp.cpmutilreward.reward=Награда
jsp.cpmutilreward.needgold=Требуется монет
jsp.cpmutilreward.beinum=Множитель награды
jsp.cpmutilreward.time=Время
jsp.cpmutilreward.actionid=Уникальный идентификатор
#
jsp.rolelog.levelreward=Логи наград за уровень
jsp.levelreward.sid=Сервер
jsp.levelreward.rewarditems=Награда
jsp.levelreward.curlevel=Текущий уровень
jsp.levelreward.rewardlevel=Уровень награды
jsp.levelreward.curtransferdegree=Текущий уровень класса
jsp.levelreward.time=Время
#
jsp.rolelog.onlinereward=Логи наград за онлайн
jsp.onlinereward.sid=Сервер
jsp.onlinereward.rewarditems=Награда
jsp.onlinereward.curonlinetime=Время в сети
jsp.onlinereward.rewardonlinetime=Требуемое время
jsp.onlinereward.time=Время
#
jsp.rolelog.seektreasure=Логи наград за поиск сокровищ
jsp.seektreasure.sid=Сервер
jsp.seektreasure.rewarditems=Награда
jsp.seektreasure.type=Тип
jsp.seektreasure.consumeitemid=ID предмета
jsp.seektreasure.consumeitemnum=Количество предметов
jsp.seektreasure.time=Время
#
jsp.rolelog.signreward=Логи наград за подписку
jsp.signreward.sid=Сервер
jsp.signreward.rewarditems=Награда
jsp.signreward.curmonth=Месяц
jsp.signreward.cursignnum=Отметок в месяце
jsp.signreward.curtotalsignnum=Всего отметок
jsp.signreward.time=Время
#
jsp.rolelog.dailyrechargerewardget=Логи получения ежедневных бонусов
jsp.dailyrechargerewardget.sid=Сервер
jsp.dailyrechargerewardget.rewardId=Уровень награды
jsp.dailyrechargerewardget.rewardItems=Награда
jsp.dailyrechargerewardget.time=Время
#
jsp.rolelog.pet=Логи питомцев
jsp.pet.sid=Сервер
jsp.pet.petID=ID питомца
jsp.pet.level=Уровень питомца
jsp.pet.actionType=Тип операции
jsp.pet.time=Время