jsp.shoplist.id=商品ID
jsp.shoplist.type=配置类型
jsp.shoplist.itemID=道具
jsp.shoplist.shopID=所属商城
jsp.shoplist.shopType=商城标签
jsp.shoplist.labelID=标签ID
jsp.shoplist.level=需求等级
jsp.shoplist.guildLevel=需求帮会等级
jsp.shoplist.guildShopLvl=需求仙盟等级
jsp.shoplist.vipLevel=需求境界等级
jsp.shoplist.occupation=职业限制
jsp.shoplist.limitType=限购类型
jsp.shoplist.buyNum=可购买次数
jsp.shoplist.currencyID=货币
jsp.shoplist.price=打折前价格
jsp.shoplist.discountPrice=打折后价格
jsp.shoplist.discount=打折数
jsp.shoplist.promotion=促销标签
jsp.shoplist.sort=排列优先级
jsp.shoplist.upTime=上架时间
jsp.shoplist.downTime=下架时间
jsp.shoplist.bind=是否绑定
jsp.shoplist.refreshCurrency=刷新使用货币类型
jsp.shoplist.refreshNum=刷新货币消耗数
jsp.shoplist.worldLvl=需求世界等级
jsp.shoplist.isDiscount=是否修神锻体打折

jsp.shoplist.chooseShopType=商城类型
jsp.shoplist.shopId0=所有
jsp.shoplist.shopId1=元宝商城
jsp.shoplist.shopId2=兑换商城
jsp.shoplist.shopId3=福地积分商店
jsp.shoplist.shopId4=仙盟贡献商店

jsp.shoplist.career-1=不限职业
jsp.shoplist.career0=玄剑
jsp.shoplist.career1=天英
jsp.shoplist.career2=地藏
jsp.shoplist.career3=罗刹

jsp.shoplist.limit0=不限购
jsp.shoplist.limit1=日限购
jsp.shoplist.limit2=周限购
jsp.shoplist.limit3=月限购
jsp.shoplist.limit4=年限购
jsp.shoplist.limit5=终身限购


jsp.shoplist.promotion0=无
jsp.shoplist.promotion1=打折
jsp.shoplist.promotion2=推荐
jsp.shoplist.promotion3=新品
jsp.shoplist.promotion4=热卖

jsp.shoplist.plat=平台
jsp.shoplist.server=区服
jsp.shoplist.operate=操作
jsp.shoplist.unknow=未知
jsp.shoplist.yes=是
jsp.shoplist.no=否
jsp.shoplist.isbind=绑定
jsp.shoplist.nobind=非绑