// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gm.proto

package game.message;

public final class GmMessage {
  private GmMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface GmCommandClientToServerOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string command = 1;
    /**
     * <code>required string command = 1;</code>
     *
     * <pre>
     *Gm命令
     * </pre>
     */
    boolean hasCommand();
    /**
     * <code>required string command = 1;</code>
     *
     * <pre>
     *Gm命令
     * </pre>
     */
    java.lang.String getCommand();
    /**
     * <code>required string command = 1;</code>
     *
     * <pre>
     *Gm命令
     * </pre>
     */
    com.google.protobuf.ByteString
        getCommandBytes();
  }
  /**
   * Protobuf type {@code MSG_Gm.GmCommandClientToServer}
   *
   * <pre>
   *Client-&gt;Game 由客户端发出的游戏内部GM命令
   * </pre>
   */
  public static final class GmCommandClientToServer extends
      com.google.protobuf.GeneratedMessage
      implements GmCommandClientToServerOrBuilder {
    // Use GmCommandClientToServer.newBuilder() to construct.
    private GmCommandClientToServer(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GmCommandClientToServer(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GmCommandClientToServer defaultInstance;
    public static GmCommandClientToServer getDefaultInstance() {
      return defaultInstance;
    }

    public GmCommandClientToServer getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GmCommandClientToServer(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              command_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return game.message.GmMessage.internal_static_MSG_Gm_GmCommandClientToServer_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return game.message.GmMessage.internal_static_MSG_Gm_GmCommandClientToServer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              game.message.GmMessage.GmCommandClientToServer.class, game.message.GmMessage.GmCommandClientToServer.Builder.class);
    }

    public static com.google.protobuf.Parser<GmCommandClientToServer> PARSER =
        new com.google.protobuf.AbstractParser<GmCommandClientToServer>() {
      public GmCommandClientToServer parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GmCommandClientToServer(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GmCommandClientToServer> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code MSG_Gm.GmCommandClientToServer.MsgID}
     */
    public enum MsgID
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>eMsgID = 110201;</code>
       */
      eMsgID(0, 110201),
      ;

      /**
       * <code>eMsgID = 110201;</code>
       */
      public static final int eMsgID_VALUE = 110201;


      public final int getNumber() { return value; }

      public static MsgID valueOf(int value) {
        switch (value) {
          case 110201: return eMsgID;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MsgID>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<MsgID>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MsgID>() {
              public MsgID findValueByNumber(int number) {
                return MsgID.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return game.message.GmMessage.GmCommandClientToServer.getDescriptor().getEnumTypes().get(0);
      }

      private static final MsgID[] VALUES = values();

      public static MsgID valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private MsgID(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:MSG_Gm.GmCommandClientToServer.MsgID)
    }

    private int bitField0_;
    // required string command = 1;
    public static final int COMMAND_FIELD_NUMBER = 1;
    private java.lang.Object command_;
    /**
     * <code>required string command = 1;</code>
     *
     * <pre>
     *Gm命令
     * </pre>
     */
    public boolean hasCommand() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string command = 1;</code>
     *
     * <pre>
     *Gm命令
     * </pre>
     */
    public java.lang.String getCommand() {
      java.lang.Object ref = command_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          command_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string command = 1;</code>
     *
     * <pre>
     *Gm命令
     * </pre>
     */
    public com.google.protobuf.ByteString
        getCommandBytes() {
      java.lang.Object ref = command_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        command_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      command_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasCommand()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getCommandBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getCommandBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static game.message.GmMessage.GmCommandClientToServer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static game.message.GmMessage.GmCommandClientToServer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static game.message.GmMessage.GmCommandClientToServer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static game.message.GmMessage.GmCommandClientToServer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static game.message.GmMessage.GmCommandClientToServer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static game.message.GmMessage.GmCommandClientToServer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static game.message.GmMessage.GmCommandClientToServer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static game.message.GmMessage.GmCommandClientToServer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static game.message.GmMessage.GmCommandClientToServer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static game.message.GmMessage.GmCommandClientToServer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(game.message.GmMessage.GmCommandClientToServer prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MSG_Gm.GmCommandClientToServer}
     *
     * <pre>
     *Client-&gt;Game 由客户端发出的游戏内部GM命令
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements game.message.GmMessage.GmCommandClientToServerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return game.message.GmMessage.internal_static_MSG_Gm_GmCommandClientToServer_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return game.message.GmMessage.internal_static_MSG_Gm_GmCommandClientToServer_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                game.message.GmMessage.GmCommandClientToServer.class, game.message.GmMessage.GmCommandClientToServer.Builder.class);
      }

      // Construct using game.message.GmMessage.GmCommandClientToServer.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        command_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return game.message.GmMessage.internal_static_MSG_Gm_GmCommandClientToServer_descriptor;
      }

      public game.message.GmMessage.GmCommandClientToServer getDefaultInstanceForType() {
        return game.message.GmMessage.GmCommandClientToServer.getDefaultInstance();
      }

      public game.message.GmMessage.GmCommandClientToServer build() {
        game.message.GmMessage.GmCommandClientToServer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public game.message.GmMessage.GmCommandClientToServer buildPartial() {
        game.message.GmMessage.GmCommandClientToServer result = new game.message.GmMessage.GmCommandClientToServer(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.command_ = command_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof game.message.GmMessage.GmCommandClientToServer) {
          return mergeFrom((game.message.GmMessage.GmCommandClientToServer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(game.message.GmMessage.GmCommandClientToServer other) {
        if (other == game.message.GmMessage.GmCommandClientToServer.getDefaultInstance()) return this;
        if (other.hasCommand()) {
          bitField0_ |= 0x00000001;
          command_ = other.command_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCommand()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        game.message.GmMessage.GmCommandClientToServer parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (game.message.GmMessage.GmCommandClientToServer) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string command = 1;
      private java.lang.Object command_ = "";
      /**
       * <code>required string command = 1;</code>
       *
       * <pre>
       *Gm命令
       * </pre>
       */
      public boolean hasCommand() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string command = 1;</code>
       *
       * <pre>
       *Gm命令
       * </pre>
       */
      public java.lang.String getCommand() {
        java.lang.Object ref = command_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          command_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string command = 1;</code>
       *
       * <pre>
       *Gm命令
       * </pre>
       */
      public com.google.protobuf.ByteString
          getCommandBytes() {
        java.lang.Object ref = command_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          command_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string command = 1;</code>
       *
       * <pre>
       *Gm命令
       * </pre>
       */
      public Builder setCommand(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        command_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string command = 1;</code>
       *
       * <pre>
       *Gm命令
       * </pre>
       */
      public Builder clearCommand() {
        bitField0_ = (bitField0_ & ~0x00000001);
        command_ = getDefaultInstance().getCommand();
        onChanged();
        return this;
      }
      /**
       * <code>required string command = 1;</code>
       *
       * <pre>
       *Gm命令
       * </pre>
       */
      public Builder setCommandBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        command_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:MSG_Gm.GmCommandClientToServer)
    }

    static {
      defaultInstance = new GmCommandClientToServer(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:MSG_Gm.GmCommandClientToServer)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_MSG_Gm_GmCommandClientToServer_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MSG_Gm_GmCommandClientToServer_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\010gm.proto\022\006MSG_Gm\"A\n\027GmCommandClientToS" +
      "erver\022\017\n\007command\030\001 \002(\t\"\025\n\005MsgID\022\014\n\006eMsgI" +
      "D\020\371\334\006B\031\n\014game.messageB\tGmMessage"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_MSG_Gm_GmCommandClientToServer_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_MSG_Gm_GmCommandClientToServer_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_MSG_Gm_GmCommandClientToServer_descriptor,
              new java.lang.String[] { "Command", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
