// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: platformevaluate.proto

package game.message;

public final class PlatformEvaluateMessage {
  private PlatformEvaluateMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ResEvaluateInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 like = 1;
    /**
     * <code>optional int32 like = 1;</code>
     *
     * <pre>
     *0未点赞,1已点赞,2已领取
     * </pre>
     */
    boolean hasLike();
    /**
     * <code>optional int32 like = 1;</code>
     *
     * <pre>
     *0未点赞,1已点赞,2已领取
     * </pre>
     */
    int getLike();

    // optional int32 share = 2;
    /**
     * <code>optional int32 share = 2;</code>
     *
     * <pre>
     *0未分享,1已分享,2已领取
     * </pre>
     */
    boolean hasShare();
    /**
     * <code>optional int32 share = 2;</code>
     *
     * <pre>
     *0未分享,1已分享,2已领取
     * </pre>
     */
    int getShare();

    // optional int32 evaluate = 3;
    /**
     * <code>optional int32 evaluate = 3;</code>
     *
     * <pre>
     *0未评价,1已评价
     * </pre>
     */
    boolean hasEvaluate();
    /**
     * <code>optional int32 evaluate = 3;</code>
     *
     * <pre>
     *0未评价,1已评价
     * </pre>
     */
    int getEvaluate();

    // optional bool openLike = 4;
    /**
     * <code>optional bool openLike = 4;</code>
     *
     * <pre>
     *后台是否开启点赞
     * </pre>
     */
    boolean hasOpenLike();
    /**
     * <code>optional bool openLike = 4;</code>
     *
     * <pre>
     *后台是否开启点赞
     * </pre>
     */
    boolean getOpenLike();

    // optional bool openShare = 5;
    /**
     * <code>optional bool openShare = 5;</code>
     *
     * <pre>
     *后台是否开启分享
     * </pre>
     */
    boolean hasOpenShare();
    /**
     * <code>optional bool openShare = 5;</code>
     *
     * <pre>
     *后台是否开启分享
     * </pre>
     */
    boolean getOpenShare();

    // optional int32 everyDayShare = 6;
    /**
     * <code>optional int32 everyDayShare = 6;</code>
     *
     * <pre>
     *每日分享  0未分享,1已分享,2已领取
     * </pre>
     */
    boolean hasEveryDayShare();
    /**
     * <code>optional int32 everyDayShare = 6;</code>
     *
     * <pre>
     *每日分享  0未分享,1已分享,2已领取
     * </pre>
     */
    int getEveryDayShare();

    // optional bool openEveryDayShare = 7;
    /**
     * <code>optional bool openEveryDayShare = 7;</code>
     *
     * <pre>
     *后台是否开启每天分享
     * </pre>
     */
    boolean hasOpenEveryDayShare();
    /**
     * <code>optional bool openEveryDayShare = 7;</code>
     *
     * <pre>
     *后台是否开启每天分享
     * </pre>
     */
    boolean getOpenEveryDayShare();

    // optional int32 shopEvaluate = 8;
    /**
     * <code>optional int32 shopEvaluate = 8;</code>
     *
     * <pre>
     *商店评价 0未评价,1已评价
     * </pre>
     */
    boolean hasShopEvaluate();
    /**
     * <code>optional int32 shopEvaluate = 8;</code>
     *
     * <pre>
     *商店评价 0未评价,1已评价
     * </pre>
     */
    int getShopEvaluate();

    // optional bool openShopEvaluate = 9;
    /**
     * <code>optional bool openShopEvaluate = 9;</code>
     *
     * <pre>
     *后台是否商店评价
     * </pre>
     */
    boolean hasOpenShopEvaluate();
    /**
     * <code>optional bool openShopEvaluate = 9;</code>
     *
     * <pre>
     *后台是否商店评价
     * </pre>
     */
    boolean getOpenShopEvaluate();
  }
  /**
   * Protobuf type {@code MSG_PlatformEvaluate.ResEvaluateInfo}
   *
   * <pre>
   *上线或更新时发送评价信息
   * </pre>
   */
  public static final class ResEvaluateInfo extends
      com.google.protobuf.GeneratedMessage
      implements ResEvaluateInfoOrBuilder {
    // Use ResEvaluateInfo.newBuilder() to construct.
    private ResEvaluateInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ResEvaluateInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ResEvaluateInfo defaultInstance;
    public static ResEvaluateInfo getDefaultInstance() {
      return defaultInstance;
    }

    public ResEvaluateInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ResEvaluateInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              like_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              share_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              evaluate_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              openLike_ = input.readBool();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              openShare_ = input.readBool();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              everyDayShare_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              openEveryDayShare_ = input.readBool();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              shopEvaluate_ = input.readInt32();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              openShopEvaluate_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return game.message.PlatformEvaluateMessage.internal_static_MSG_PlatformEvaluate_ResEvaluateInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return game.message.PlatformEvaluateMessage.internal_static_MSG_PlatformEvaluate_ResEvaluateInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              game.message.PlatformEvaluateMessage.ResEvaluateInfo.class, game.message.PlatformEvaluateMessage.ResEvaluateInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<ResEvaluateInfo> PARSER =
        new com.google.protobuf.AbstractParser<ResEvaluateInfo>() {
      public ResEvaluateInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResEvaluateInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ResEvaluateInfo> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code MSG_PlatformEvaluate.ResEvaluateInfo.MsgID}
     */
    public enum MsgID
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>eMsgID = 146101;</code>
       */
      eMsgID(0, 146101),
      ;

      /**
       * <code>eMsgID = 146101;</code>
       */
      public static final int eMsgID_VALUE = 146101;


      public final int getNumber() { return value; }

      public static MsgID valueOf(int value) {
        switch (value) {
          case 146101: return eMsgID;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MsgID>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<MsgID>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MsgID>() {
              public MsgID findValueByNumber(int number) {
                return MsgID.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return game.message.PlatformEvaluateMessage.ResEvaluateInfo.getDescriptor().getEnumTypes().get(0);
      }

      private static final MsgID[] VALUES = values();

      public static MsgID valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private MsgID(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:MSG_PlatformEvaluate.ResEvaluateInfo.MsgID)
    }

    private int bitField0_;
    // optional int32 like = 1;
    public static final int LIKE_FIELD_NUMBER = 1;
    private int like_;
    /**
     * <code>optional int32 like = 1;</code>
     *
     * <pre>
     *0未点赞,1已点赞,2已领取
     * </pre>
     */
    public boolean hasLike() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 like = 1;</code>
     *
     * <pre>
     *0未点赞,1已点赞,2已领取
     * </pre>
     */
    public int getLike() {
      return like_;
    }

    // optional int32 share = 2;
    public static final int SHARE_FIELD_NUMBER = 2;
    private int share_;
    /**
     * <code>optional int32 share = 2;</code>
     *
     * <pre>
     *0未分享,1已分享,2已领取
     * </pre>
     */
    public boolean hasShare() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 share = 2;</code>
     *
     * <pre>
     *0未分享,1已分享,2已领取
     * </pre>
     */
    public int getShare() {
      return share_;
    }

    // optional int32 evaluate = 3;
    public static final int EVALUATE_FIELD_NUMBER = 3;
    private int evaluate_;
    /**
     * <code>optional int32 evaluate = 3;</code>
     *
     * <pre>
     *0未评价,1已评价
     * </pre>
     */
    public boolean hasEvaluate() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 evaluate = 3;</code>
     *
     * <pre>
     *0未评价,1已评价
     * </pre>
     */
    public int getEvaluate() {
      return evaluate_;
    }

    // optional bool openLike = 4;
    public static final int OPENLIKE_FIELD_NUMBER = 4;
    private boolean openLike_;
    /**
     * <code>optional bool openLike = 4;</code>
     *
     * <pre>
     *后台是否开启点赞
     * </pre>
     */
    public boolean hasOpenLike() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional bool openLike = 4;</code>
     *
     * <pre>
     *后台是否开启点赞
     * </pre>
     */
    public boolean getOpenLike() {
      return openLike_;
    }

    // optional bool openShare = 5;
    public static final int OPENSHARE_FIELD_NUMBER = 5;
    private boolean openShare_;
    /**
     * <code>optional bool openShare = 5;</code>
     *
     * <pre>
     *后台是否开启分享
     * </pre>
     */
    public boolean hasOpenShare() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional bool openShare = 5;</code>
     *
     * <pre>
     *后台是否开启分享
     * </pre>
     */
    public boolean getOpenShare() {
      return openShare_;
    }

    // optional int32 everyDayShare = 6;
    public static final int EVERYDAYSHARE_FIELD_NUMBER = 6;
    private int everyDayShare_;
    /**
     * <code>optional int32 everyDayShare = 6;</code>
     *
     * <pre>
     *每日分享  0未分享,1已分享,2已领取
     * </pre>
     */
    public boolean hasEveryDayShare() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional int32 everyDayShare = 6;</code>
     *
     * <pre>
     *每日分享  0未分享,1已分享,2已领取
     * </pre>
     */
    public int getEveryDayShare() {
      return everyDayShare_;
    }

    // optional bool openEveryDayShare = 7;
    public static final int OPENEVERYDAYSHARE_FIELD_NUMBER = 7;
    private boolean openEveryDayShare_;
    /**
     * <code>optional bool openEveryDayShare = 7;</code>
     *
     * <pre>
     *后台是否开启每天分享
     * </pre>
     */
    public boolean hasOpenEveryDayShare() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional bool openEveryDayShare = 7;</code>
     *
     * <pre>
     *后台是否开启每天分享
     * </pre>
     */
    public boolean getOpenEveryDayShare() {
      return openEveryDayShare_;
    }

    // optional int32 shopEvaluate = 8;
    public static final int SHOPEVALUATE_FIELD_NUMBER = 8;
    private int shopEvaluate_;
    /**
     * <code>optional int32 shopEvaluate = 8;</code>
     *
     * <pre>
     *商店评价 0未评价,1已评价
     * </pre>
     */
    public boolean hasShopEvaluate() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional int32 shopEvaluate = 8;</code>
     *
     * <pre>
     *商店评价 0未评价,1已评价
     * </pre>
     */
    public int getShopEvaluate() {
      return shopEvaluate_;
    }

    // optional bool openShopEvaluate = 9;
    public static final int OPENSHOPEVALUATE_FIELD_NUMBER = 9;
    private boolean openShopEvaluate_;
    /**
     * <code>optional bool openShopEvaluate = 9;</code>
     *
     * <pre>
     *后台是否商店评价
     * </pre>
     */
    public boolean hasOpenShopEvaluate() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional bool openShopEvaluate = 9;</code>
     *
     * <pre>
     *后台是否商店评价
     * </pre>
     */
    public boolean getOpenShopEvaluate() {
      return openShopEvaluate_;
    }

    private void initFields() {
      like_ = 0;
      share_ = 0;
      evaluate_ = 0;
      openLike_ = false;
      openShare_ = false;
      everyDayShare_ = 0;
      openEveryDayShare_ = false;
      shopEvaluate_ = 0;
      openShopEvaluate_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, like_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, share_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, evaluate_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBool(4, openLike_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBool(5, openShare_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, everyDayShare_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBool(7, openEveryDayShare_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt32(8, shopEvaluate_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBool(9, openShopEvaluate_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, like_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, share_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, evaluate_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, openLike_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, openShare_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, everyDayShare_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, openEveryDayShare_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, shopEvaluate_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(9, openShopEvaluate_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static game.message.PlatformEvaluateMessage.ResEvaluateInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static game.message.PlatformEvaluateMessage.ResEvaluateInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static game.message.PlatformEvaluateMessage.ResEvaluateInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static game.message.PlatformEvaluateMessage.ResEvaluateInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static game.message.PlatformEvaluateMessage.ResEvaluateInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static game.message.PlatformEvaluateMessage.ResEvaluateInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static game.message.PlatformEvaluateMessage.ResEvaluateInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static game.message.PlatformEvaluateMessage.ResEvaluateInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static game.message.PlatformEvaluateMessage.ResEvaluateInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static game.message.PlatformEvaluateMessage.ResEvaluateInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(game.message.PlatformEvaluateMessage.ResEvaluateInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MSG_PlatformEvaluate.ResEvaluateInfo}
     *
     * <pre>
     *上线或更新时发送评价信息
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements game.message.PlatformEvaluateMessage.ResEvaluateInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return game.message.PlatformEvaluateMessage.internal_static_MSG_PlatformEvaluate_ResEvaluateInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return game.message.PlatformEvaluateMessage.internal_static_MSG_PlatformEvaluate_ResEvaluateInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                game.message.PlatformEvaluateMessage.ResEvaluateInfo.class, game.message.PlatformEvaluateMessage.ResEvaluateInfo.Builder.class);
      }

      // Construct using game.message.PlatformEvaluateMessage.ResEvaluateInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        like_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        share_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        evaluate_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        openLike_ = false;
        bitField0_ = (bitField0_ & ~0x00000008);
        openShare_ = false;
        bitField0_ = (bitField0_ & ~0x00000010);
        everyDayShare_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        openEveryDayShare_ = false;
        bitField0_ = (bitField0_ & ~0x00000040);
        shopEvaluate_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        openShopEvaluate_ = false;
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return game.message.PlatformEvaluateMessage.internal_static_MSG_PlatformEvaluate_ResEvaluateInfo_descriptor;
      }

      public game.message.PlatformEvaluateMessage.ResEvaluateInfo getDefaultInstanceForType() {
        return game.message.PlatformEvaluateMessage.ResEvaluateInfo.getDefaultInstance();
      }

      public game.message.PlatformEvaluateMessage.ResEvaluateInfo build() {
        game.message.PlatformEvaluateMessage.ResEvaluateInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public game.message.PlatformEvaluateMessage.ResEvaluateInfo buildPartial() {
        game.message.PlatformEvaluateMessage.ResEvaluateInfo result = new game.message.PlatformEvaluateMessage.ResEvaluateInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.like_ = like_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.share_ = share_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.evaluate_ = evaluate_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.openLike_ = openLike_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.openShare_ = openShare_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.everyDayShare_ = everyDayShare_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.openEveryDayShare_ = openEveryDayShare_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.shopEvaluate_ = shopEvaluate_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.openShopEvaluate_ = openShopEvaluate_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof game.message.PlatformEvaluateMessage.ResEvaluateInfo) {
          return mergeFrom((game.message.PlatformEvaluateMessage.ResEvaluateInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(game.message.PlatformEvaluateMessage.ResEvaluateInfo other) {
        if (other == game.message.PlatformEvaluateMessage.ResEvaluateInfo.getDefaultInstance()) return this;
        if (other.hasLike()) {
          setLike(other.getLike());
        }
        if (other.hasShare()) {
          setShare(other.getShare());
        }
        if (other.hasEvaluate()) {
          setEvaluate(other.getEvaluate());
        }
        if (other.hasOpenLike()) {
          setOpenLike(other.getOpenLike());
        }
        if (other.hasOpenShare()) {
          setOpenShare(other.getOpenShare());
        }
        if (other.hasEveryDayShare()) {
          setEveryDayShare(other.getEveryDayShare());
        }
        if (other.hasOpenEveryDayShare()) {
          setOpenEveryDayShare(other.getOpenEveryDayShare());
        }
        if (other.hasShopEvaluate()) {
          setShopEvaluate(other.getShopEvaluate());
        }
        if (other.hasOpenShopEvaluate()) {
          setOpenShopEvaluate(other.getOpenShopEvaluate());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        game.message.PlatformEvaluateMessage.ResEvaluateInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (game.message.PlatformEvaluateMessage.ResEvaluateInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 like = 1;
      private int like_ ;
      /**
       * <code>optional int32 like = 1;</code>
       *
       * <pre>
       *0未点赞,1已点赞,2已领取
       * </pre>
       */
      public boolean hasLike() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 like = 1;</code>
       *
       * <pre>
       *0未点赞,1已点赞,2已领取
       * </pre>
       */
      public int getLike() {
        return like_;
      }
      /**
       * <code>optional int32 like = 1;</code>
       *
       * <pre>
       *0未点赞,1已点赞,2已领取
       * </pre>
       */
      public Builder setLike(int value) {
        bitField0_ |= 0x00000001;
        like_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 like = 1;</code>
       *
       * <pre>
       *0未点赞,1已点赞,2已领取
       * </pre>
       */
      public Builder clearLike() {
        bitField0_ = (bitField0_ & ~0x00000001);
        like_ = 0;
        onChanged();
        return this;
      }

      // optional int32 share = 2;
      private int share_ ;
      /**
       * <code>optional int32 share = 2;</code>
       *
       * <pre>
       *0未分享,1已分享,2已领取
       * </pre>
       */
      public boolean hasShare() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 share = 2;</code>
       *
       * <pre>
       *0未分享,1已分享,2已领取
       * </pre>
       */
      public int getShare() {
        return share_;
      }
      /**
       * <code>optional int32 share = 2;</code>
       *
       * <pre>
       *0未分享,1已分享,2已领取
       * </pre>
       */
      public Builder setShare(int value) {
        bitField0_ |= 0x00000002;
        share_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 share = 2;</code>
       *
       * <pre>
       *0未分享,1已分享,2已领取
       * </pre>
       */
      public Builder clearShare() {
        bitField0_ = (bitField0_ & ~0x00000002);
        share_ = 0;
        onChanged();
        return this;
      }

      // optional int32 evaluate = 3;
      private int evaluate_ ;
      /**
       * <code>optional int32 evaluate = 3;</code>
       *
       * <pre>
       *0未评价,1已评价
       * </pre>
       */
      public boolean hasEvaluate() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 evaluate = 3;</code>
       *
       * <pre>
       *0未评价,1已评价
       * </pre>
       */
      public int getEvaluate() {
        return evaluate_;
      }
      /**
       * <code>optional int32 evaluate = 3;</code>
       *
       * <pre>
       *0未评价,1已评价
       * </pre>
       */
      public Builder setEvaluate(int value) {
        bitField0_ |= 0x00000004;
        evaluate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 evaluate = 3;</code>
       *
       * <pre>
       *0未评价,1已评价
       * </pre>
       */
      public Builder clearEvaluate() {
        bitField0_ = (bitField0_ & ~0x00000004);
        evaluate_ = 0;
        onChanged();
        return this;
      }

      // optional bool openLike = 4;
      private boolean openLike_ ;
      /**
       * <code>optional bool openLike = 4;</code>
       *
       * <pre>
       *后台是否开启点赞
       * </pre>
       */
      public boolean hasOpenLike() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional bool openLike = 4;</code>
       *
       * <pre>
       *后台是否开启点赞
       * </pre>
       */
      public boolean getOpenLike() {
        return openLike_;
      }
      /**
       * <code>optional bool openLike = 4;</code>
       *
       * <pre>
       *后台是否开启点赞
       * </pre>
       */
      public Builder setOpenLike(boolean value) {
        bitField0_ |= 0x00000008;
        openLike_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool openLike = 4;</code>
       *
       * <pre>
       *后台是否开启点赞
       * </pre>
       */
      public Builder clearOpenLike() {
        bitField0_ = (bitField0_ & ~0x00000008);
        openLike_ = false;
        onChanged();
        return this;
      }

      // optional bool openShare = 5;
      private boolean openShare_ ;
      /**
       * <code>optional bool openShare = 5;</code>
       *
       * <pre>
       *后台是否开启分享
       * </pre>
       */
      public boolean hasOpenShare() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional bool openShare = 5;</code>
       *
       * <pre>
       *后台是否开启分享
       * </pre>
       */
      public boolean getOpenShare() {
        return openShare_;
      }
      /**
       * <code>optional bool openShare = 5;</code>
       *
       * <pre>
       *后台是否开启分享
       * </pre>
       */
      public Builder setOpenShare(boolean value) {
        bitField0_ |= 0x00000010;
        openShare_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool openShare = 5;</code>
       *
       * <pre>
       *后台是否开启分享
       * </pre>
       */
      public Builder clearOpenShare() {
        bitField0_ = (bitField0_ & ~0x00000010);
        openShare_ = false;
        onChanged();
        return this;
      }

      // optional int32 everyDayShare = 6;
      private int everyDayShare_ ;
      /**
       * <code>optional int32 everyDayShare = 6;</code>
       *
       * <pre>
       *每日分享  0未分享,1已分享,2已领取
       * </pre>
       */
      public boolean hasEveryDayShare() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional int32 everyDayShare = 6;</code>
       *
       * <pre>
       *每日分享  0未分享,1已分享,2已领取
       * </pre>
       */
      public int getEveryDayShare() {
        return everyDayShare_;
      }
      /**
       * <code>optional int32 everyDayShare = 6;</code>
       *
       * <pre>
       *每日分享  0未分享,1已分享,2已领取
       * </pre>
       */
      public Builder setEveryDayShare(int value) {
        bitField0_ |= 0x00000020;
        everyDayShare_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 everyDayShare = 6;</code>
       *
       * <pre>
       *每日分享  0未分享,1已分享,2已领取
       * </pre>
       */
      public Builder clearEveryDayShare() {
        bitField0_ = (bitField0_ & ~0x00000020);
        everyDayShare_ = 0;
        onChanged();
        return this;
      }

      // optional bool openEveryDayShare = 7;
      private boolean openEveryDayShare_ ;
      /**
       * <code>optional bool openEveryDayShare = 7;</code>
       *
       * <pre>
       *后台是否开启每天分享
       * </pre>
       */
      public boolean hasOpenEveryDayShare() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional bool openEveryDayShare = 7;</code>
       *
       * <pre>
       *后台是否开启每天分享
       * </pre>
       */
      public boolean getOpenEveryDayShare() {
        return openEveryDayShare_;
      }
      /**
       * <code>optional bool openEveryDayShare = 7;</code>
       *
       * <pre>
       *后台是否开启每天分享
       * </pre>
       */
      public Builder setOpenEveryDayShare(boolean value) {
        bitField0_ |= 0x00000040;
        openEveryDayShare_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool openEveryDayShare = 7;</code>
       *
       * <pre>
       *后台是否开启每天分享
       * </pre>
       */
      public Builder clearOpenEveryDayShare() {
        bitField0_ = (bitField0_ & ~0x00000040);
        openEveryDayShare_ = false;
        onChanged();
        return this;
      }

      // optional int32 shopEvaluate = 8;
      private int shopEvaluate_ ;
      /**
       * <code>optional int32 shopEvaluate = 8;</code>
       *
       * <pre>
       *商店评价 0未评价,1已评价
       * </pre>
       */
      public boolean hasShopEvaluate() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional int32 shopEvaluate = 8;</code>
       *
       * <pre>
       *商店评价 0未评价,1已评价
       * </pre>
       */
      public int getShopEvaluate() {
        return shopEvaluate_;
      }
      /**
       * <code>optional int32 shopEvaluate = 8;</code>
       *
       * <pre>
       *商店评价 0未评价,1已评价
       * </pre>
       */
      public Builder setShopEvaluate(int value) {
        bitField0_ |= 0x00000080;
        shopEvaluate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 shopEvaluate = 8;</code>
       *
       * <pre>
       *商店评价 0未评价,1已评价
       * </pre>
       */
      public Builder clearShopEvaluate() {
        bitField0_ = (bitField0_ & ~0x00000080);
        shopEvaluate_ = 0;
        onChanged();
        return this;
      }

      // optional bool openShopEvaluate = 9;
      private boolean openShopEvaluate_ ;
      /**
       * <code>optional bool openShopEvaluate = 9;</code>
       *
       * <pre>
       *后台是否商店评价
       * </pre>
       */
      public boolean hasOpenShopEvaluate() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional bool openShopEvaluate = 9;</code>
       *
       * <pre>
       *后台是否商店评价
       * </pre>
       */
      public boolean getOpenShopEvaluate() {
        return openShopEvaluate_;
      }
      /**
       * <code>optional bool openShopEvaluate = 9;</code>
       *
       * <pre>
       *后台是否商店评价
       * </pre>
       */
      public Builder setOpenShopEvaluate(boolean value) {
        bitField0_ |= 0x00000100;
        openShopEvaluate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool openShopEvaluate = 9;</code>
       *
       * <pre>
       *后台是否商店评价
       * </pre>
       */
      public Builder clearOpenShopEvaluate() {
        bitField0_ = (bitField0_ & ~0x00000100);
        openShopEvaluate_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:MSG_PlatformEvaluate.ResEvaluateInfo)
    }

    static {
      defaultInstance = new ResEvaluateInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:MSG_PlatformEvaluate.ResEvaluateInfo)
  }

  public interface ResEvaluateResultOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 like = 1;
    /**
     * <code>optional int32 like = 1;</code>
     *
     * <pre>
     *1已点赞（成功）,2已领取
     * </pre>
     */
    boolean hasLike();
    /**
     * <code>optional int32 like = 1;</code>
     *
     * <pre>
     *1已点赞（成功）,2已领取
     * </pre>
     */
    int getLike();

    // optional int32 share = 2;
    /**
     * <code>optional int32 share = 2;</code>
     *
     * <pre>
     *1已分享（成功）,2已领取
     * </pre>
     */
    boolean hasShare();
    /**
     * <code>optional int32 share = 2;</code>
     *
     * <pre>
     *1已分享（成功）,2已领取
     * </pre>
     */
    int getShare();

    // optional int32 evaluate = 3;
    /**
     * <code>optional int32 evaluate = 3;</code>
     *
     * <pre>
     *1已评价（成功）
     * </pre>
     */
    boolean hasEvaluate();
    /**
     * <code>optional int32 evaluate = 3;</code>
     *
     * <pre>
     *1已评价（成功）
     * </pre>
     */
    int getEvaluate();

    // optional int32 everyDayShare = 4;
    /**
     * <code>optional int32 everyDayShare = 4;</code>
     *
     * <pre>
     *每日分享  0未分享,1已分享,2已领取
     * </pre>
     */
    boolean hasEveryDayShare();
    /**
     * <code>optional int32 everyDayShare = 4;</code>
     *
     * <pre>
     *每日分享  0未分享,1已分享,2已领取
     * </pre>
     */
    int getEveryDayShare();

    // optional int32 shopEvaluate = 5;
    /**
     * <code>optional int32 shopEvaluate = 5;</code>
     *
     * <pre>
     *商店评价 0未评价,1已评价
     * </pre>
     */
    boolean hasShopEvaluate();
    /**
     * <code>optional int32 shopEvaluate = 5;</code>
     *
     * <pre>
     *商店评价 0未评价,1已评价
     * </pre>
     */
    int getShopEvaluate();
  }
  /**
   * Protobuf type {@code MSG_PlatformEvaluate.ResEvaluateResult}
   *
   * <pre>
   *返回评价结果
   * </pre>
   */
  public static final class ResEvaluateResult extends
      com.google.protobuf.GeneratedMessage
      implements ResEvaluateResultOrBuilder {
    // Use ResEvaluateResult.newBuilder() to construct.
    private ResEvaluateResult(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ResEvaluateResult(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ResEvaluateResult defaultInstance;
    public static ResEvaluateResult getDefaultInstance() {
      return defaultInstance;
    }

    public ResEvaluateResult getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ResEvaluateResult(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              like_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              share_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              evaluate_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              everyDayShare_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              shopEvaluate_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return game.message.PlatformEvaluateMessage.internal_static_MSG_PlatformEvaluate_ResEvaluateResult_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return game.message.PlatformEvaluateMessage.internal_static_MSG_PlatformEvaluate_ResEvaluateResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              game.message.PlatformEvaluateMessage.ResEvaluateResult.class, game.message.PlatformEvaluateMessage.ResEvaluateResult.Builder.class);
    }

    public static com.google.protobuf.Parser<ResEvaluateResult> PARSER =
        new com.google.protobuf.AbstractParser<ResEvaluateResult>() {
      public ResEvaluateResult parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResEvaluateResult(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ResEvaluateResult> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code MSG_PlatformEvaluate.ResEvaluateResult.MsgID}
     */
    public enum MsgID
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>eMsgID = 146102;</code>
       */
      eMsgID(0, 146102),
      ;

      /**
       * <code>eMsgID = 146102;</code>
       */
      public static final int eMsgID_VALUE = 146102;


      public final int getNumber() { return value; }

      public static MsgID valueOf(int value) {
        switch (value) {
          case 146102: return eMsgID;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MsgID>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<MsgID>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MsgID>() {
              public MsgID findValueByNumber(int number) {
                return MsgID.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return game.message.PlatformEvaluateMessage.ResEvaluateResult.getDescriptor().getEnumTypes().get(0);
      }

      private static final MsgID[] VALUES = values();

      public static MsgID valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private MsgID(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:MSG_PlatformEvaluate.ResEvaluateResult.MsgID)
    }

    private int bitField0_;
    // optional int32 like = 1;
    public static final int LIKE_FIELD_NUMBER = 1;
    private int like_;
    /**
     * <code>optional int32 like = 1;</code>
     *
     * <pre>
     *1已点赞（成功）,2已领取
     * </pre>
     */
    public boolean hasLike() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 like = 1;</code>
     *
     * <pre>
     *1已点赞（成功）,2已领取
     * </pre>
     */
    public int getLike() {
      return like_;
    }

    // optional int32 share = 2;
    public static final int SHARE_FIELD_NUMBER = 2;
    private int share_;
    /**
     * <code>optional int32 share = 2;</code>
     *
     * <pre>
     *1已分享（成功）,2已领取
     * </pre>
     */
    public boolean hasShare() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 share = 2;</code>
     *
     * <pre>
     *1已分享（成功）,2已领取
     * </pre>
     */
    public int getShare() {
      return share_;
    }

    // optional int32 evaluate = 3;
    public static final int EVALUATE_FIELD_NUMBER = 3;
    private int evaluate_;
    /**
     * <code>optional int32 evaluate = 3;</code>
     *
     * <pre>
     *1已评价（成功）
     * </pre>
     */
    public boolean hasEvaluate() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 evaluate = 3;</code>
     *
     * <pre>
     *1已评价（成功）
     * </pre>
     */
    public int getEvaluate() {
      return evaluate_;
    }

    // optional int32 everyDayShare = 4;
    public static final int EVERYDAYSHARE_FIELD_NUMBER = 4;
    private int everyDayShare_;
    /**
     * <code>optional int32 everyDayShare = 4;</code>
     *
     * <pre>
     *每日分享  0未分享,1已分享,2已领取
     * </pre>
     */
    public boolean hasEveryDayShare() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 everyDayShare = 4;</code>
     *
     * <pre>
     *每日分享  0未分享,1已分享,2已领取
     * </pre>
     */
    public int getEveryDayShare() {
      return everyDayShare_;
    }

    // optional int32 shopEvaluate = 5;
    public static final int SHOPEVALUATE_FIELD_NUMBER = 5;
    private int shopEvaluate_;
    /**
     * <code>optional int32 shopEvaluate = 5;</code>
     *
     * <pre>
     *商店评价 0未评价,1已评价
     * </pre>
     */
    public boolean hasShopEvaluate() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 shopEvaluate = 5;</code>
     *
     * <pre>
     *商店评价 0未评价,1已评价
     * </pre>
     */
    public int getShopEvaluate() {
      return shopEvaluate_;
    }

    private void initFields() {
      like_ = 0;
      share_ = 0;
      evaluate_ = 0;
      everyDayShare_ = 0;
      shopEvaluate_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, like_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, share_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, evaluate_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, everyDayShare_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, shopEvaluate_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, like_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, share_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, evaluate_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, everyDayShare_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, shopEvaluate_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static game.message.PlatformEvaluateMessage.ResEvaluateResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static game.message.PlatformEvaluateMessage.ResEvaluateResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static game.message.PlatformEvaluateMessage.ResEvaluateResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static game.message.PlatformEvaluateMessage.ResEvaluateResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static game.message.PlatformEvaluateMessage.ResEvaluateResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static game.message.PlatformEvaluateMessage.ResEvaluateResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static game.message.PlatformEvaluateMessage.ResEvaluateResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static game.message.PlatformEvaluateMessage.ResEvaluateResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static game.message.PlatformEvaluateMessage.ResEvaluateResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static game.message.PlatformEvaluateMessage.ResEvaluateResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(game.message.PlatformEvaluateMessage.ResEvaluateResult prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MSG_PlatformEvaluate.ResEvaluateResult}
     *
     * <pre>
     *返回评价结果
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements game.message.PlatformEvaluateMessage.ResEvaluateResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return game.message.PlatformEvaluateMessage.internal_static_MSG_PlatformEvaluate_ResEvaluateResult_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return game.message.PlatformEvaluateMessage.internal_static_MSG_PlatformEvaluate_ResEvaluateResult_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                game.message.PlatformEvaluateMessage.ResEvaluateResult.class, game.message.PlatformEvaluateMessage.ResEvaluateResult.Builder.class);
      }

      // Construct using game.message.PlatformEvaluateMessage.ResEvaluateResult.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        like_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        share_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        evaluate_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        everyDayShare_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        shopEvaluate_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return game.message.PlatformEvaluateMessage.internal_static_MSG_PlatformEvaluate_ResEvaluateResult_descriptor;
      }

      public game.message.PlatformEvaluateMessage.ResEvaluateResult getDefaultInstanceForType() {
        return game.message.PlatformEvaluateMessage.ResEvaluateResult.getDefaultInstance();
      }

      public game.message.PlatformEvaluateMessage.ResEvaluateResult build() {
        game.message.PlatformEvaluateMessage.ResEvaluateResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public game.message.PlatformEvaluateMessage.ResEvaluateResult buildPartial() {
        game.message.PlatformEvaluateMessage.ResEvaluateResult result = new game.message.PlatformEvaluateMessage.ResEvaluateResult(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.like_ = like_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.share_ = share_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.evaluate_ = evaluate_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.everyDayShare_ = everyDayShare_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.shopEvaluate_ = shopEvaluate_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof game.message.PlatformEvaluateMessage.ResEvaluateResult) {
          return mergeFrom((game.message.PlatformEvaluateMessage.ResEvaluateResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(game.message.PlatformEvaluateMessage.ResEvaluateResult other) {
        if (other == game.message.PlatformEvaluateMessage.ResEvaluateResult.getDefaultInstance()) return this;
        if (other.hasLike()) {
          setLike(other.getLike());
        }
        if (other.hasShare()) {
          setShare(other.getShare());
        }
        if (other.hasEvaluate()) {
          setEvaluate(other.getEvaluate());
        }
        if (other.hasEveryDayShare()) {
          setEveryDayShare(other.getEveryDayShare());
        }
        if (other.hasShopEvaluate()) {
          setShopEvaluate(other.getShopEvaluate());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        game.message.PlatformEvaluateMessage.ResEvaluateResult parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (game.message.PlatformEvaluateMessage.ResEvaluateResult) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 like = 1;
      private int like_ ;
      /**
       * <code>optional int32 like = 1;</code>
       *
       * <pre>
       *1已点赞（成功）,2已领取
       * </pre>
       */
      public boolean hasLike() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 like = 1;</code>
       *
       * <pre>
       *1已点赞（成功）,2已领取
       * </pre>
       */
      public int getLike() {
        return like_;
      }
      /**
       * <code>optional int32 like = 1;</code>
       *
       * <pre>
       *1已点赞（成功）,2已领取
       * </pre>
       */
      public Builder setLike(int value) {
        bitField0_ |= 0x00000001;
        like_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 like = 1;</code>
       *
       * <pre>
       *1已点赞（成功）,2已领取
       * </pre>
       */
      public Builder clearLike() {
        bitField0_ = (bitField0_ & ~0x00000001);
        like_ = 0;
        onChanged();
        return this;
      }

      // optional int32 share = 2;
      private int share_ ;
      /**
       * <code>optional int32 share = 2;</code>
       *
       * <pre>
       *1已分享（成功）,2已领取
       * </pre>
       */
      public boolean hasShare() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 share = 2;</code>
       *
       * <pre>
       *1已分享（成功）,2已领取
       * </pre>
       */
      public int getShare() {
        return share_;
      }
      /**
       * <code>optional int32 share = 2;</code>
       *
       * <pre>
       *1已分享（成功）,2已领取
       * </pre>
       */
      public Builder setShare(int value) {
        bitField0_ |= 0x00000002;
        share_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 share = 2;</code>
       *
       * <pre>
       *1已分享（成功）,2已领取
       * </pre>
       */
      public Builder clearShare() {
        bitField0_ = (bitField0_ & ~0x00000002);
        share_ = 0;
        onChanged();
        return this;
      }

      // optional int32 evaluate = 3;
      private int evaluate_ ;
      /**
       * <code>optional int32 evaluate = 3;</code>
       *
       * <pre>
       *1已评价（成功）
       * </pre>
       */
      public boolean hasEvaluate() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 evaluate = 3;</code>
       *
       * <pre>
       *1已评价（成功）
       * </pre>
       */
      public int getEvaluate() {
        return evaluate_;
      }
      /**
       * <code>optional int32 evaluate = 3;</code>
       *
       * <pre>
       *1已评价（成功）
       * </pre>
       */
      public Builder setEvaluate(int value) {
        bitField0_ |= 0x00000004;
        evaluate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 evaluate = 3;</code>
       *
       * <pre>
       *1已评价（成功）
       * </pre>
       */
      public Builder clearEvaluate() {
        bitField0_ = (bitField0_ & ~0x00000004);
        evaluate_ = 0;
        onChanged();
        return this;
      }

      // optional int32 everyDayShare = 4;
      private int everyDayShare_ ;
      /**
       * <code>optional int32 everyDayShare = 4;</code>
       *
       * <pre>
       *每日分享  0未分享,1已分享,2已领取
       * </pre>
       */
      public boolean hasEveryDayShare() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 everyDayShare = 4;</code>
       *
       * <pre>
       *每日分享  0未分享,1已分享,2已领取
       * </pre>
       */
      public int getEveryDayShare() {
        return everyDayShare_;
      }
      /**
       * <code>optional int32 everyDayShare = 4;</code>
       *
       * <pre>
       *每日分享  0未分享,1已分享,2已领取
       * </pre>
       */
      public Builder setEveryDayShare(int value) {
        bitField0_ |= 0x00000008;
        everyDayShare_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 everyDayShare = 4;</code>
       *
       * <pre>
       *每日分享  0未分享,1已分享,2已领取
       * </pre>
       */
      public Builder clearEveryDayShare() {
        bitField0_ = (bitField0_ & ~0x00000008);
        everyDayShare_ = 0;
        onChanged();
        return this;
      }

      // optional int32 shopEvaluate = 5;
      private int shopEvaluate_ ;
      /**
       * <code>optional int32 shopEvaluate = 5;</code>
       *
       * <pre>
       *商店评价 0未评价,1已评价
       * </pre>
       */
      public boolean hasShopEvaluate() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 shopEvaluate = 5;</code>
       *
       * <pre>
       *商店评价 0未评价,1已评价
       * </pre>
       */
      public int getShopEvaluate() {
        return shopEvaluate_;
      }
      /**
       * <code>optional int32 shopEvaluate = 5;</code>
       *
       * <pre>
       *商店评价 0未评价,1已评价
       * </pre>
       */
      public Builder setShopEvaluate(int value) {
        bitField0_ |= 0x00000010;
        shopEvaluate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 shopEvaluate = 5;</code>
       *
       * <pre>
       *商店评价 0未评价,1已评价
       * </pre>
       */
      public Builder clearShopEvaluate() {
        bitField0_ = (bitField0_ & ~0x00000010);
        shopEvaluate_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:MSG_PlatformEvaluate.ResEvaluateResult)
    }

    static {
      defaultInstance = new ResEvaluateResult(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:MSG_PlatformEvaluate.ResEvaluateResult)
  }

  public interface ReqEvaluateOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 type = 1;
    /**
     * <code>required int32 type = 1;</code>
     *
     * <pre>
     *评价类型1点赞,2分享3评价 4每日分享 5,商店评价
     * </pre>
     */
    boolean hasType();
    /**
     * <code>required int32 type = 1;</code>
     *
     * <pre>
     *评价类型1点赞,2分享3评价 4每日分享 5,商店评价
     * </pre>
     */
    int getType();

    // required int32 actType = 2;
    /**
     * <code>required int32 actType = 2;</code>
     *
     * <pre>
     *操作类型1完成操作2领取奖励
     * </pre>
     */
    boolean hasActType();
    /**
     * <code>required int32 actType = 2;</code>
     *
     * <pre>
     *操作类型1完成操作2领取奖励
     * </pre>
     */
    int getActType();
  }
  /**
   * Protobuf type {@code MSG_PlatformEvaluate.ReqEvaluate}
   *
   * <pre>
   *请求评价
   * </pre>
   */
  public static final class ReqEvaluate extends
      com.google.protobuf.GeneratedMessage
      implements ReqEvaluateOrBuilder {
    // Use ReqEvaluate.newBuilder() to construct.
    private ReqEvaluate(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ReqEvaluate(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ReqEvaluate defaultInstance;
    public static ReqEvaluate getDefaultInstance() {
      return defaultInstance;
    }

    public ReqEvaluate getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ReqEvaluate(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              type_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              actType_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return game.message.PlatformEvaluateMessage.internal_static_MSG_PlatformEvaluate_ReqEvaluate_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return game.message.PlatformEvaluateMessage.internal_static_MSG_PlatformEvaluate_ReqEvaluate_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              game.message.PlatformEvaluateMessage.ReqEvaluate.class, game.message.PlatformEvaluateMessage.ReqEvaluate.Builder.class);
    }

    public static com.google.protobuf.Parser<ReqEvaluate> PARSER =
        new com.google.protobuf.AbstractParser<ReqEvaluate>() {
      public ReqEvaluate parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReqEvaluate(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ReqEvaluate> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code MSG_PlatformEvaluate.ReqEvaluate.MsgID}
     */
    public enum MsgID
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>eMsgID = 146201;</code>
       */
      eMsgID(0, 146201),
      ;

      /**
       * <code>eMsgID = 146201;</code>
       */
      public static final int eMsgID_VALUE = 146201;


      public final int getNumber() { return value; }

      public static MsgID valueOf(int value) {
        switch (value) {
          case 146201: return eMsgID;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MsgID>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<MsgID>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MsgID>() {
              public MsgID findValueByNumber(int number) {
                return MsgID.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return game.message.PlatformEvaluateMessage.ReqEvaluate.getDescriptor().getEnumTypes().get(0);
      }

      private static final MsgID[] VALUES = values();

      public static MsgID valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private MsgID(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:MSG_PlatformEvaluate.ReqEvaluate.MsgID)
    }

    private int bitField0_;
    // required int32 type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>required int32 type = 1;</code>
     *
     * <pre>
     *评价类型1点赞,2分享3评价 4每日分享 5,商店评价
     * </pre>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 type = 1;</code>
     *
     * <pre>
     *评价类型1点赞,2分享3评价 4每日分享 5,商店评价
     * </pre>
     */
    public int getType() {
      return type_;
    }

    // required int32 actType = 2;
    public static final int ACTTYPE_FIELD_NUMBER = 2;
    private int actType_;
    /**
     * <code>required int32 actType = 2;</code>
     *
     * <pre>
     *操作类型1完成操作2领取奖励
     * </pre>
     */
    public boolean hasActType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 actType = 2;</code>
     *
     * <pre>
     *操作类型1完成操作2领取奖励
     * </pre>
     */
    public int getActType() {
      return actType_;
    }

    private void initFields() {
      type_ = 0;
      actType_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasActType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, type_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, actType_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, type_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, actType_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static game.message.PlatformEvaluateMessage.ReqEvaluate parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static game.message.PlatformEvaluateMessage.ReqEvaluate parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static game.message.PlatformEvaluateMessage.ReqEvaluate parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static game.message.PlatformEvaluateMessage.ReqEvaluate parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static game.message.PlatformEvaluateMessage.ReqEvaluate parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static game.message.PlatformEvaluateMessage.ReqEvaluate parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static game.message.PlatformEvaluateMessage.ReqEvaluate parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static game.message.PlatformEvaluateMessage.ReqEvaluate parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static game.message.PlatformEvaluateMessage.ReqEvaluate parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static game.message.PlatformEvaluateMessage.ReqEvaluate parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(game.message.PlatformEvaluateMessage.ReqEvaluate prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MSG_PlatformEvaluate.ReqEvaluate}
     *
     * <pre>
     *请求评价
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements game.message.PlatformEvaluateMessage.ReqEvaluateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return game.message.PlatformEvaluateMessage.internal_static_MSG_PlatformEvaluate_ReqEvaluate_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return game.message.PlatformEvaluateMessage.internal_static_MSG_PlatformEvaluate_ReqEvaluate_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                game.message.PlatformEvaluateMessage.ReqEvaluate.class, game.message.PlatformEvaluateMessage.ReqEvaluate.Builder.class);
      }

      // Construct using game.message.PlatformEvaluateMessage.ReqEvaluate.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        actType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return game.message.PlatformEvaluateMessage.internal_static_MSG_PlatformEvaluate_ReqEvaluate_descriptor;
      }

      public game.message.PlatformEvaluateMessage.ReqEvaluate getDefaultInstanceForType() {
        return game.message.PlatformEvaluateMessage.ReqEvaluate.getDefaultInstance();
      }

      public game.message.PlatformEvaluateMessage.ReqEvaluate build() {
        game.message.PlatformEvaluateMessage.ReqEvaluate result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public game.message.PlatformEvaluateMessage.ReqEvaluate buildPartial() {
        game.message.PlatformEvaluateMessage.ReqEvaluate result = new game.message.PlatformEvaluateMessage.ReqEvaluate(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.actType_ = actType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof game.message.PlatformEvaluateMessage.ReqEvaluate) {
          return mergeFrom((game.message.PlatformEvaluateMessage.ReqEvaluate)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(game.message.PlatformEvaluateMessage.ReqEvaluate other) {
        if (other == game.message.PlatformEvaluateMessage.ReqEvaluate.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasActType()) {
          setActType(other.getActType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (!hasActType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        game.message.PlatformEvaluateMessage.ReqEvaluate parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (game.message.PlatformEvaluateMessage.ReqEvaluate) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 type = 1;
      private int type_ ;
      /**
       * <code>required int32 type = 1;</code>
       *
       * <pre>
       *评价类型1点赞,2分享3评价 4每日分享 5,商店评价
       * </pre>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 type = 1;</code>
       *
       * <pre>
       *评价类型1点赞,2分享3评价 4每日分享 5,商店评价
       * </pre>
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>required int32 type = 1;</code>
       *
       * <pre>
       *评价类型1点赞,2分享3评价 4每日分享 5,商店评价
       * </pre>
       */
      public Builder setType(int value) {
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 type = 1;</code>
       *
       * <pre>
       *评价类型1点赞,2分享3评价 4每日分享 5,商店评价
       * </pre>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 0;
        onChanged();
        return this;
      }

      // required int32 actType = 2;
      private int actType_ ;
      /**
       * <code>required int32 actType = 2;</code>
       *
       * <pre>
       *操作类型1完成操作2领取奖励
       * </pre>
       */
      public boolean hasActType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 actType = 2;</code>
       *
       * <pre>
       *操作类型1完成操作2领取奖励
       * </pre>
       */
      public int getActType() {
        return actType_;
      }
      /**
       * <code>required int32 actType = 2;</code>
       *
       * <pre>
       *操作类型1完成操作2领取奖励
       * </pre>
       */
      public Builder setActType(int value) {
        bitField0_ |= 0x00000002;
        actType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 actType = 2;</code>
       *
       * <pre>
       *操作类型1完成操作2领取奖励
       * </pre>
       */
      public Builder clearActType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        actType_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:MSG_PlatformEvaluate.ReqEvaluate)
    }

    static {
      defaultInstance = new ReqEvaluate(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:MSG_PlatformEvaluate.ReqEvaluate)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_MSG_PlatformEvaluate_ResEvaluateInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MSG_PlatformEvaluate_ResEvaluateInfo_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_MSG_PlatformEvaluate_ResEvaluateResult_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MSG_PlatformEvaluate_ResEvaluateResult_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_MSG_PlatformEvaluate_ReqEvaluate_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MSG_PlatformEvaluate_ReqEvaluate_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026platformevaluate.proto\022\024MSG_PlatformEv" +
      "aluate\"\336\001\n\017ResEvaluateInfo\022\014\n\004like\030\001 \001(\005" +
      "\022\r\n\005share\030\002 \001(\005\022\020\n\010evaluate\030\003 \001(\005\022\020\n\010ope" +
      "nLike\030\004 \001(\010\022\021\n\topenShare\030\005 \001(\010\022\025\n\reveryD" +
      "ayShare\030\006 \001(\005\022\031\n\021openEveryDayShare\030\007 \001(\010" +
      "\022\024\n\014shopEvaluate\030\010 \001(\005\022\030\n\020openShopEvalua" +
      "te\030\t \001(\010\"\025\n\005MsgID\022\014\n\006eMsgID\020\265\365\010\"\206\001\n\021ResE" +
      "valuateResult\022\014\n\004like\030\001 \001(\005\022\r\n\005share\030\002 \001" +
      "(\005\022\020\n\010evaluate\030\003 \001(\005\022\025\n\reveryDayShare\030\004 " +
      "\001(\005\022\024\n\014shopEvaluate\030\005 \001(\005\"\025\n\005MsgID\022\014\n\006eM",
      "sgID\020\266\365\010\"C\n\013ReqEvaluate\022\014\n\004type\030\001 \002(\005\022\017\n" +
      "\007actType\030\002 \002(\005\"\025\n\005MsgID\022\014\n\006eMsgID\020\231\366\010B\'\n" +
      "\014game.messageB\027PlatformEvaluateMessage"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_MSG_PlatformEvaluate_ResEvaluateInfo_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_MSG_PlatformEvaluate_ResEvaluateInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_MSG_PlatformEvaluate_ResEvaluateInfo_descriptor,
              new java.lang.String[] { "Like", "Share", "Evaluate", "OpenLike", "OpenShare", "EveryDayShare", "OpenEveryDayShare", "ShopEvaluate", "OpenShopEvaluate", });
          internal_static_MSG_PlatformEvaluate_ResEvaluateResult_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_MSG_PlatformEvaluate_ResEvaluateResult_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_MSG_PlatformEvaluate_ResEvaluateResult_descriptor,
              new java.lang.String[] { "Like", "Share", "Evaluate", "EveryDayShare", "ShopEvaluate", });
          internal_static_MSG_PlatformEvaluate_ReqEvaluate_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_MSG_PlatformEvaluate_ReqEvaluate_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_MSG_PlatformEvaluate_ReqEvaluate_descriptor,
              new java.lang.String[] { "Type", "ActType", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
