// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: recycle.proto

package game.message;

public final class RecycleMessage {
  private RecycleMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ReqRecycleOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated uint64 itemId = 1;
    /**
     * <code>repeated uint64 itemId = 1;</code>
     *
     * <pre>
     *道具实例ID
     * </pre>
     */
    java.util.List<java.lang.Long> getItemIdList();
    /**
     * <code>repeated uint64 itemId = 1;</code>
     *
     * <pre>
     *道具实例ID
     * </pre>
     */
    int getItemIdCount();
    /**
     * <code>repeated uint64 itemId = 1;</code>
     *
     * <pre>
     *道具实例ID
     * </pre>
     */
    long getItemId(int index);
  }
  /**
   * Protobuf type {@code MSG_Recycle.ReqRecycle}
   *
   * <pre>
   *Client -&gt; Server 回收物品
   * </pre>
   */
  public static final class ReqRecycle extends
      com.google.protobuf.GeneratedMessage
      implements ReqRecycleOrBuilder {
    // Use ReqRecycle.newBuilder() to construct.
    private ReqRecycle(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ReqRecycle(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ReqRecycle defaultInstance;
    public static ReqRecycle getDefaultInstance() {
      return defaultInstance;
    }

    public ReqRecycle getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ReqRecycle(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                itemId_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000001;
              }
              itemId_.add(input.readUInt64());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                itemId_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                itemId_.add(input.readUInt64());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          itemId_ = java.util.Collections.unmodifiableList(itemId_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return game.message.RecycleMessage.internal_static_MSG_Recycle_ReqRecycle_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return game.message.RecycleMessage.internal_static_MSG_Recycle_ReqRecycle_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              game.message.RecycleMessage.ReqRecycle.class, game.message.RecycleMessage.ReqRecycle.Builder.class);
    }

    public static com.google.protobuf.Parser<ReqRecycle> PARSER =
        new com.google.protobuf.AbstractParser<ReqRecycle>() {
      public ReqRecycle parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReqRecycle(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ReqRecycle> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code MSG_Recycle.ReqRecycle.MsgID}
     */
    public enum MsgID
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>eMsgID = 519201;</code>
       */
      eMsgID(0, 519201),
      ;

      /**
       * <code>eMsgID = 519201;</code>
       */
      public static final int eMsgID_VALUE = 519201;


      public final int getNumber() { return value; }

      public static MsgID valueOf(int value) {
        switch (value) {
          case 519201: return eMsgID;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MsgID>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<MsgID>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MsgID>() {
              public MsgID findValueByNumber(int number) {
                return MsgID.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return game.message.RecycleMessage.ReqRecycle.getDescriptor().getEnumTypes().get(0);
      }

      private static final MsgID[] VALUES = values();

      public static MsgID valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private MsgID(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:MSG_Recycle.ReqRecycle.MsgID)
    }

    // repeated uint64 itemId = 1;
    public static final int ITEMID_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Long> itemId_;
    /**
     * <code>repeated uint64 itemId = 1;</code>
     *
     * <pre>
     *道具实例ID
     * </pre>
     */
    public java.util.List<java.lang.Long>
        getItemIdList() {
      return itemId_;
    }
    /**
     * <code>repeated uint64 itemId = 1;</code>
     *
     * <pre>
     *道具实例ID
     * </pre>
     */
    public int getItemIdCount() {
      return itemId_.size();
    }
    /**
     * <code>repeated uint64 itemId = 1;</code>
     *
     * <pre>
     *道具实例ID
     * </pre>
     */
    public long getItemId(int index) {
      return itemId_.get(index);
    }

    private void initFields() {
      itemId_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < itemId_.size(); i++) {
        output.writeUInt64(1, itemId_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < itemId_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeUInt64SizeNoTag(itemId_.get(i));
        }
        size += dataSize;
        size += 1 * getItemIdList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static game.message.RecycleMessage.ReqRecycle parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static game.message.RecycleMessage.ReqRecycle parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static game.message.RecycleMessage.ReqRecycle parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static game.message.RecycleMessage.ReqRecycle parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static game.message.RecycleMessage.ReqRecycle parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static game.message.RecycleMessage.ReqRecycle parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static game.message.RecycleMessage.ReqRecycle parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static game.message.RecycleMessage.ReqRecycle parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static game.message.RecycleMessage.ReqRecycle parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static game.message.RecycleMessage.ReqRecycle parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(game.message.RecycleMessage.ReqRecycle prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MSG_Recycle.ReqRecycle}
     *
     * <pre>
     *Client -&gt; Server 回收物品
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements game.message.RecycleMessage.ReqRecycleOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return game.message.RecycleMessage.internal_static_MSG_Recycle_ReqRecycle_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return game.message.RecycleMessage.internal_static_MSG_Recycle_ReqRecycle_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                game.message.RecycleMessage.ReqRecycle.class, game.message.RecycleMessage.ReqRecycle.Builder.class);
      }

      // Construct using game.message.RecycleMessage.ReqRecycle.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        itemId_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return game.message.RecycleMessage.internal_static_MSG_Recycle_ReqRecycle_descriptor;
      }

      public game.message.RecycleMessage.ReqRecycle getDefaultInstanceForType() {
        return game.message.RecycleMessage.ReqRecycle.getDefaultInstance();
      }

      public game.message.RecycleMessage.ReqRecycle build() {
        game.message.RecycleMessage.ReqRecycle result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public game.message.RecycleMessage.ReqRecycle buildPartial() {
        game.message.RecycleMessage.ReqRecycle result = new game.message.RecycleMessage.ReqRecycle(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          itemId_ = java.util.Collections.unmodifiableList(itemId_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.itemId_ = itemId_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof game.message.RecycleMessage.ReqRecycle) {
          return mergeFrom((game.message.RecycleMessage.ReqRecycle)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(game.message.RecycleMessage.ReqRecycle other) {
        if (other == game.message.RecycleMessage.ReqRecycle.getDefaultInstance()) return this;
        if (!other.itemId_.isEmpty()) {
          if (itemId_.isEmpty()) {
            itemId_ = other.itemId_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureItemIdIsMutable();
            itemId_.addAll(other.itemId_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        game.message.RecycleMessage.ReqRecycle parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (game.message.RecycleMessage.ReqRecycle) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated uint64 itemId = 1;
      private java.util.List<java.lang.Long> itemId_ = java.util.Collections.emptyList();
      private void ensureItemIdIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          itemId_ = new java.util.ArrayList<java.lang.Long>(itemId_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated uint64 itemId = 1;</code>
       *
       * <pre>
       *道具实例ID
       * </pre>
       */
      public java.util.List<java.lang.Long>
          getItemIdList() {
        return java.util.Collections.unmodifiableList(itemId_);
      }
      /**
       * <code>repeated uint64 itemId = 1;</code>
       *
       * <pre>
       *道具实例ID
       * </pre>
       */
      public int getItemIdCount() {
        return itemId_.size();
      }
      /**
       * <code>repeated uint64 itemId = 1;</code>
       *
       * <pre>
       *道具实例ID
       * </pre>
       */
      public long getItemId(int index) {
        return itemId_.get(index);
      }
      /**
       * <code>repeated uint64 itemId = 1;</code>
       *
       * <pre>
       *道具实例ID
       * </pre>
       */
      public Builder setItemId(
          int index, long value) {
        ensureItemIdIsMutable();
        itemId_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint64 itemId = 1;</code>
       *
       * <pre>
       *道具实例ID
       * </pre>
       */
      public Builder addItemId(long value) {
        ensureItemIdIsMutable();
        itemId_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint64 itemId = 1;</code>
       *
       * <pre>
       *道具实例ID
       * </pre>
       */
      public Builder addAllItemId(
          java.lang.Iterable<? extends java.lang.Long> values) {
        ensureItemIdIsMutable();
        super.addAll(values, itemId_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint64 itemId = 1;</code>
       *
       * <pre>
       *道具实例ID
       * </pre>
       */
      public Builder clearItemId() {
        itemId_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:MSG_Recycle.ReqRecycle)
    }

    static {
      defaultInstance = new ReqRecycle(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:MSG_Recycle.ReqRecycle)
  }

  public interface ReqSetAutoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required bool isOpen = 1;
    /**
     * <code>required bool isOpen = 1;</code>
     *
     * <pre>
     *是否开启自动熔炼，true开启false关闭
     * </pre>
     */
    boolean hasIsOpen();
    /**
     * <code>required bool isOpen = 1;</code>
     *
     * <pre>
     *是否开启自动熔炼，true开启false关闭
     * </pre>
     */
    boolean getIsOpen();
  }
  /**
   * Protobuf type {@code MSG_Recycle.ReqSetAuto}
   *
   * <pre>
   *Client -&gt; Server 请求设置自动熔炼垃圾装备
   * </pre>
   */
  public static final class ReqSetAuto extends
      com.google.protobuf.GeneratedMessage
      implements ReqSetAutoOrBuilder {
    // Use ReqSetAuto.newBuilder() to construct.
    private ReqSetAuto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ReqSetAuto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ReqSetAuto defaultInstance;
    public static ReqSetAuto getDefaultInstance() {
      return defaultInstance;
    }

    public ReqSetAuto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ReqSetAuto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              isOpen_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return game.message.RecycleMessage.internal_static_MSG_Recycle_ReqSetAuto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return game.message.RecycleMessage.internal_static_MSG_Recycle_ReqSetAuto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              game.message.RecycleMessage.ReqSetAuto.class, game.message.RecycleMessage.ReqSetAuto.Builder.class);
    }

    public static com.google.protobuf.Parser<ReqSetAuto> PARSER =
        new com.google.protobuf.AbstractParser<ReqSetAuto>() {
      public ReqSetAuto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReqSetAuto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ReqSetAuto> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code MSG_Recycle.ReqSetAuto.MsgID}
     */
    public enum MsgID
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>eMsgID = 519202;</code>
       */
      eMsgID(0, 519202),
      ;

      /**
       * <code>eMsgID = 519202;</code>
       */
      public static final int eMsgID_VALUE = 519202;


      public final int getNumber() { return value; }

      public static MsgID valueOf(int value) {
        switch (value) {
          case 519202: return eMsgID;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MsgID>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<MsgID>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MsgID>() {
              public MsgID findValueByNumber(int number) {
                return MsgID.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return game.message.RecycleMessage.ReqSetAuto.getDescriptor().getEnumTypes().get(0);
      }

      private static final MsgID[] VALUES = values();

      public static MsgID valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private MsgID(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:MSG_Recycle.ReqSetAuto.MsgID)
    }

    private int bitField0_;
    // required bool isOpen = 1;
    public static final int ISOPEN_FIELD_NUMBER = 1;
    private boolean isOpen_;
    /**
     * <code>required bool isOpen = 1;</code>
     *
     * <pre>
     *是否开启自动熔炼，true开启false关闭
     * </pre>
     */
    public boolean hasIsOpen() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bool isOpen = 1;</code>
     *
     * <pre>
     *是否开启自动熔炼，true开启false关闭
     * </pre>
     */
    public boolean getIsOpen() {
      return isOpen_;
    }

    private void initFields() {
      isOpen_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasIsOpen()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, isOpen_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, isOpen_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static game.message.RecycleMessage.ReqSetAuto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static game.message.RecycleMessage.ReqSetAuto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static game.message.RecycleMessage.ReqSetAuto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static game.message.RecycleMessage.ReqSetAuto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static game.message.RecycleMessage.ReqSetAuto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static game.message.RecycleMessage.ReqSetAuto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static game.message.RecycleMessage.ReqSetAuto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static game.message.RecycleMessage.ReqSetAuto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static game.message.RecycleMessage.ReqSetAuto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static game.message.RecycleMessage.ReqSetAuto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(game.message.RecycleMessage.ReqSetAuto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MSG_Recycle.ReqSetAuto}
     *
     * <pre>
     *Client -&gt; Server 请求设置自动熔炼垃圾装备
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements game.message.RecycleMessage.ReqSetAutoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return game.message.RecycleMessage.internal_static_MSG_Recycle_ReqSetAuto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return game.message.RecycleMessage.internal_static_MSG_Recycle_ReqSetAuto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                game.message.RecycleMessage.ReqSetAuto.class, game.message.RecycleMessage.ReqSetAuto.Builder.class);
      }

      // Construct using game.message.RecycleMessage.ReqSetAuto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        isOpen_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return game.message.RecycleMessage.internal_static_MSG_Recycle_ReqSetAuto_descriptor;
      }

      public game.message.RecycleMessage.ReqSetAuto getDefaultInstanceForType() {
        return game.message.RecycleMessage.ReqSetAuto.getDefaultInstance();
      }

      public game.message.RecycleMessage.ReqSetAuto build() {
        game.message.RecycleMessage.ReqSetAuto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public game.message.RecycleMessage.ReqSetAuto buildPartial() {
        game.message.RecycleMessage.ReqSetAuto result = new game.message.RecycleMessage.ReqSetAuto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.isOpen_ = isOpen_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof game.message.RecycleMessage.ReqSetAuto) {
          return mergeFrom((game.message.RecycleMessage.ReqSetAuto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(game.message.RecycleMessage.ReqSetAuto other) {
        if (other == game.message.RecycleMessage.ReqSetAuto.getDefaultInstance()) return this;
        if (other.hasIsOpen()) {
          setIsOpen(other.getIsOpen());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasIsOpen()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        game.message.RecycleMessage.ReqSetAuto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (game.message.RecycleMessage.ReqSetAuto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required bool isOpen = 1;
      private boolean isOpen_ ;
      /**
       * <code>required bool isOpen = 1;</code>
       *
       * <pre>
       *是否开启自动熔炼，true开启false关闭
       * </pre>
       */
      public boolean hasIsOpen() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bool isOpen = 1;</code>
       *
       * <pre>
       *是否开启自动熔炼，true开启false关闭
       * </pre>
       */
      public boolean getIsOpen() {
        return isOpen_;
      }
      /**
       * <code>required bool isOpen = 1;</code>
       *
       * <pre>
       *是否开启自动熔炼，true开启false关闭
       * </pre>
       */
      public Builder setIsOpen(boolean value) {
        bitField0_ |= 0x00000001;
        isOpen_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool isOpen = 1;</code>
       *
       * <pre>
       *是否开启自动熔炼，true开启false关闭
       * </pre>
       */
      public Builder clearIsOpen() {
        bitField0_ = (bitField0_ & ~0x00000001);
        isOpen_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:MSG_Recycle.ReqSetAuto)
    }

    static {
      defaultInstance = new ReqSetAuto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:MSG_Recycle.ReqSetAuto)
  }

  public interface ResRecycleOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 num = 1;
    /**
     * <code>required int32 num = 1;</code>
     *
     * <pre>
     *获得道具数量
     * </pre>
     */
    boolean hasNum();
    /**
     * <code>required int32 num = 1;</code>
     *
     * <pre>
     *获得道具数量
     * </pre>
     */
    int getNum();
  }
  /**
   * Protobuf type {@code MSG_Recycle.ResRecycle}
   *
   * <pre>
   *Server -&gt; Client 回收返回
   * </pre>
   */
  public static final class ResRecycle extends
      com.google.protobuf.GeneratedMessage
      implements ResRecycleOrBuilder {
    // Use ResRecycle.newBuilder() to construct.
    private ResRecycle(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ResRecycle(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ResRecycle defaultInstance;
    public static ResRecycle getDefaultInstance() {
      return defaultInstance;
    }

    public ResRecycle getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ResRecycle(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              num_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return game.message.RecycleMessage.internal_static_MSG_Recycle_ResRecycle_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return game.message.RecycleMessage.internal_static_MSG_Recycle_ResRecycle_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              game.message.RecycleMessage.ResRecycle.class, game.message.RecycleMessage.ResRecycle.Builder.class);
    }

    public static com.google.protobuf.Parser<ResRecycle> PARSER =
        new com.google.protobuf.AbstractParser<ResRecycle>() {
      public ResRecycle parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResRecycle(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ResRecycle> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code MSG_Recycle.ResRecycle.MsgID}
     */
    public enum MsgID
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>eMsgID = 519101;</code>
       */
      eMsgID(0, 519101),
      ;

      /**
       * <code>eMsgID = 519101;</code>
       */
      public static final int eMsgID_VALUE = 519101;


      public final int getNumber() { return value; }

      public static MsgID valueOf(int value) {
        switch (value) {
          case 519101: return eMsgID;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MsgID>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<MsgID>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MsgID>() {
              public MsgID findValueByNumber(int number) {
                return MsgID.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return game.message.RecycleMessage.ResRecycle.getDescriptor().getEnumTypes().get(0);
      }

      private static final MsgID[] VALUES = values();

      public static MsgID valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private MsgID(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:MSG_Recycle.ResRecycle.MsgID)
    }

    private int bitField0_;
    // required int32 num = 1;
    public static final int NUM_FIELD_NUMBER = 1;
    private int num_;
    /**
     * <code>required int32 num = 1;</code>
     *
     * <pre>
     *获得道具数量
     * </pre>
     */
    public boolean hasNum() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 num = 1;</code>
     *
     * <pre>
     *获得道具数量
     * </pre>
     */
    public int getNum() {
      return num_;
    }

    private void initFields() {
      num_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasNum()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, num_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, num_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static game.message.RecycleMessage.ResRecycle parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static game.message.RecycleMessage.ResRecycle parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static game.message.RecycleMessage.ResRecycle parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static game.message.RecycleMessage.ResRecycle parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static game.message.RecycleMessage.ResRecycle parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static game.message.RecycleMessage.ResRecycle parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static game.message.RecycleMessage.ResRecycle parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static game.message.RecycleMessage.ResRecycle parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static game.message.RecycleMessage.ResRecycle parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static game.message.RecycleMessage.ResRecycle parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(game.message.RecycleMessage.ResRecycle prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MSG_Recycle.ResRecycle}
     *
     * <pre>
     *Server -&gt; Client 回收返回
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements game.message.RecycleMessage.ResRecycleOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return game.message.RecycleMessage.internal_static_MSG_Recycle_ResRecycle_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return game.message.RecycleMessage.internal_static_MSG_Recycle_ResRecycle_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                game.message.RecycleMessage.ResRecycle.class, game.message.RecycleMessage.ResRecycle.Builder.class);
      }

      // Construct using game.message.RecycleMessage.ResRecycle.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        num_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return game.message.RecycleMessage.internal_static_MSG_Recycle_ResRecycle_descriptor;
      }

      public game.message.RecycleMessage.ResRecycle getDefaultInstanceForType() {
        return game.message.RecycleMessage.ResRecycle.getDefaultInstance();
      }

      public game.message.RecycleMessage.ResRecycle build() {
        game.message.RecycleMessage.ResRecycle result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public game.message.RecycleMessage.ResRecycle buildPartial() {
        game.message.RecycleMessage.ResRecycle result = new game.message.RecycleMessage.ResRecycle(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.num_ = num_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof game.message.RecycleMessage.ResRecycle) {
          return mergeFrom((game.message.RecycleMessage.ResRecycle)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(game.message.RecycleMessage.ResRecycle other) {
        if (other == game.message.RecycleMessage.ResRecycle.getDefaultInstance()) return this;
        if (other.hasNum()) {
          setNum(other.getNum());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasNum()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        game.message.RecycleMessage.ResRecycle parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (game.message.RecycleMessage.ResRecycle) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 num = 1;
      private int num_ ;
      /**
       * <code>required int32 num = 1;</code>
       *
       * <pre>
       *获得道具数量
       * </pre>
       */
      public boolean hasNum() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 num = 1;</code>
       *
       * <pre>
       *获得道具数量
       * </pre>
       */
      public int getNum() {
        return num_;
      }
      /**
       * <code>required int32 num = 1;</code>
       *
       * <pre>
       *获得道具数量
       * </pre>
       */
      public Builder setNum(int value) {
        bitField0_ |= 0x00000001;
        num_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 num = 1;</code>
       *
       * <pre>
       *获得道具数量
       * </pre>
       */
      public Builder clearNum() {
        bitField0_ = (bitField0_ & ~0x00000001);
        num_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:MSG_Recycle.ResRecycle)
    }

    static {
      defaultInstance = new ResRecycle(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:MSG_Recycle.ResRecycle)
  }

  public interface ResSetAutoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required bool isOpen = 1;
    /**
     * <code>required bool isOpen = 1;</code>
     *
     * <pre>
     *设置结果true开启false关闭
     * </pre>
     */
    boolean hasIsOpen();
    /**
     * <code>required bool isOpen = 1;</code>
     *
     * <pre>
     *设置结果true开启false关闭
     * </pre>
     */
    boolean getIsOpen();
  }
  /**
   * Protobuf type {@code MSG_Recycle.ResSetAuto}
   *
   * <pre>
   *Server -&gt; Client 返回设置自动熔炼垃圾装备
   * </pre>
   */
  public static final class ResSetAuto extends
      com.google.protobuf.GeneratedMessage
      implements ResSetAutoOrBuilder {
    // Use ResSetAuto.newBuilder() to construct.
    private ResSetAuto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ResSetAuto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ResSetAuto defaultInstance;
    public static ResSetAuto getDefaultInstance() {
      return defaultInstance;
    }

    public ResSetAuto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ResSetAuto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              isOpen_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return game.message.RecycleMessage.internal_static_MSG_Recycle_ResSetAuto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return game.message.RecycleMessage.internal_static_MSG_Recycle_ResSetAuto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              game.message.RecycleMessage.ResSetAuto.class, game.message.RecycleMessage.ResSetAuto.Builder.class);
    }

    public static com.google.protobuf.Parser<ResSetAuto> PARSER =
        new com.google.protobuf.AbstractParser<ResSetAuto>() {
      public ResSetAuto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResSetAuto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ResSetAuto> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code MSG_Recycle.ResSetAuto.MsgID}
     */
    public enum MsgID
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>eMsgID = 519102;</code>
       */
      eMsgID(0, 519102),
      ;

      /**
       * <code>eMsgID = 519102;</code>
       */
      public static final int eMsgID_VALUE = 519102;


      public final int getNumber() { return value; }

      public static MsgID valueOf(int value) {
        switch (value) {
          case 519102: return eMsgID;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MsgID>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<MsgID>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MsgID>() {
              public MsgID findValueByNumber(int number) {
                return MsgID.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return game.message.RecycleMessage.ResSetAuto.getDescriptor().getEnumTypes().get(0);
      }

      private static final MsgID[] VALUES = values();

      public static MsgID valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private MsgID(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:MSG_Recycle.ResSetAuto.MsgID)
    }

    private int bitField0_;
    // required bool isOpen = 1;
    public static final int ISOPEN_FIELD_NUMBER = 1;
    private boolean isOpen_;
    /**
     * <code>required bool isOpen = 1;</code>
     *
     * <pre>
     *设置结果true开启false关闭
     * </pre>
     */
    public boolean hasIsOpen() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bool isOpen = 1;</code>
     *
     * <pre>
     *设置结果true开启false关闭
     * </pre>
     */
    public boolean getIsOpen() {
      return isOpen_;
    }

    private void initFields() {
      isOpen_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasIsOpen()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, isOpen_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, isOpen_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static game.message.RecycleMessage.ResSetAuto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static game.message.RecycleMessage.ResSetAuto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static game.message.RecycleMessage.ResSetAuto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static game.message.RecycleMessage.ResSetAuto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static game.message.RecycleMessage.ResSetAuto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static game.message.RecycleMessage.ResSetAuto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static game.message.RecycleMessage.ResSetAuto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static game.message.RecycleMessage.ResSetAuto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static game.message.RecycleMessage.ResSetAuto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static game.message.RecycleMessage.ResSetAuto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(game.message.RecycleMessage.ResSetAuto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MSG_Recycle.ResSetAuto}
     *
     * <pre>
     *Server -&gt; Client 返回设置自动熔炼垃圾装备
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements game.message.RecycleMessage.ResSetAutoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return game.message.RecycleMessage.internal_static_MSG_Recycle_ResSetAuto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return game.message.RecycleMessage.internal_static_MSG_Recycle_ResSetAuto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                game.message.RecycleMessage.ResSetAuto.class, game.message.RecycleMessage.ResSetAuto.Builder.class);
      }

      // Construct using game.message.RecycleMessage.ResSetAuto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        isOpen_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return game.message.RecycleMessage.internal_static_MSG_Recycle_ResSetAuto_descriptor;
      }

      public game.message.RecycleMessage.ResSetAuto getDefaultInstanceForType() {
        return game.message.RecycleMessage.ResSetAuto.getDefaultInstance();
      }

      public game.message.RecycleMessage.ResSetAuto build() {
        game.message.RecycleMessage.ResSetAuto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public game.message.RecycleMessage.ResSetAuto buildPartial() {
        game.message.RecycleMessage.ResSetAuto result = new game.message.RecycleMessage.ResSetAuto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.isOpen_ = isOpen_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof game.message.RecycleMessage.ResSetAuto) {
          return mergeFrom((game.message.RecycleMessage.ResSetAuto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(game.message.RecycleMessage.ResSetAuto other) {
        if (other == game.message.RecycleMessage.ResSetAuto.getDefaultInstance()) return this;
        if (other.hasIsOpen()) {
          setIsOpen(other.getIsOpen());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasIsOpen()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        game.message.RecycleMessage.ResSetAuto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (game.message.RecycleMessage.ResSetAuto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required bool isOpen = 1;
      private boolean isOpen_ ;
      /**
       * <code>required bool isOpen = 1;</code>
       *
       * <pre>
       *设置结果true开启false关闭
       * </pre>
       */
      public boolean hasIsOpen() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bool isOpen = 1;</code>
       *
       * <pre>
       *设置结果true开启false关闭
       * </pre>
       */
      public boolean getIsOpen() {
        return isOpen_;
      }
      /**
       * <code>required bool isOpen = 1;</code>
       *
       * <pre>
       *设置结果true开启false关闭
       * </pre>
       */
      public Builder setIsOpen(boolean value) {
        bitField0_ |= 0x00000001;
        isOpen_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool isOpen = 1;</code>
       *
       * <pre>
       *设置结果true开启false关闭
       * </pre>
       */
      public Builder clearIsOpen() {
        bitField0_ = (bitField0_ & ~0x00000001);
        isOpen_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:MSG_Recycle.ResSetAuto)
    }

    static {
      defaultInstance = new ResSetAuto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:MSG_Recycle.ResSetAuto)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_MSG_Recycle_ReqRecycle_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MSG_Recycle_ReqRecycle_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_MSG_Recycle_ReqSetAuto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MSG_Recycle_ReqSetAuto_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_MSG_Recycle_ResRecycle_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MSG_Recycle_ResRecycle_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_MSG_Recycle_ResSetAuto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MSG_Recycle_ResSetAuto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rrecycle.proto\022\013MSG_Recycle\"3\n\nReqRecyc" +
      "le\022\016\n\006itemId\030\001 \003(\004\"\025\n\005MsgID\022\014\n\006eMsgID\020\241\330" +
      "\037\"3\n\nReqSetAuto\022\016\n\006isOpen\030\001 \002(\010\"\025\n\005MsgID" +
      "\022\014\n\006eMsgID\020\242\330\037\"0\n\nResRecycle\022\013\n\003num\030\001 \002(" +
      "\005\"\025\n\005MsgID\022\014\n\006eMsgID\020\275\327\037\"3\n\nResSetAuto\022\016" +
      "\n\006isOpen\030\001 \002(\010\"\025\n\005MsgID\022\014\n\006eMsgID\020\276\327\037B\036\n" +
      "\014game.messageB\016RecycleMessage"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_MSG_Recycle_ReqRecycle_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_MSG_Recycle_ReqRecycle_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_MSG_Recycle_ReqRecycle_descriptor,
              new java.lang.String[] { "ItemId", });
          internal_static_MSG_Recycle_ReqSetAuto_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_MSG_Recycle_ReqSetAuto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_MSG_Recycle_ReqSetAuto_descriptor,
              new java.lang.String[] { "IsOpen", });
          internal_static_MSG_Recycle_ResRecycle_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_MSG_Recycle_ResRecycle_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_MSG_Recycle_ResRecycle_descriptor,
              new java.lang.String[] { "Num", });
          internal_static_MSG_Recycle_ResSetAuto_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_MSG_Recycle_ResSetAuto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_MSG_Recycle_ResSetAuto_descriptor,
              new java.lang.String[] { "IsOpen", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
