// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: shihai.proto

package game.message;

public final class ShiHaiMessage {
  private ShiHaiMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ReqShiHaiDataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code MSG_ShiHai.ReqShiHaiData}
   *
   * <pre>
   *打开面板，返回ResShiHaiData
   * </pre>
   */
  public static final class ReqShiHaiData extends
      com.google.protobuf.GeneratedMessage
      implements ReqShiHaiDataOrBuilder {
    // Use ReqShiHaiData.newBuilder() to construct.
    private ReqShiHaiData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ReqShiHaiData(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ReqShiHaiData defaultInstance;
    public static ReqShiHaiData getDefaultInstance() {
      return defaultInstance;
    }

    public ReqShiHaiData getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ReqShiHaiData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return game.message.ShiHaiMessage.internal_static_MSG_ShiHai_ReqShiHaiData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return game.message.ShiHaiMessage.internal_static_MSG_ShiHai_ReqShiHaiData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              game.message.ShiHaiMessage.ReqShiHaiData.class, game.message.ShiHaiMessage.ReqShiHaiData.Builder.class);
    }

    public static com.google.protobuf.Parser<ReqShiHaiData> PARSER =
        new com.google.protobuf.AbstractParser<ReqShiHaiData>() {
      public ReqShiHaiData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReqShiHaiData(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ReqShiHaiData> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code MSG_ShiHai.ReqShiHaiData.MsgID}
     */
    public enum MsgID
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>eMsgID = 503201;</code>
       */
      eMsgID(0, 503201),
      ;

      /**
       * <code>eMsgID = 503201;</code>
       */
      public static final int eMsgID_VALUE = 503201;


      public final int getNumber() { return value; }

      public static MsgID valueOf(int value) {
        switch (value) {
          case 503201: return eMsgID;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MsgID>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<MsgID>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MsgID>() {
              public MsgID findValueByNumber(int number) {
                return MsgID.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return game.message.ShiHaiMessage.ReqShiHaiData.getDescriptor().getEnumTypes().get(0);
      }

      private static final MsgID[] VALUES = values();

      public static MsgID valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private MsgID(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:MSG_ShiHai.ReqShiHaiData.MsgID)
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static game.message.ShiHaiMessage.ReqShiHaiData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static game.message.ShiHaiMessage.ReqShiHaiData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static game.message.ShiHaiMessage.ReqShiHaiData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static game.message.ShiHaiMessage.ReqShiHaiData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static game.message.ShiHaiMessage.ReqShiHaiData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static game.message.ShiHaiMessage.ReqShiHaiData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static game.message.ShiHaiMessage.ReqShiHaiData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static game.message.ShiHaiMessage.ReqShiHaiData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static game.message.ShiHaiMessage.ReqShiHaiData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static game.message.ShiHaiMessage.ReqShiHaiData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(game.message.ShiHaiMessage.ReqShiHaiData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MSG_ShiHai.ReqShiHaiData}
     *
     * <pre>
     *打开面板，返回ResShiHaiData
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements game.message.ShiHaiMessage.ReqShiHaiDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return game.message.ShiHaiMessage.internal_static_MSG_ShiHai_ReqShiHaiData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return game.message.ShiHaiMessage.internal_static_MSG_ShiHai_ReqShiHaiData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                game.message.ShiHaiMessage.ReqShiHaiData.class, game.message.ShiHaiMessage.ReqShiHaiData.Builder.class);
      }

      // Construct using game.message.ShiHaiMessage.ReqShiHaiData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return game.message.ShiHaiMessage.internal_static_MSG_ShiHai_ReqShiHaiData_descriptor;
      }

      public game.message.ShiHaiMessage.ReqShiHaiData getDefaultInstanceForType() {
        return game.message.ShiHaiMessage.ReqShiHaiData.getDefaultInstance();
      }

      public game.message.ShiHaiMessage.ReqShiHaiData build() {
        game.message.ShiHaiMessage.ReqShiHaiData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public game.message.ShiHaiMessage.ReqShiHaiData buildPartial() {
        game.message.ShiHaiMessage.ReqShiHaiData result = new game.message.ShiHaiMessage.ReqShiHaiData(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof game.message.ShiHaiMessage.ReqShiHaiData) {
          return mergeFrom((game.message.ShiHaiMessage.ReqShiHaiData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(game.message.ShiHaiMessage.ReqShiHaiData other) {
        if (other == game.message.ShiHaiMessage.ReqShiHaiData.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        game.message.ShiHaiMessage.ReqShiHaiData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (game.message.ShiHaiMessage.ReqShiHaiData) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:MSG_ShiHai.ReqShiHaiData)
    }

    static {
      defaultInstance = new ReqShiHaiData(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:MSG_ShiHai.ReqShiHaiData)
  }

  public interface ResShiHaiDataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 cfgId = 1;
    /**
     * <code>required int32 cfgId = 1;</code>
     *
     * <pre>
     *境界，对应配置表id
     * </pre>
     */
    boolean hasCfgId();
    /**
     * <code>required int32 cfgId = 1;</code>
     *
     * <pre>
     *境界，对应配置表id
     * </pre>
     */
    int getCfgId();

    // required int32 layer = 2;
    /**
     * <code>required int32 layer = 2;</code>
     *
     * <pre>
     *万妖卷层数
     * </pre>
     */
    boolean hasLayer();
    /**
     * <code>required int32 layer = 2;</code>
     *
     * <pre>
     *万妖卷层数
     * </pre>
     */
    int getLayer();
  }
  /**
   * Protobuf type {@code MSG_ShiHai.ResShiHaiData}
   *
   * <pre>
   *返回识海数据
   * </pre>
   */
  public static final class ResShiHaiData extends
      com.google.protobuf.GeneratedMessage
      implements ResShiHaiDataOrBuilder {
    // Use ResShiHaiData.newBuilder() to construct.
    private ResShiHaiData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ResShiHaiData(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ResShiHaiData defaultInstance;
    public static ResShiHaiData getDefaultInstance() {
      return defaultInstance;
    }

    public ResShiHaiData getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ResShiHaiData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              cfgId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              layer_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return game.message.ShiHaiMessage.internal_static_MSG_ShiHai_ResShiHaiData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return game.message.ShiHaiMessage.internal_static_MSG_ShiHai_ResShiHaiData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              game.message.ShiHaiMessage.ResShiHaiData.class, game.message.ShiHaiMessage.ResShiHaiData.Builder.class);
    }

    public static com.google.protobuf.Parser<ResShiHaiData> PARSER =
        new com.google.protobuf.AbstractParser<ResShiHaiData>() {
      public ResShiHaiData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResShiHaiData(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ResShiHaiData> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code MSG_ShiHai.ResShiHaiData.MsgID}
     */
    public enum MsgID
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>eMsgID = 503101;</code>
       */
      eMsgID(0, 503101),
      ;

      /**
       * <code>eMsgID = 503101;</code>
       */
      public static final int eMsgID_VALUE = 503101;


      public final int getNumber() { return value; }

      public static MsgID valueOf(int value) {
        switch (value) {
          case 503101: return eMsgID;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MsgID>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<MsgID>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MsgID>() {
              public MsgID findValueByNumber(int number) {
                return MsgID.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return game.message.ShiHaiMessage.ResShiHaiData.getDescriptor().getEnumTypes().get(0);
      }

      private static final MsgID[] VALUES = values();

      public static MsgID valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private MsgID(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:MSG_ShiHai.ResShiHaiData.MsgID)
    }

    private int bitField0_;
    // required int32 cfgId = 1;
    public static final int CFGID_FIELD_NUMBER = 1;
    private int cfgId_;
    /**
     * <code>required int32 cfgId = 1;</code>
     *
     * <pre>
     *境界，对应配置表id
     * </pre>
     */
    public boolean hasCfgId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 cfgId = 1;</code>
     *
     * <pre>
     *境界，对应配置表id
     * </pre>
     */
    public int getCfgId() {
      return cfgId_;
    }

    // required int32 layer = 2;
    public static final int LAYER_FIELD_NUMBER = 2;
    private int layer_;
    /**
     * <code>required int32 layer = 2;</code>
     *
     * <pre>
     *万妖卷层数
     * </pre>
     */
    public boolean hasLayer() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 layer = 2;</code>
     *
     * <pre>
     *万妖卷层数
     * </pre>
     */
    public int getLayer() {
      return layer_;
    }

    private void initFields() {
      cfgId_ = 0;
      layer_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasCfgId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLayer()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, cfgId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, layer_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, cfgId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, layer_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static game.message.ShiHaiMessage.ResShiHaiData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static game.message.ShiHaiMessage.ResShiHaiData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static game.message.ShiHaiMessage.ResShiHaiData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static game.message.ShiHaiMessage.ResShiHaiData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static game.message.ShiHaiMessage.ResShiHaiData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static game.message.ShiHaiMessage.ResShiHaiData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static game.message.ShiHaiMessage.ResShiHaiData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static game.message.ShiHaiMessage.ResShiHaiData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static game.message.ShiHaiMessage.ResShiHaiData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static game.message.ShiHaiMessage.ResShiHaiData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(game.message.ShiHaiMessage.ResShiHaiData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MSG_ShiHai.ResShiHaiData}
     *
     * <pre>
     *返回识海数据
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements game.message.ShiHaiMessage.ResShiHaiDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return game.message.ShiHaiMessage.internal_static_MSG_ShiHai_ResShiHaiData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return game.message.ShiHaiMessage.internal_static_MSG_ShiHai_ResShiHaiData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                game.message.ShiHaiMessage.ResShiHaiData.class, game.message.ShiHaiMessage.ResShiHaiData.Builder.class);
      }

      // Construct using game.message.ShiHaiMessage.ResShiHaiData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        cfgId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        layer_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return game.message.ShiHaiMessage.internal_static_MSG_ShiHai_ResShiHaiData_descriptor;
      }

      public game.message.ShiHaiMessage.ResShiHaiData getDefaultInstanceForType() {
        return game.message.ShiHaiMessage.ResShiHaiData.getDefaultInstance();
      }

      public game.message.ShiHaiMessage.ResShiHaiData build() {
        game.message.ShiHaiMessage.ResShiHaiData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public game.message.ShiHaiMessage.ResShiHaiData buildPartial() {
        game.message.ShiHaiMessage.ResShiHaiData result = new game.message.ShiHaiMessage.ResShiHaiData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.cfgId_ = cfgId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.layer_ = layer_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof game.message.ShiHaiMessage.ResShiHaiData) {
          return mergeFrom((game.message.ShiHaiMessage.ResShiHaiData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(game.message.ShiHaiMessage.ResShiHaiData other) {
        if (other == game.message.ShiHaiMessage.ResShiHaiData.getDefaultInstance()) return this;
        if (other.hasCfgId()) {
          setCfgId(other.getCfgId());
        }
        if (other.hasLayer()) {
          setLayer(other.getLayer());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCfgId()) {
          
          return false;
        }
        if (!hasLayer()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        game.message.ShiHaiMessage.ResShiHaiData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (game.message.ShiHaiMessage.ResShiHaiData) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 cfgId = 1;
      private int cfgId_ ;
      /**
       * <code>required int32 cfgId = 1;</code>
       *
       * <pre>
       *境界，对应配置表id
       * </pre>
       */
      public boolean hasCfgId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 cfgId = 1;</code>
       *
       * <pre>
       *境界，对应配置表id
       * </pre>
       */
      public int getCfgId() {
        return cfgId_;
      }
      /**
       * <code>required int32 cfgId = 1;</code>
       *
       * <pre>
       *境界，对应配置表id
       * </pre>
       */
      public Builder setCfgId(int value) {
        bitField0_ |= 0x00000001;
        cfgId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 cfgId = 1;</code>
       *
       * <pre>
       *境界，对应配置表id
       * </pre>
       */
      public Builder clearCfgId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        cfgId_ = 0;
        onChanged();
        return this;
      }

      // required int32 layer = 2;
      private int layer_ ;
      /**
       * <code>required int32 layer = 2;</code>
       *
       * <pre>
       *万妖卷层数
       * </pre>
       */
      public boolean hasLayer() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 layer = 2;</code>
       *
       * <pre>
       *万妖卷层数
       * </pre>
       */
      public int getLayer() {
        return layer_;
      }
      /**
       * <code>required int32 layer = 2;</code>
       *
       * <pre>
       *万妖卷层数
       * </pre>
       */
      public Builder setLayer(int value) {
        bitField0_ |= 0x00000002;
        layer_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 layer = 2;</code>
       *
       * <pre>
       *万妖卷层数
       * </pre>
       */
      public Builder clearLayer() {
        bitField0_ = (bitField0_ & ~0x00000002);
        layer_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:MSG_ShiHai.ResShiHaiData)
    }

    static {
      defaultInstance = new ResShiHaiData(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:MSG_ShiHai.ResShiHaiData)
  }

  public interface ReqUpLevelOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code MSG_ShiHai.ReqUpLevel}
   *
   * <pre>
   *点击提升，返回ResShiHaiData
   * </pre>
   */
  public static final class ReqUpLevel extends
      com.google.protobuf.GeneratedMessage
      implements ReqUpLevelOrBuilder {
    // Use ReqUpLevel.newBuilder() to construct.
    private ReqUpLevel(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ReqUpLevel(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ReqUpLevel defaultInstance;
    public static ReqUpLevel getDefaultInstance() {
      return defaultInstance;
    }

    public ReqUpLevel getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ReqUpLevel(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return game.message.ShiHaiMessage.internal_static_MSG_ShiHai_ReqUpLevel_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return game.message.ShiHaiMessage.internal_static_MSG_ShiHai_ReqUpLevel_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              game.message.ShiHaiMessage.ReqUpLevel.class, game.message.ShiHaiMessage.ReqUpLevel.Builder.class);
    }

    public static com.google.protobuf.Parser<ReqUpLevel> PARSER =
        new com.google.protobuf.AbstractParser<ReqUpLevel>() {
      public ReqUpLevel parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReqUpLevel(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ReqUpLevel> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code MSG_ShiHai.ReqUpLevel.MsgID}
     */
    public enum MsgID
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>eMsgID = 503202;</code>
       */
      eMsgID(0, 503202),
      ;

      /**
       * <code>eMsgID = 503202;</code>
       */
      public static final int eMsgID_VALUE = 503202;


      public final int getNumber() { return value; }

      public static MsgID valueOf(int value) {
        switch (value) {
          case 503202: return eMsgID;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MsgID>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<MsgID>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MsgID>() {
              public MsgID findValueByNumber(int number) {
                return MsgID.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return game.message.ShiHaiMessage.ReqUpLevel.getDescriptor().getEnumTypes().get(0);
      }

      private static final MsgID[] VALUES = values();

      public static MsgID valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private MsgID(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:MSG_ShiHai.ReqUpLevel.MsgID)
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static game.message.ShiHaiMessage.ReqUpLevel parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static game.message.ShiHaiMessage.ReqUpLevel parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static game.message.ShiHaiMessage.ReqUpLevel parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static game.message.ShiHaiMessage.ReqUpLevel parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static game.message.ShiHaiMessage.ReqUpLevel parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static game.message.ShiHaiMessage.ReqUpLevel parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static game.message.ShiHaiMessage.ReqUpLevel parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static game.message.ShiHaiMessage.ReqUpLevel parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static game.message.ShiHaiMessage.ReqUpLevel parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static game.message.ShiHaiMessage.ReqUpLevel parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(game.message.ShiHaiMessage.ReqUpLevel prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MSG_ShiHai.ReqUpLevel}
     *
     * <pre>
     *点击提升，返回ResShiHaiData
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements game.message.ShiHaiMessage.ReqUpLevelOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return game.message.ShiHaiMessage.internal_static_MSG_ShiHai_ReqUpLevel_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return game.message.ShiHaiMessage.internal_static_MSG_ShiHai_ReqUpLevel_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                game.message.ShiHaiMessage.ReqUpLevel.class, game.message.ShiHaiMessage.ReqUpLevel.Builder.class);
      }

      // Construct using game.message.ShiHaiMessage.ReqUpLevel.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return game.message.ShiHaiMessage.internal_static_MSG_ShiHai_ReqUpLevel_descriptor;
      }

      public game.message.ShiHaiMessage.ReqUpLevel getDefaultInstanceForType() {
        return game.message.ShiHaiMessage.ReqUpLevel.getDefaultInstance();
      }

      public game.message.ShiHaiMessage.ReqUpLevel build() {
        game.message.ShiHaiMessage.ReqUpLevel result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public game.message.ShiHaiMessage.ReqUpLevel buildPartial() {
        game.message.ShiHaiMessage.ReqUpLevel result = new game.message.ShiHaiMessage.ReqUpLevel(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof game.message.ShiHaiMessage.ReqUpLevel) {
          return mergeFrom((game.message.ShiHaiMessage.ReqUpLevel)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(game.message.ShiHaiMessage.ReqUpLevel other) {
        if (other == game.message.ShiHaiMessage.ReqUpLevel.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        game.message.ShiHaiMessage.ReqUpLevel parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (game.message.ShiHaiMessage.ReqUpLevel) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:MSG_ShiHai.ReqUpLevel)
    }

    static {
      defaultInstance = new ReqUpLevel(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:MSG_ShiHai.ReqUpLevel)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_MSG_ShiHai_ReqShiHaiData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MSG_ShiHai_ReqShiHaiData_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_MSG_ShiHai_ResShiHaiData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MSG_ShiHai_ResShiHaiData_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_MSG_ShiHai_ReqUpLevel_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MSG_ShiHai_ReqUpLevel_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014shihai.proto\022\nMSG_ShiHai\"&\n\rReqShiHaiD" +
      "ata\"\025\n\005MsgID\022\014\n\006eMsgID\020\241\333\036\"D\n\rResShiHaiD" +
      "ata\022\r\n\005cfgId\030\001 \002(\005\022\r\n\005layer\030\002 \002(\005\"\025\n\005Msg" +
      "ID\022\014\n\006eMsgID\020\275\332\036\"#\n\nReqUpLevel\"\025\n\005MsgID\022" +
      "\014\n\006eMsgID\020\242\333\036B\035\n\014game.messageB\rShiHaiMes" +
      "sage"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_MSG_ShiHai_ReqShiHaiData_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_MSG_ShiHai_ReqShiHaiData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_MSG_ShiHai_ReqShiHaiData_descriptor,
              new java.lang.String[] { });
          internal_static_MSG_ShiHai_ResShiHaiData_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_MSG_ShiHai_ResShiHaiData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_MSG_ShiHai_ResShiHaiData_descriptor,
              new java.lang.String[] { "CfgId", "Layer", });
          internal_static_MSG_ShiHai_ReqUpLevel_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_MSG_ShiHai_ReqUpLevel_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_MSG_ShiHai_ReqUpLevel_descriptor,
              new java.lang.String[] { });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
