// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bravepeak.proto

package game.message;

public final class BravePeakMessage {
  private BravePeakMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface F2GSendBravePeakRewardOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 roleId = 1;
    /**
     * <code>required int64 roleId = 1;</code>
     *
     * <pre>
     *玩家角色
     * </pre>
     */
    boolean hasRoleId();
    /**
     * <code>required int64 roleId = 1;</code>
     *
     * <pre>
     *玩家角色
     * </pre>
     */
    long getRoleId();

    // required int32 floor = 2;
    /**
     * <code>required int32 floor = 2;</code>
     *
     * <pre>
     *玩家当前的层数
     * </pre>
     */
    boolean hasFloor();
    /**
     * <code>required int32 floor = 2;</code>
     *
     * <pre>
     *玩家当前的层数
     * </pre>
     */
    int getFloor();

    // required int32 copyMapId = 3;
    /**
     * <code>required int32 copyMapId = 3;</code>
     *
     * <pre>
     *副本配置id
     * </pre>
     */
    boolean hasCopyMapId();
    /**
     * <code>required int32 copyMapId = 3;</code>
     *
     * <pre>
     *副本配置id
     * </pre>
     */
    int getCopyMapId();

    // required bool needToNext = 4;
    /**
     * <code>required bool needToNext = 4;</code>
     *
     * <pre>
     *是否需要进入下一层
     * </pre>
     */
    boolean hasNeedToNext();
    /**
     * <code>required bool needToNext = 4;</code>
     *
     * <pre>
     *是否需要进入下一层
     * </pre>
     */
    boolean getNeedToNext();

    // required bool isGetReward = 5;
    /**
     * <code>required bool isGetReward = 5;</code>
     *
     * <pre>
     *是否这层已经领过奖
     * </pre>
     */
    boolean hasIsGetReward();
    /**
     * <code>required bool isGetReward = 5;</code>
     *
     * <pre>
     *是否这层已经领过奖
     * </pre>
     */
    boolean getIsGetReward();
  }
  /**
   * Protobuf type {@code MSG_BravePeak.F2GSendBravePeakReward}
   *
   * <pre>
   *Fight -&gt; Game 跨服发送勇者巅峰的奖励
   * </pre>
   */
  public static final class F2GSendBravePeakReward extends
      com.google.protobuf.GeneratedMessage
      implements F2GSendBravePeakRewardOrBuilder {
    // Use F2GSendBravePeakReward.newBuilder() to construct.
    private F2GSendBravePeakReward(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private F2GSendBravePeakReward(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final F2GSendBravePeakReward defaultInstance;
    public static F2GSendBravePeakReward getDefaultInstance() {
      return defaultInstance;
    }

    public F2GSendBravePeakReward getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private F2GSendBravePeakReward(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              roleId_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              floor_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              copyMapId_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              needToNext_ = input.readBool();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              isGetReward_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return game.message.BravePeakMessage.internal_static_MSG_BravePeak_F2GSendBravePeakReward_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return game.message.BravePeakMessage.internal_static_MSG_BravePeak_F2GSendBravePeakReward_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              game.message.BravePeakMessage.F2GSendBravePeakReward.class, game.message.BravePeakMessage.F2GSendBravePeakReward.Builder.class);
    }

    public static com.google.protobuf.Parser<F2GSendBravePeakReward> PARSER =
        new com.google.protobuf.AbstractParser<F2GSendBravePeakReward>() {
      public F2GSendBravePeakReward parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new F2GSendBravePeakReward(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<F2GSendBravePeakReward> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code MSG_BravePeak.F2GSendBravePeakReward.MsgID}
     */
    public enum MsgID
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>eMsgID = 515401;</code>
       */
      eMsgID(0, 515401),
      ;

      /**
       * <code>eMsgID = 515401;</code>
       */
      public static final int eMsgID_VALUE = 515401;


      public final int getNumber() { return value; }

      public static MsgID valueOf(int value) {
        switch (value) {
          case 515401: return eMsgID;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MsgID>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<MsgID>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MsgID>() {
              public MsgID findValueByNumber(int number) {
                return MsgID.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return game.message.BravePeakMessage.F2GSendBravePeakReward.getDescriptor().getEnumTypes().get(0);
      }

      private static final MsgID[] VALUES = values();

      public static MsgID valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private MsgID(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:MSG_BravePeak.F2GSendBravePeakReward.MsgID)
    }

    private int bitField0_;
    // required int64 roleId = 1;
    public static final int ROLEID_FIELD_NUMBER = 1;
    private long roleId_;
    /**
     * <code>required int64 roleId = 1;</code>
     *
     * <pre>
     *玩家角色
     * </pre>
     */
    public boolean hasRoleId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 roleId = 1;</code>
     *
     * <pre>
     *玩家角色
     * </pre>
     */
    public long getRoleId() {
      return roleId_;
    }

    // required int32 floor = 2;
    public static final int FLOOR_FIELD_NUMBER = 2;
    private int floor_;
    /**
     * <code>required int32 floor = 2;</code>
     *
     * <pre>
     *玩家当前的层数
     * </pre>
     */
    public boolean hasFloor() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 floor = 2;</code>
     *
     * <pre>
     *玩家当前的层数
     * </pre>
     */
    public int getFloor() {
      return floor_;
    }

    // required int32 copyMapId = 3;
    public static final int COPYMAPID_FIELD_NUMBER = 3;
    private int copyMapId_;
    /**
     * <code>required int32 copyMapId = 3;</code>
     *
     * <pre>
     *副本配置id
     * </pre>
     */
    public boolean hasCopyMapId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 copyMapId = 3;</code>
     *
     * <pre>
     *副本配置id
     * </pre>
     */
    public int getCopyMapId() {
      return copyMapId_;
    }

    // required bool needToNext = 4;
    public static final int NEEDTONEXT_FIELD_NUMBER = 4;
    private boolean needToNext_;
    /**
     * <code>required bool needToNext = 4;</code>
     *
     * <pre>
     *是否需要进入下一层
     * </pre>
     */
    public boolean hasNeedToNext() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required bool needToNext = 4;</code>
     *
     * <pre>
     *是否需要进入下一层
     * </pre>
     */
    public boolean getNeedToNext() {
      return needToNext_;
    }

    // required bool isGetReward = 5;
    public static final int ISGETREWARD_FIELD_NUMBER = 5;
    private boolean isGetReward_;
    /**
     * <code>required bool isGetReward = 5;</code>
     *
     * <pre>
     *是否这层已经领过奖
     * </pre>
     */
    public boolean hasIsGetReward() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required bool isGetReward = 5;</code>
     *
     * <pre>
     *是否这层已经领过奖
     * </pre>
     */
    public boolean getIsGetReward() {
      return isGetReward_;
    }

    private void initFields() {
      roleId_ = 0L;
      floor_ = 0;
      copyMapId_ = 0;
      needToNext_ = false;
      isGetReward_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasRoleId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFloor()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCopyMapId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNeedToNext()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIsGetReward()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, roleId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, floor_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, copyMapId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBool(4, needToNext_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBool(5, isGetReward_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, roleId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, floor_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, copyMapId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, needToNext_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, isGetReward_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static game.message.BravePeakMessage.F2GSendBravePeakReward parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static game.message.BravePeakMessage.F2GSendBravePeakReward parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static game.message.BravePeakMessage.F2GSendBravePeakReward parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static game.message.BravePeakMessage.F2GSendBravePeakReward parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static game.message.BravePeakMessage.F2GSendBravePeakReward parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static game.message.BravePeakMessage.F2GSendBravePeakReward parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static game.message.BravePeakMessage.F2GSendBravePeakReward parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static game.message.BravePeakMessage.F2GSendBravePeakReward parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static game.message.BravePeakMessage.F2GSendBravePeakReward parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static game.message.BravePeakMessage.F2GSendBravePeakReward parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(game.message.BravePeakMessage.F2GSendBravePeakReward prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MSG_BravePeak.F2GSendBravePeakReward}
     *
     * <pre>
     *Fight -&gt; Game 跨服发送勇者巅峰的奖励
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements game.message.BravePeakMessage.F2GSendBravePeakRewardOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return game.message.BravePeakMessage.internal_static_MSG_BravePeak_F2GSendBravePeakReward_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return game.message.BravePeakMessage.internal_static_MSG_BravePeak_F2GSendBravePeakReward_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                game.message.BravePeakMessage.F2GSendBravePeakReward.class, game.message.BravePeakMessage.F2GSendBravePeakReward.Builder.class);
      }

      // Construct using game.message.BravePeakMessage.F2GSendBravePeakReward.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        roleId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        floor_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        copyMapId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        needToNext_ = false;
        bitField0_ = (bitField0_ & ~0x00000008);
        isGetReward_ = false;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return game.message.BravePeakMessage.internal_static_MSG_BravePeak_F2GSendBravePeakReward_descriptor;
      }

      public game.message.BravePeakMessage.F2GSendBravePeakReward getDefaultInstanceForType() {
        return game.message.BravePeakMessage.F2GSendBravePeakReward.getDefaultInstance();
      }

      public game.message.BravePeakMessage.F2GSendBravePeakReward build() {
        game.message.BravePeakMessage.F2GSendBravePeakReward result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public game.message.BravePeakMessage.F2GSendBravePeakReward buildPartial() {
        game.message.BravePeakMessage.F2GSendBravePeakReward result = new game.message.BravePeakMessage.F2GSendBravePeakReward(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.roleId_ = roleId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.floor_ = floor_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.copyMapId_ = copyMapId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.needToNext_ = needToNext_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.isGetReward_ = isGetReward_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof game.message.BravePeakMessage.F2GSendBravePeakReward) {
          return mergeFrom((game.message.BravePeakMessage.F2GSendBravePeakReward)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(game.message.BravePeakMessage.F2GSendBravePeakReward other) {
        if (other == game.message.BravePeakMessage.F2GSendBravePeakReward.getDefaultInstance()) return this;
        if (other.hasRoleId()) {
          setRoleId(other.getRoleId());
        }
        if (other.hasFloor()) {
          setFloor(other.getFloor());
        }
        if (other.hasCopyMapId()) {
          setCopyMapId(other.getCopyMapId());
        }
        if (other.hasNeedToNext()) {
          setNeedToNext(other.getNeedToNext());
        }
        if (other.hasIsGetReward()) {
          setIsGetReward(other.getIsGetReward());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRoleId()) {
          
          return false;
        }
        if (!hasFloor()) {
          
          return false;
        }
        if (!hasCopyMapId()) {
          
          return false;
        }
        if (!hasNeedToNext()) {
          
          return false;
        }
        if (!hasIsGetReward()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        game.message.BravePeakMessage.F2GSendBravePeakReward parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (game.message.BravePeakMessage.F2GSendBravePeakReward) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 roleId = 1;
      private long roleId_ ;
      /**
       * <code>required int64 roleId = 1;</code>
       *
       * <pre>
       *玩家角色
       * </pre>
       */
      public boolean hasRoleId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 roleId = 1;</code>
       *
       * <pre>
       *玩家角色
       * </pre>
       */
      public long getRoleId() {
        return roleId_;
      }
      /**
       * <code>required int64 roleId = 1;</code>
       *
       * <pre>
       *玩家角色
       * </pre>
       */
      public Builder setRoleId(long value) {
        bitField0_ |= 0x00000001;
        roleId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 roleId = 1;</code>
       *
       * <pre>
       *玩家角色
       * </pre>
       */
      public Builder clearRoleId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        roleId_ = 0L;
        onChanged();
        return this;
      }

      // required int32 floor = 2;
      private int floor_ ;
      /**
       * <code>required int32 floor = 2;</code>
       *
       * <pre>
       *玩家当前的层数
       * </pre>
       */
      public boolean hasFloor() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 floor = 2;</code>
       *
       * <pre>
       *玩家当前的层数
       * </pre>
       */
      public int getFloor() {
        return floor_;
      }
      /**
       * <code>required int32 floor = 2;</code>
       *
       * <pre>
       *玩家当前的层数
       * </pre>
       */
      public Builder setFloor(int value) {
        bitField0_ |= 0x00000002;
        floor_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 floor = 2;</code>
       *
       * <pre>
       *玩家当前的层数
       * </pre>
       */
      public Builder clearFloor() {
        bitField0_ = (bitField0_ & ~0x00000002);
        floor_ = 0;
        onChanged();
        return this;
      }

      // required int32 copyMapId = 3;
      private int copyMapId_ ;
      /**
       * <code>required int32 copyMapId = 3;</code>
       *
       * <pre>
       *副本配置id
       * </pre>
       */
      public boolean hasCopyMapId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 copyMapId = 3;</code>
       *
       * <pre>
       *副本配置id
       * </pre>
       */
      public int getCopyMapId() {
        return copyMapId_;
      }
      /**
       * <code>required int32 copyMapId = 3;</code>
       *
       * <pre>
       *副本配置id
       * </pre>
       */
      public Builder setCopyMapId(int value) {
        bitField0_ |= 0x00000004;
        copyMapId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 copyMapId = 3;</code>
       *
       * <pre>
       *副本配置id
       * </pre>
       */
      public Builder clearCopyMapId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        copyMapId_ = 0;
        onChanged();
        return this;
      }

      // required bool needToNext = 4;
      private boolean needToNext_ ;
      /**
       * <code>required bool needToNext = 4;</code>
       *
       * <pre>
       *是否需要进入下一层
       * </pre>
       */
      public boolean hasNeedToNext() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required bool needToNext = 4;</code>
       *
       * <pre>
       *是否需要进入下一层
       * </pre>
       */
      public boolean getNeedToNext() {
        return needToNext_;
      }
      /**
       * <code>required bool needToNext = 4;</code>
       *
       * <pre>
       *是否需要进入下一层
       * </pre>
       */
      public Builder setNeedToNext(boolean value) {
        bitField0_ |= 0x00000008;
        needToNext_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool needToNext = 4;</code>
       *
       * <pre>
       *是否需要进入下一层
       * </pre>
       */
      public Builder clearNeedToNext() {
        bitField0_ = (bitField0_ & ~0x00000008);
        needToNext_ = false;
        onChanged();
        return this;
      }

      // required bool isGetReward = 5;
      private boolean isGetReward_ ;
      /**
       * <code>required bool isGetReward = 5;</code>
       *
       * <pre>
       *是否这层已经领过奖
       * </pre>
       */
      public boolean hasIsGetReward() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required bool isGetReward = 5;</code>
       *
       * <pre>
       *是否这层已经领过奖
       * </pre>
       */
      public boolean getIsGetReward() {
        return isGetReward_;
      }
      /**
       * <code>required bool isGetReward = 5;</code>
       *
       * <pre>
       *是否这层已经领过奖
       * </pre>
       */
      public Builder setIsGetReward(boolean value) {
        bitField0_ |= 0x00000010;
        isGetReward_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool isGetReward = 5;</code>
       *
       * <pre>
       *是否这层已经领过奖
       * </pre>
       */
      public Builder clearIsGetReward() {
        bitField0_ = (bitField0_ & ~0x00000010);
        isGetReward_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:MSG_BravePeak.F2GSendBravePeakReward)
    }

    static {
      defaultInstance = new F2GSendBravePeakReward(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:MSG_BravePeak.F2GSendBravePeakReward)
  }

  public interface G2PGetPlayerBravePeakInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 roleId = 1;
    /**
     * <code>required int64 roleId = 1;</code>
     *
     * <pre>
     *玩家角色
     * </pre>
     */
    boolean hasRoleId();
    /**
     * <code>required int64 roleId = 1;</code>
     *
     * <pre>
     *玩家角色
     * </pre>
     */
    long getRoleId();
  }
  /**
   * Protobuf type {@code MSG_BravePeak.G2PGetPlayerBravePeakInfo}
   *
   * <pre>
   *Game -&gt; Public 请求获取玩家勇者巅峰信息
   * </pre>
   */
  public static final class G2PGetPlayerBravePeakInfo extends
      com.google.protobuf.GeneratedMessage
      implements G2PGetPlayerBravePeakInfoOrBuilder {
    // Use G2PGetPlayerBravePeakInfo.newBuilder() to construct.
    private G2PGetPlayerBravePeakInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private G2PGetPlayerBravePeakInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final G2PGetPlayerBravePeakInfo defaultInstance;
    public static G2PGetPlayerBravePeakInfo getDefaultInstance() {
      return defaultInstance;
    }

    public G2PGetPlayerBravePeakInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private G2PGetPlayerBravePeakInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              roleId_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return game.message.BravePeakMessage.internal_static_MSG_BravePeak_G2PGetPlayerBravePeakInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return game.message.BravePeakMessage.internal_static_MSG_BravePeak_G2PGetPlayerBravePeakInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              game.message.BravePeakMessage.G2PGetPlayerBravePeakInfo.class, game.message.BravePeakMessage.G2PGetPlayerBravePeakInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<G2PGetPlayerBravePeakInfo> PARSER =
        new com.google.protobuf.AbstractParser<G2PGetPlayerBravePeakInfo>() {
      public G2PGetPlayerBravePeakInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new G2PGetPlayerBravePeakInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<G2PGetPlayerBravePeakInfo> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code MSG_BravePeak.G2PGetPlayerBravePeakInfo.MsgID}
     */
    public enum MsgID
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>eMsgID = 515301;</code>
       */
      eMsgID(0, 515301),
      ;

      /**
       * <code>eMsgID = 515301;</code>
       */
      public static final int eMsgID_VALUE = 515301;


      public final int getNumber() { return value; }

      public static MsgID valueOf(int value) {
        switch (value) {
          case 515301: return eMsgID;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MsgID>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<MsgID>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MsgID>() {
              public MsgID findValueByNumber(int number) {
                return MsgID.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return game.message.BravePeakMessage.G2PGetPlayerBravePeakInfo.getDescriptor().getEnumTypes().get(0);
      }

      private static final MsgID[] VALUES = values();

      public static MsgID valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private MsgID(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:MSG_BravePeak.G2PGetPlayerBravePeakInfo.MsgID)
    }

    private int bitField0_;
    // required int64 roleId = 1;
    public static final int ROLEID_FIELD_NUMBER = 1;
    private long roleId_;
    /**
     * <code>required int64 roleId = 1;</code>
     *
     * <pre>
     *玩家角色
     * </pre>
     */
    public boolean hasRoleId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 roleId = 1;</code>
     *
     * <pre>
     *玩家角色
     * </pre>
     */
    public long getRoleId() {
      return roleId_;
    }

    private void initFields() {
      roleId_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasRoleId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, roleId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, roleId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static game.message.BravePeakMessage.G2PGetPlayerBravePeakInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static game.message.BravePeakMessage.G2PGetPlayerBravePeakInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static game.message.BravePeakMessage.G2PGetPlayerBravePeakInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static game.message.BravePeakMessage.G2PGetPlayerBravePeakInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static game.message.BravePeakMessage.G2PGetPlayerBravePeakInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static game.message.BravePeakMessage.G2PGetPlayerBravePeakInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static game.message.BravePeakMessage.G2PGetPlayerBravePeakInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static game.message.BravePeakMessage.G2PGetPlayerBravePeakInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static game.message.BravePeakMessage.G2PGetPlayerBravePeakInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static game.message.BravePeakMessage.G2PGetPlayerBravePeakInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(game.message.BravePeakMessage.G2PGetPlayerBravePeakInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MSG_BravePeak.G2PGetPlayerBravePeakInfo}
     *
     * <pre>
     *Game -&gt; Public 请求获取玩家勇者巅峰信息
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements game.message.BravePeakMessage.G2PGetPlayerBravePeakInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return game.message.BravePeakMessage.internal_static_MSG_BravePeak_G2PGetPlayerBravePeakInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return game.message.BravePeakMessage.internal_static_MSG_BravePeak_G2PGetPlayerBravePeakInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                game.message.BravePeakMessage.G2PGetPlayerBravePeakInfo.class, game.message.BravePeakMessage.G2PGetPlayerBravePeakInfo.Builder.class);
      }

      // Construct using game.message.BravePeakMessage.G2PGetPlayerBravePeakInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        roleId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return game.message.BravePeakMessage.internal_static_MSG_BravePeak_G2PGetPlayerBravePeakInfo_descriptor;
      }

      public game.message.BravePeakMessage.G2PGetPlayerBravePeakInfo getDefaultInstanceForType() {
        return game.message.BravePeakMessage.G2PGetPlayerBravePeakInfo.getDefaultInstance();
      }

      public game.message.BravePeakMessage.G2PGetPlayerBravePeakInfo build() {
        game.message.BravePeakMessage.G2PGetPlayerBravePeakInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public game.message.BravePeakMessage.G2PGetPlayerBravePeakInfo buildPartial() {
        game.message.BravePeakMessage.G2PGetPlayerBravePeakInfo result = new game.message.BravePeakMessage.G2PGetPlayerBravePeakInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.roleId_ = roleId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof game.message.BravePeakMessage.G2PGetPlayerBravePeakInfo) {
          return mergeFrom((game.message.BravePeakMessage.G2PGetPlayerBravePeakInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(game.message.BravePeakMessage.G2PGetPlayerBravePeakInfo other) {
        if (other == game.message.BravePeakMessage.G2PGetPlayerBravePeakInfo.getDefaultInstance()) return this;
        if (other.hasRoleId()) {
          setRoleId(other.getRoleId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRoleId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        game.message.BravePeakMessage.G2PGetPlayerBravePeakInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (game.message.BravePeakMessage.G2PGetPlayerBravePeakInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 roleId = 1;
      private long roleId_ ;
      /**
       * <code>required int64 roleId = 1;</code>
       *
       * <pre>
       *玩家角色
       * </pre>
       */
      public boolean hasRoleId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 roleId = 1;</code>
       *
       * <pre>
       *玩家角色
       * </pre>
       */
      public long getRoleId() {
        return roleId_;
      }
      /**
       * <code>required int64 roleId = 1;</code>
       *
       * <pre>
       *玩家角色
       * </pre>
       */
      public Builder setRoleId(long value) {
        bitField0_ |= 0x00000001;
        roleId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 roleId = 1;</code>
       *
       * <pre>
       *玩家角色
       * </pre>
       */
      public Builder clearRoleId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        roleId_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:MSG_BravePeak.G2PGetPlayerBravePeakInfo)
    }

    static {
      defaultInstance = new G2PGetPlayerBravePeakInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:MSG_BravePeak.G2PGetPlayerBravePeakInfo)
  }

  public interface P2GPlayerBravePeakInfoResultOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 roleId = 1;
    /**
     * <code>required int64 roleId = 1;</code>
     *
     * <pre>
     *玩家角色
     * </pre>
     */
    boolean hasRoleId();
    /**
     * <code>required int64 roleId = 1;</code>
     *
     * <pre>
     *玩家角色
     * </pre>
     */
    long getRoleId();

    // required int32 floor = 2;
    /**
     * <code>required int32 floor = 2;</code>
     *
     * <pre>
     *玩家当前的层数
     * </pre>
     */
    boolean hasFloor();
    /**
     * <code>required int32 floor = 2;</code>
     *
     * <pre>
     *玩家当前的层数
     * </pre>
     */
    int getFloor();

    // required bool success = 3;
    /**
     * <code>required bool success = 3;</code>
     *
     * <pre>
     *当前层是否通过
     * </pre>
     */
    boolean hasSuccess();
    /**
     * <code>required bool success = 3;</code>
     *
     * <pre>
     *当前层是否通过
     * </pre>
     */
    boolean getSuccess();
  }
  /**
   * Protobuf type {@code MSG_BravePeak.P2GPlayerBravePeakInfoResult}
   *
   * <pre>
   *Public -&gt; Game 请求获取玩家勇者巅峰信息
   * </pre>
   */
  public static final class P2GPlayerBravePeakInfoResult extends
      com.google.protobuf.GeneratedMessage
      implements P2GPlayerBravePeakInfoResultOrBuilder {
    // Use P2GPlayerBravePeakInfoResult.newBuilder() to construct.
    private P2GPlayerBravePeakInfoResult(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private P2GPlayerBravePeakInfoResult(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final P2GPlayerBravePeakInfoResult defaultInstance;
    public static P2GPlayerBravePeakInfoResult getDefaultInstance() {
      return defaultInstance;
    }

    public P2GPlayerBravePeakInfoResult getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private P2GPlayerBravePeakInfoResult(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              roleId_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              floor_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              success_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return game.message.BravePeakMessage.internal_static_MSG_BravePeak_P2GPlayerBravePeakInfoResult_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return game.message.BravePeakMessage.internal_static_MSG_BravePeak_P2GPlayerBravePeakInfoResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              game.message.BravePeakMessage.P2GPlayerBravePeakInfoResult.class, game.message.BravePeakMessage.P2GPlayerBravePeakInfoResult.Builder.class);
    }

    public static com.google.protobuf.Parser<P2GPlayerBravePeakInfoResult> PARSER =
        new com.google.protobuf.AbstractParser<P2GPlayerBravePeakInfoResult>() {
      public P2GPlayerBravePeakInfoResult parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new P2GPlayerBravePeakInfoResult(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<P2GPlayerBravePeakInfoResult> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code MSG_BravePeak.P2GPlayerBravePeakInfoResult.MsgID}
     */
    public enum MsgID
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>eMsgID = 515402;</code>
       */
      eMsgID(0, 515402),
      ;

      /**
       * <code>eMsgID = 515402;</code>
       */
      public static final int eMsgID_VALUE = 515402;


      public final int getNumber() { return value; }

      public static MsgID valueOf(int value) {
        switch (value) {
          case 515402: return eMsgID;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MsgID>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<MsgID>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MsgID>() {
              public MsgID findValueByNumber(int number) {
                return MsgID.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return game.message.BravePeakMessage.P2GPlayerBravePeakInfoResult.getDescriptor().getEnumTypes().get(0);
      }

      private static final MsgID[] VALUES = values();

      public static MsgID valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private MsgID(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:MSG_BravePeak.P2GPlayerBravePeakInfoResult.MsgID)
    }

    private int bitField0_;
    // required int64 roleId = 1;
    public static final int ROLEID_FIELD_NUMBER = 1;
    private long roleId_;
    /**
     * <code>required int64 roleId = 1;</code>
     *
     * <pre>
     *玩家角色
     * </pre>
     */
    public boolean hasRoleId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 roleId = 1;</code>
     *
     * <pre>
     *玩家角色
     * </pre>
     */
    public long getRoleId() {
      return roleId_;
    }

    // required int32 floor = 2;
    public static final int FLOOR_FIELD_NUMBER = 2;
    private int floor_;
    /**
     * <code>required int32 floor = 2;</code>
     *
     * <pre>
     *玩家当前的层数
     * </pre>
     */
    public boolean hasFloor() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 floor = 2;</code>
     *
     * <pre>
     *玩家当前的层数
     * </pre>
     */
    public int getFloor() {
      return floor_;
    }

    // required bool success = 3;
    public static final int SUCCESS_FIELD_NUMBER = 3;
    private boolean success_;
    /**
     * <code>required bool success = 3;</code>
     *
     * <pre>
     *当前层是否通过
     * </pre>
     */
    public boolean hasSuccess() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required bool success = 3;</code>
     *
     * <pre>
     *当前层是否通过
     * </pre>
     */
    public boolean getSuccess() {
      return success_;
    }

    private void initFields() {
      roleId_ = 0L;
      floor_ = 0;
      success_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasRoleId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFloor()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSuccess()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, roleId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, floor_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBool(3, success_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, roleId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, floor_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, success_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static game.message.BravePeakMessage.P2GPlayerBravePeakInfoResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static game.message.BravePeakMessage.P2GPlayerBravePeakInfoResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static game.message.BravePeakMessage.P2GPlayerBravePeakInfoResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static game.message.BravePeakMessage.P2GPlayerBravePeakInfoResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static game.message.BravePeakMessage.P2GPlayerBravePeakInfoResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static game.message.BravePeakMessage.P2GPlayerBravePeakInfoResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static game.message.BravePeakMessage.P2GPlayerBravePeakInfoResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static game.message.BravePeakMessage.P2GPlayerBravePeakInfoResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static game.message.BravePeakMessage.P2GPlayerBravePeakInfoResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static game.message.BravePeakMessage.P2GPlayerBravePeakInfoResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(game.message.BravePeakMessage.P2GPlayerBravePeakInfoResult prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MSG_BravePeak.P2GPlayerBravePeakInfoResult}
     *
     * <pre>
     *Public -&gt; Game 请求获取玩家勇者巅峰信息
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements game.message.BravePeakMessage.P2GPlayerBravePeakInfoResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return game.message.BravePeakMessage.internal_static_MSG_BravePeak_P2GPlayerBravePeakInfoResult_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return game.message.BravePeakMessage.internal_static_MSG_BravePeak_P2GPlayerBravePeakInfoResult_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                game.message.BravePeakMessage.P2GPlayerBravePeakInfoResult.class, game.message.BravePeakMessage.P2GPlayerBravePeakInfoResult.Builder.class);
      }

      // Construct using game.message.BravePeakMessage.P2GPlayerBravePeakInfoResult.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        roleId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        floor_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        success_ = false;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return game.message.BravePeakMessage.internal_static_MSG_BravePeak_P2GPlayerBravePeakInfoResult_descriptor;
      }

      public game.message.BravePeakMessage.P2GPlayerBravePeakInfoResult getDefaultInstanceForType() {
        return game.message.BravePeakMessage.P2GPlayerBravePeakInfoResult.getDefaultInstance();
      }

      public game.message.BravePeakMessage.P2GPlayerBravePeakInfoResult build() {
        game.message.BravePeakMessage.P2GPlayerBravePeakInfoResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public game.message.BravePeakMessage.P2GPlayerBravePeakInfoResult buildPartial() {
        game.message.BravePeakMessage.P2GPlayerBravePeakInfoResult result = new game.message.BravePeakMessage.P2GPlayerBravePeakInfoResult(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.roleId_ = roleId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.floor_ = floor_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.success_ = success_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof game.message.BravePeakMessage.P2GPlayerBravePeakInfoResult) {
          return mergeFrom((game.message.BravePeakMessage.P2GPlayerBravePeakInfoResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(game.message.BravePeakMessage.P2GPlayerBravePeakInfoResult other) {
        if (other == game.message.BravePeakMessage.P2GPlayerBravePeakInfoResult.getDefaultInstance()) return this;
        if (other.hasRoleId()) {
          setRoleId(other.getRoleId());
        }
        if (other.hasFloor()) {
          setFloor(other.getFloor());
        }
        if (other.hasSuccess()) {
          setSuccess(other.getSuccess());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRoleId()) {
          
          return false;
        }
        if (!hasFloor()) {
          
          return false;
        }
        if (!hasSuccess()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        game.message.BravePeakMessage.P2GPlayerBravePeakInfoResult parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (game.message.BravePeakMessage.P2GPlayerBravePeakInfoResult) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 roleId = 1;
      private long roleId_ ;
      /**
       * <code>required int64 roleId = 1;</code>
       *
       * <pre>
       *玩家角色
       * </pre>
       */
      public boolean hasRoleId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 roleId = 1;</code>
       *
       * <pre>
       *玩家角色
       * </pre>
       */
      public long getRoleId() {
        return roleId_;
      }
      /**
       * <code>required int64 roleId = 1;</code>
       *
       * <pre>
       *玩家角色
       * </pre>
       */
      public Builder setRoleId(long value) {
        bitField0_ |= 0x00000001;
        roleId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 roleId = 1;</code>
       *
       * <pre>
       *玩家角色
       * </pre>
       */
      public Builder clearRoleId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        roleId_ = 0L;
        onChanged();
        return this;
      }

      // required int32 floor = 2;
      private int floor_ ;
      /**
       * <code>required int32 floor = 2;</code>
       *
       * <pre>
       *玩家当前的层数
       * </pre>
       */
      public boolean hasFloor() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 floor = 2;</code>
       *
       * <pre>
       *玩家当前的层数
       * </pre>
       */
      public int getFloor() {
        return floor_;
      }
      /**
       * <code>required int32 floor = 2;</code>
       *
       * <pre>
       *玩家当前的层数
       * </pre>
       */
      public Builder setFloor(int value) {
        bitField0_ |= 0x00000002;
        floor_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 floor = 2;</code>
       *
       * <pre>
       *玩家当前的层数
       * </pre>
       */
      public Builder clearFloor() {
        bitField0_ = (bitField0_ & ~0x00000002);
        floor_ = 0;
        onChanged();
        return this;
      }

      // required bool success = 3;
      private boolean success_ ;
      /**
       * <code>required bool success = 3;</code>
       *
       * <pre>
       *当前层是否通过
       * </pre>
       */
      public boolean hasSuccess() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required bool success = 3;</code>
       *
       * <pre>
       *当前层是否通过
       * </pre>
       */
      public boolean getSuccess() {
        return success_;
      }
      /**
       * <code>required bool success = 3;</code>
       *
       * <pre>
       *当前层是否通过
       * </pre>
       */
      public Builder setSuccess(boolean value) {
        bitField0_ |= 0x00000004;
        success_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool success = 3;</code>
       *
       * <pre>
       *当前层是否通过
       * </pre>
       */
      public Builder clearSuccess() {
        bitField0_ = (bitField0_ & ~0x00000004);
        success_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:MSG_BravePeak.P2GPlayerBravePeakInfoResult)
    }

    static {
      defaultInstance = new P2GPlayerBravePeakInfoResult(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:MSG_BravePeak.P2GPlayerBravePeakInfoResult)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_MSG_BravePeak_F2GSendBravePeakReward_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MSG_BravePeak_F2GSendBravePeakReward_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_MSG_BravePeak_G2PGetPlayerBravePeakInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MSG_BravePeak_G2PGetPlayerBravePeakInfo_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_MSG_BravePeak_P2GPlayerBravePeakInfoResult_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MSG_BravePeak_P2GPlayerBravePeakInfoResult_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017bravepeak.proto\022\rMSG_BravePeak\"\212\001\n\026F2G" +
      "SendBravePeakReward\022\016\n\006roleId\030\001 \002(\003\022\r\n\005f" +
      "loor\030\002 \002(\005\022\021\n\tcopyMapId\030\003 \002(\005\022\022\n\nneedToN" +
      "ext\030\004 \002(\010\022\023\n\013isGetReward\030\005 \002(\010\"\025\n\005MsgID\022" +
      "\014\n\006eMsgID\020\311\272\037\"B\n\031G2PGetPlayerBravePeakIn" +
      "fo\022\016\n\006roleId\030\001 \002(\003\"\025\n\005MsgID\022\014\n\006eMsgID\020\345\271" +
      "\037\"e\n\034P2GPlayerBravePeakInfoResult\022\016\n\006rol" +
      "eId\030\001 \002(\003\022\r\n\005floor\030\002 \002(\005\022\017\n\007success\030\003 \002(" +
      "\010\"\025\n\005MsgID\022\014\n\006eMsgID\020\312\272\037B \n\014game.message" +
      "B\020BravePeakMessage"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_MSG_BravePeak_F2GSendBravePeakReward_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_MSG_BravePeak_F2GSendBravePeakReward_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_MSG_BravePeak_F2GSendBravePeakReward_descriptor,
              new java.lang.String[] { "RoleId", "Floor", "CopyMapId", "NeedToNext", "IsGetReward", });
          internal_static_MSG_BravePeak_G2PGetPlayerBravePeakInfo_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_MSG_BravePeak_G2PGetPlayerBravePeakInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_MSG_BravePeak_G2PGetPlayerBravePeakInfo_descriptor,
              new java.lang.String[] { "RoleId", });
          internal_static_MSG_BravePeak_P2GPlayerBravePeakInfoResult_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_MSG_BravePeak_P2GPlayerBravePeakInfoResult_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_MSG_BravePeak_P2GPlayerBravePeakInfoResult_descriptor,
              new java.lang.String[] { "RoleId", "Floor", "Success", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
