#
jsp.log.timechoose=时间选择
jsp.log.onlinetitle=在线信息查询
jsp.log.search=查询
jsp.log.searchcon=查询条件
jsp.log.exportexcel=导出Excel
jsp.log.exportall=导出所有结果
jsp.log.pleasechoosedate=请选择日期！
jsp.log.time=时间
jsp.log.online=在线
jsp.log.acodetitle=激活码生成
jsp.log.loading=数据努力加载中...
jsp.log.generating=数据正在生产中...
jsp.log.sdateempty=开始日期不能为空！
jsp.log.edateempty=结束日期不能为空！
jsp.log.sdatelessthanedate=结束日期不能小于开始日期！
jsp.log.pageNumber=页码
jsp.log.pageSize=显示条数
jsp.log.all=共
jsp.log.record=条记录
jsp.log.page=页
jsp.log.totalpeoplenumber=总人数
jsp.log.totalpeoplecount=总人次
#
jsp.activereward.title=活跃奖励日志
jsp.shopbuy.title=商城购买日志
jsp.goldchange.title=元宝变化日志
jsp.guildchange.create=公会创建
jsp.guildchange.changename=公会改名
jsp.guildchange.changechairman=会长移交
jsp.guildchange.tanhe=会长弹劾
jsp.guildchange.unknown=未知
jsp.guild.title=公会基本信息
jsp.guild.id=公会ID
jsp.guild.guildname=公会名称
jsp.guild.chairmanname=会长名
jsp.guild.action=操作
jsp.guildchange.title=公会动态信息
jsp.guildmember.title=公会成员信息
jsp.guildmember.join=加入公会
jsp.guildmember.exit=退出公会
jsp.guildmember.unknown=未知
jsp.guild.guildDynamic=公会动态
jsp.guild.guildMember=公会成员
jsp.guildchange.create=公会创建
jsp.guildchange.changename=公会改名
jsp.guildchange.changechairman=会长移交
jsp.guildchange.tanhe=会长弹劾
jsp.guildchange.unknown=未知
#
jsp.activecode.code=礼包码
jsp.activecode.num=激活码数量
jsp.activecode.name=类型名(用途简述)
jsp.activecode.itemId=物品ID
jsp.activecode.itemnum=物品数量
jsp.activecode.universalcode=万能码
jsp.activecode.no=否
jsp.activecode.yes=是
jsp.activecode.starttime=有效开始时间
jsp.activecode.endtime=有效结束时间
jsp.activecode.platform=平台名
jsp.activecode.channel=生效渠道
jsp.activecode.server=生效区服
jsp.activecode.generate=生成
jsp.activecode.generatesuccess=生成成功!
jsp.activecode.allchannel=所有渠道
jsp.activecode.allcheck=全选(不选区服表示通用)
#
jsp.acodesearch.selectbatch=激活码批次号查询
jsp.acodesearch.selectcodeuse=激活码使用查询
jsp.acodesearch.code=激活码
jsp.acodesearch.activeName=激活码类型名
jsp.acodesearch.batch=批次号
jsp.acodesearch.itemList=物品列表
jsp.acodesearch.param=万能码
jsp.acodesearch.valide_time_begin=有效开始时间
jsp.acodesearch.valide_time_end=有效结束时间
jsp.acodesearch.plateform_name_big=渠道名
jsp.acodesearch.valide_server_id_list=有效区服
jsp.acodesearch.create_time=创建时间
jsp.acodesearch.get_time=激活码使用时间
jsp.acodesearch.get_player_id=使用者角色ID
jsp.acodesearch.get_plateform_aid=使用者角色名
jsp.acodesearch.get_account_id=使用者帐号
jsp.acodesearch.get_plateform_name=使用者平台名
jsp.acodesearch.get_server_id=使用者区服
jsp.acodesearch.activeCode=激活码
jsp.acodesearch.platformName=平台名
jsp.acodesearch.sid=区服
jsp.acodesearch.roleId=角色ID
jsp.acodesearch.userId=帐号ID
jsp.acodesearch.actionId=唯一标识
jsp.acodesearch.yes=是
jsp.acodesearch.no=否
jsp.acodesearch.opt=操作
#
jsp.during.title=留存统计
jsp.during.newuser=新注册用户
jsp.during.rechargeuser=付费用户
jsp.during.onedayduring=次留
jsp.during.dayduring=留
jsp.during.getAllDuringList=总留存统计
jsp.during.getRechargeDuringList=付费玩家留存统计
#
online.echarts.people=人
online.echarts.maintitle=在线人数统计
online.echarts.subhead=当日在线
online.echarts.time=时间(时:分)
online.echarts.onlinepeople=在线人数
online.echarts.zonezoom=区域缩放
online.echarts.zonezoomback=区域缩放后退
online.echarts.max=最大值
online.echarts.min=最小值
online.echarts.average=平均值
online.echarts.chartshow=图表显示
online.echarts.tableshow=表格显示
#
career.echarts.maintitle=职业分布
career.echarts.career=职业
#
reason.echarts.maintitle=原因分布
reason.echarts.reason=原因
#0-玄剑1-天英
jsp.career.career0=玄剑
jsp.career.career1=天英
jsp.career.career2=地藏
jsp.career.career3=罗刹
jsp.career.unknown=未知
#
level.echarts.maintitle=等级分布统计
level.echarts.subhead=等级相应人数分布
level.echarts.peoplecount=人数
level.echarts.zonezoom=区域缩放
level.echarts.zonezoomback=区域缩放后退
level.echarts.level=等级
level.echarts.max=最大值
level.echarts.min=最小值
level.echarts.average=平均值
level.echarts.zonesum=选中点之前区域总值（包括选中点）
#
jsp.level.minlevel=最小等级
jsp.level.detail=(不填则统计所有等级)
jsp.level.createtime=创建时间
jsp.level.optional=(选填)
jsp.level.offline=离线时的等级分布
jsp.level.behindoffline=离线后加上离线挂机的等级分布
#
jsp.dailydata.title=服务器日常数据
jsp.dailydata.day=日期
jsp.dailydata.totalmoney=充值金额
jsp.dailydata.totalgold=充值元宝
jsp.dailydata.totaltimes=充值次数
jsp.dailydata.totalbindgold=赠送绑定元宝
jsp.dailydata.totaluser=付费人数
jsp.dailydata.rateofpay=活跃付费率
jsp.dailydata.activenum=活跃玩家
jsp.dailydata.addnum=新增玩家
jsp.dailydata.addRechargeNum=新增付费玩家人数
jsp.dailydata.addRechargRate=新增付费率
jsp.dailydata.devicenum=活跃设备
jsp.dailydata.deviceaddnum=新增设备
jsp.dailydata.arpu=ARPU
jsp.dailydata.arppu=ARPPU
jsp.dailydata.maxnum=最高在线
jsp.dailydata.avgnum=平均在线
#
jsp.dailydata.allpay=平台总付费人数
jsp.dailydata.allactiveuser=平台总活跃玩家
jsp.dailydata.allpayrate=付费率
jsp.dailydata.allmoney=总充值金额
jsp.dailydata.allgold=总充值元宝
jsp.dailydata.allbindgold=总赠送绑定元宝
#
jsp.online.serverid=区服ID
jsp.online.servername=区服名称
jsp.online.time=时间
jsp.online.num=在线人数
jsp.online.action=操作
jsp.online.refreshall=全部刷新
jsp.online.refresh=刷新
jsp.online.refreshfail=刷新失败
jsp.online.loading=正在加载
jsp.online.conlinecount=当前在线人数
#
jsp.shopitem.title=商城道具销售统计
jsp.shopitem.conditionFailed=条件获取失败
jsp.shopitem.shopType=商店类型
jsp.shopitem.shopId=商店ID
jsp.shopitem.moneyType=货币类型
jsp.shopitem.itemmodelid=道具ID
jsp.shopitem.itemname=道具名称
jsp.shopitem.users=购买用户数
jsp.shopitem.roles=购买角色数
jsp.shopitem.totalnum=道具销量
jsp.shopitem.totalgold=消耗货币数
jsp.shopitem.totaltimes=购买次数
jsp.shopitem.allMoneyType=所有货币类型
#
jsp.money.title=货币产出消耗
jsp.money.1=已废弃货币
jsp.money.2=绑定金币
jsp.money.3=蓝钻
jsp.money.4=火钻
jsp.money.5=首席积分
jsp.money.6=科技点
jsp.money.7=善恶值
jsp.money.8=经验值
jsp.money.9=体力
jsp.money.10=成就
jsp.money.11=会贡
jsp.money.12=竞技场积分
jsp.money.13=勇气值
jsp.money.14=战魂点
jsp.money.15=导师积分
jsp.money.16=魅力值
jsp.money.17=龙灵值
jsp.money.18=创世积分
jsp.money.19=宝库积分
jsp.money.20=荣誉之战积分
jsp.money.21=活跃点
jsp.money.22=额外经验值
jsp.money.23=学分
jsp.money.24=荣誉值
jsp.money.25=军功
jsp.money.26=特权经验
jsp.money.27=乱斗点数
jsp.money.unknown=未知类型
jsp.money.moneytype=货币类型
jsp.money.choosemoney=选择货币
jsp.money.choose=请选择
jsp.money.ok=确认
jsp.money.cancel=取消
jsp.money.day=日期
jsp.money.output=产出
jsp.money.consume=消耗
jsp.money.balance=结余
jsp.money.choosediv=货币类型选择(不选则只统计元宝)
jsp.money.allcheck=全选
#
money.echarts.maintitle=产出及消耗统计
money.echarts.subhead=产出及消耗
money.echarts.zonezoom=区域缩放
money.echarts.zonezoomback=区域缩放后退
money.echarts.time=时间
money.echarts.count=数量
money.echarts.output=产出
money.echarts.consume=消耗
money.echarts.max=最大值
money.echarts.min=最小值
money.echarts.average=平均值
#
jsp.chat.title=聊天日志查询
jsp.chat.world=世界
jsp.chat.guild=公会
jsp.chat.team=队伍
jsp.chat.private=私人
jsp.chat.unknown=未知类型
#
jsp.horseillusion.title=坐骑幻化统计
jsp.horseillusion.illusionItemId=幻化道具ID
jsp.horseillusion.illusionpertime=坐骑幻化人次
jsp.horseillusion.layer=阶数
jsp.horseillusion.level=幻化星级
jsp.horseillusion.totalnum=道具消耗数量
jsp.horseillusion.totaltimes=玩家幻化次数
jsp.horseillusion.chooseItem=幻化道具
jsp.horseillusion.gold=元宝
jsp.horseillusion.huanhuadan=坐骑幻化丹
#
jsp.dragoon.title=骑兵升级统计
jsp.dragoon.key=骑兵ID
jsp.dragoon.totalgold=消耗元宝
jsp.dragoon.totaltimes=升级次数
jsp.dragoon.upplayernumber=升阶人数
jsp.dragoon.clickcount=点击次数
#
jsp.cloak.title=披风排行榜
jsp.cloak.gold=元宝
jsp.cloak.pifengshengjieshi=披风升阶石
jsp.cloak.upItemId=升级道具ID
jsp.cloak.chooseItem=升级道具
jsp.cloak.layer=阶数
jsp.cloak.totalnum=道具消耗数量
jsp.cloak.totaltimes=玩家升级次数
jsp.cloak.noitem=任务激活
jsp.cloak.unknown=未知道具ID:
jsp.cloak.upplayernumber=升阶人数
jsp.cloak.clickcount=点击次数
#
jsp.pet.title=宠物升级统计
jsp.pet.key=宠物ID
jsp.pet.totaltimes=升级次数
#
jsp.fightpower.title=战力排行榜
jsp.level.title=等级排行榜
jsp.level.layer=阶
jsp.level.level=级
jsp.money.title=财富排行榜
jsp.competition.title=竞技场排行榜
jsp.horse.title=坐骑排行榜
jsp.horseweapon.title=骑兵排行榜
jsp.rank.rank=排名
jsp.rank.roleid=角色ID
jsp.rank.rolename=角色名
jsp.rank.fightpower=战斗力
jsp.rank.level=等级
jsp.rank.money=财富(金币)
jsp.rank.competition=竞技
jsp.rank.horse=坐骑
jsp.rank.horseweapon=骑兵
jsp.rank.cloak=披风
jsp.levelrank.title=等级排行榜
jsp.levelrank.rank=排名
jsp.levelrank.rolename=角色名
jsp.levelrank.level=等级
#
log.logData=日志数据
log.paramerror=请求参数错误
log.configerror=配置异常，请检查配置文件fields.js
log.searcherror=数据查询异常
log.nodata=没有数据
log.noacodeinfo=没有使用该激活码相关记录
log.batcherror=批号错误
log.acodeerror=输入的激活码不正确
log.itemNum=数量:
log.isBind=是否绑定:
log.bind=绑定
log.noBind=不绑定
log.acodesuccess=激活码生成成功
log.lsgeterror=LS获取连接失败
log.lsDBerror=LS获取数据库连接信息失败
log.nobatchinfo=没有找到该批号相关激活码信息
log.nolslogtable=登录日志服表不存在
log.publicgeterror=公共服获取失败
log.dbfail=数据库操作失败
log.serverfail=服务器获取失败
log.rankfail=排行榜获取失败
#
log.title.nonickname=无昵称
log.title.nodata=未找到数据
log.title.battle.pagetitle=进出战场日志列表
log.title.city.pagetitle=城市战报名日志列表
log.title.number=日志编号
log.title.city=城市
log.title.time=时间
log.title.roleId=角色ID
log.title.roleName=角色名字
log.title.event=获得奖励
log.title.isEnter=进出战场状态
#
module.item=物品%d[道具ID=%s,数量=%s,绑定=%s,过期时间=%s]
module.yes=是
module.no=否
#
jsp.ranklog.title=排行榜日志查询
jsp.ranklog.fightPower=战力
jsp.ranklog.level=等级
jsp.ranklog.wealth=财富
jsp.ranklog.compete=竞技
jsp.ranklog.horse=坐骑
jsp.ranklog.wing=翅膀
jsp.ranklog.spiritBall=宠物精灵球
jsp.ranklog.guild=帮会
jsp.ranklog.rankType=排行榜类型
#
jsp.th.forbid.option=封号操作
jsp.th.forbid.button=一键封号
jsp.th.forbid.fastbutton=快捷封号
#
jsp.copymap.victory=胜利
jsp.copymap.draw=平局
jsp.copymap.success=成功
jsp.copymap.fail=失败
jsp.copymap.zoneType=副本类型
#
jsp.cityBattleOver.cityId=城市
jsp.cityBattleOver.conditionFailed=城市争夺战查询条件失败
#
jsp.kpList.title=王府列表
jsp.kpList.kpId=王府ID
jsp.kpList.kpName=王府名称
jsp.kpList.time=创建时间
jsp.kpList.moreInfo=更多信息
jsp.kpList.kpInfo=王府信息
jsp.kpList.member=王府成员信息
jsp.kpList.dynamic=王府动态信息
jsp.kpList.resultCount=结果记录数
#
jsp.kpInfo.title=王府信息
jsp.kpInfo.kpBaseInfo=王府基本信息
jsp.kpInfo.kpId=王府ID
jsp.kpInfo.kpName=王府名称
jsp.kpInfo.notice=王府宣言
jsp.kpInfo.isAuto=是否自动接受申请
jsp.kpInfo.limitLevel=最小加入等级
jsp.kpInfo.icon=旗帜
jsp.kpInfo.kpOfficeInfo=王府职位信息
jsp.kpInfo.destPower=王府职位
jsp.kpInfo.destRoleId=角色ID
jsp.kpInfo.destRoleName=角色名称
jsp.kpInfo.kpOffice0=普通成员
jsp.kpInfo.kpOffice1=王爷
jsp.kpInfo.kpOffice2=王妃
jsp.kpInfo.kpOffice3=军师
jsp.kpInfo.kpOffice4=辅国将军
jsp.kpInfo.kpOffice5=辅政将军
#
jsp.kpMember.title=王府成员
jsp.kpMember.kpId=王府ID
jsp.kpMember.guildId=公会
jsp.kpMember.guildName=公会名称
jsp.kpMember.moreInfo=更多信息
#
jsp.kpChange.title=王府动态
jsp.kpChange.kpId=王府ID
jsp.kpChange.kpMemberAdd=王府成员增加日志
jsp.kpChange.kpMemberDel=王府成员删除日志
jsp.kpChange.kpDonation=王府捐献日志
jsp.kpChange.kpGongXian=王府贡献日志
jsp.kpChange.kpBaseInfoModify=王府基本信息修改日志
jsp.kpChange.kpOffice=王府官职变动日志 
jsp.kpChange.kpUpLevel=王府升级日志 
#
jsp.crossWarRole.title=跨服战角色日志
jsp.flightRewardCreate.title=战斗奖励创建日志
jsp.flightRewardDelete.title=战斗奖励删除日志
jsp.flightRoomCreate.title=战斗房间创建日志
jsp.flightRoomDelete.title=战斗房间删除日志
jsp.playerEnterRoom.title=玩家进入房间日志

#
jsp.rechargeOverview.title=付费总览
jsp.rechargeOverview.date=日期
jsp.rechargeOverview.DAU=DAU
jsp.rechargeOverview.totalPayment=付费总额
jsp.rechargeOverview.newRechargeUsers=新增付费账号
jsp.rechargeOverview.rechargeUsers=当天付费账号
jsp.rechargeOverview.oldRechargeUsers=老玩家付费账号
jsp.rechargeOverview.newUsers=当天新增账号
jsp.rechargeOverview.rechargeRate=付费率
jsp.rechargeOverview.ARPU=ARPU
jsp.rechargeOverview.ARPPU=ARPPU
jsp.rechargeOverview.newrechargeRate=新增玩家付费率
jsp.rechargeOverview.oldrechargeRate=老玩家付费率

#
jsp.packageSearch.title=背包查询
jsp.packageSearch.packageInfo=背包信息
jsp.packageSearch.allroleId=全部角色
jsp.packageSearch.roleId=角色Id
jsp.packageSearch.roleName=角色名称
jsp.packageSearch.condition=查询条件
jsp.packageSearch.bags=背包(物品_数量)
jsp.packageSearch.stores=仓库(物品_数量)
jsp.packageSearch.equips=已穿戴装备(物品_数量)
#
jsp.vipChange.title=查看VIP变换日志