# commonlogbean
logentity.commonlogbean.time=Время
logentity.commonlogbean.roleId=ID персонажа
logentity.commonlogbean.roleName=Имя персонажа

# chatlog
logentity.chatlog.level=Уровень
logentity.chatlog.channel=Тип чата
logentity.chatlog.receRoleId=ID получателя
logentity.chatlog.content=Содержание чата

# roleloginlog
logentity.roleloginlog.platformName=Платформа
logentity.roleloginlog.level=Уровень
logentity.roleloginlog.onlineTime=Время в сети
logentity.roleloginlog.loginRoleIP=IP
logentity.roleloginlog.type=Тип

# itemchangelog
logentity.itemchangelog.roleLevel=Уровень
logentity.itemchangelog.itemId=ID предмета
logentity.itemchangelog.modelId=ID модели предмета
logentity.itemchangelog.changeNum=Изменение количества
logentity.itemchangelog.oldNum=Количество до
logentity.itemchangelog.newNum=Количество после
logentity.itemchangelog.reason=Код причины
logentity.itemchangelog.actionId=Связанный ID
logentity.itemchangelog.changeAction=Тип изменения
logentity.itemchangelog.coinType=Тип потраченной валюты
logentity.itemchangelog.coinNum=Количество потраченной валюты

# expchangelog
logentity.expchangelog.roleLevel=Уровень
logentity.expchangelog.changeNum=Изменение
logentity.expchangelog.reason=Код причины
logentity.expchangelog.beforeNum=Опыт до
logentity.expchangelog.afterNum=Опыт после
logentity.expchangelog.actionId=Связанный ID
logentity.expchangelog.upLevelExp=Опыт до следующего уровня

# goldchangelog
logentity.goldchangelog.roleLevel=Уровень
logentity.goldchangelog.changeNum=Изменение
logentity.goldchangelog.reason=Код причины
logentity.goldchangelog.beforeNum=Монет до
logentity.goldchangelog.afterNum=Монет после
logentity.goldchangelog.actionId=Связанный ID
logentity.goldchangelog.loginIp=IP

# guildbaselog
logentity.guildbaselog.guildId=ID гильдии
logentity.guildbaselog.guildName=Название гильдии
logentity.guildbaselog.type=Тип операции
logentity.guildbaselog.actId=ID целевого игрока
logentity.guildbaselog.actName=Имя целевого игрока
logentity.guildbaselog.param=Дополнительные параметры
logentity.guildbaselog.actionId=Связанный ID

# achievementawardlog
logentity.achievementrewardlog.confId=ID конфигурации
logentity.achievementrewardlog.itemStr=Награда (предметы)
logentity.achievementrewardlog.bindGold=Бонусные монеты
logentity.achievementrewardlog.value=Очки достижений
logentity.achievementrewardlog.actionId=Связанный ID

# crosscloneenterlog
logentity.crosscloneenterlog.fightId=ID комнаты
logentity.crosscloneenterlog.platsid=ID сервера
logentity.crosscloneenterlog.campNo=Лагерь
logentity.crosscloneenterlog.cloneId=ID подземелья
logentity.crosscloneenterlog.cloneName=Название подземелья
logentity.crosscloneenterlog.level=Уровень игрока

# crosscloneendlog
logentity.crosscloneendlog.roomId=ID комнаты
logentity.crosscloneendlog.modelId=ID подземелья
logentity.crosscloneendlog.CreateTime=Время создания
logentity.crosscloneendlog.success=Успех
logentity.crosscloneendlog.failure=Неудача
logentity.crosscloneendlog.condition=Условие

# fightrewardcreatelog
logentity.fightrewardcreatelog.key=ID сервера
logentity.fightrewardcreatelog.data=Данные награды

# fightrewardremovelog
logentity.fightrewardremovelog.key=ID сервера
logentity.fightrewardremovelog.data=Данные награды

# fightroomcreatelog
logentity.fightroomcreatelog.roleId=ID персонажа
logentity.fightroomcreatelog.roleName=Имя персонажа
logentity.fightroomcreatelog.plat=Платформа
logentity.fightroomcreatelog.fid=ID битвы
logentity.fightroomcreatelog.modelId=ID модели
logentity.fightroomcreatelog.sid=ID сервера
logentity.fightroomcreatelog.power=Боевая мощь
logentity.fightroomcreatelog.isAuto=Автоматически

# fightroomdeletelog
logentity.fightroomdeletelog.fid=ID комнаты
logentity.fightroomdeletelog.modelId=ID модели
logentity.fightroomdeletelog.state=Статус
logentity.fightroomdeletelog.typeRange=Тип
logentity.fightroomdeletelog.data=Данные игроков

# playerenterroomlog
logentity.playerenterroomlog.roleId=ID персонажа
logentity.playerenterroomlog.roleName=Имя персонажа
logentity.playerenterroomlog.plat=Платформа
logentity.playerenterroomlog.fid=ID комнаты
logentity.playerenterroomlog.modelId=ID модели
logentity.playerenterroomlog.sid=ID сервера
logentity.playerenterroomlog.sizeNo=Позиция
logentity.playerenterroomlog.level=Уровень
logentity.playerenterroomlog.power=Боевая мощь

# questionnirelog
logentity.questionnirelog.roleId=ID персонажа
logentity.questionnirelog.userId=ID пользователя
logentity.questionnirelog.data=Данные викторины

# rechargelog
logentity.rechargelog.orderNo=Номер заказа
logentity.rechargelog.userId=ID пользователя
logentity.rechargelog.roleId=ID персонажа
logentity.rechargelog.sid=ID сервера
logentity.rechargelog.goodsId=ID товара
logentity.rechargelog.goodsType=Тип товара
logentity.rechargelog.goodsExt=Дополнительные параметры товара
logentity.rechargelog.totalFee=Сумма (копейки)
logentity.rechargelog.itemId=ID предмета
logentity.rechargelog.gameMoney=Количество валюты
logentity.rechargelog.extParam=Дополнительные параметры
logentity.rechargelog.status=Статус
logentity.rechargelog.statusReason=Код статуса

# changerolenamelog
logentity.changerolenamelog.playerId=ID персонажа
logentity.changerolenamelog.userId=ID аккаунта
logentity.changerolenamelog.sid=Сервер
logentity.changerolenamelog.oldName=Старое имя
logentity.changerolenamelog.newName=Новое имя
logentity.changerolenamelog.modelId=ID предмета
logentity.changerolenamelog.platformName=Платформа

# bossdierelivelog
logentity.bossdierelivelog.bossId=ID босса
logentity.bossdierelivelog.mapId=ID карты
logentity.bossdierelivelog.type=Тип
logentity.bossdierelivelog.param=Убийца

# ranklistlog
logentity.ranklistlog.data=Дата
logentity.ranklistlog.rankKind=Тип рейтинга
logentity.ranklistlog.rank=Место
logentity.ranklistlog.roleId=ID персонажа
logentity.ranklistlog.roleName=Имя персонажа
logentity.ranklistlog.rankData=Данные рейтинга
logentity.ranklistlog.platformName=Платформа

# coinchangelog
logentity.coinchangelog.roleLevel=Уровень
logentity.coinchangelog.loginIp=IP
logentity.coinchangelog.moneyType=Тип валюты
logentity.coinchangelog.changeNum=Изменение
logentity.coinchangelog.reason=Код причины
logentity.coinchangelog.beforeNum=Количество до
logentity.coinchangelog.afterNum=Количество после
logentity.coinchangelog.actionId=Связанный ID

# maillog
logentity.maillog.mailAction=Тип операции с почтой
logentity.maillog.type=Тип письма
logentity.maillog.mailId=ID письма
logentity.maillog.receiveTime=Время получения
logentity.maillog.mailTitle=Заголовок письма
logentity.maillog.mailContend=Содержание письма
logentity.maillog.receiverId=ID получателя
logentity.maillog.receiverName=Получатель
logentity.maillog.attachment=Вложения