menu_1=Панель управления
menu_2=Управление пользователями
menu_3=Список пользователей
menu_4=Управление правами
menu_5=Словарь предметов
menu_6=Управление меню
menu_7=Список меню
menu_8=Управление поддержкой
menu_9=Данные игрока
menu_10=Перекрёстный поиск аккаунта и персонажа
menu_11=Управление операциями
menu_12=Операционные инструменты
menu_13=Логи процесса пополнения
menu_14=Генерация активационных кодов
menu_15=Логи изменения бонусных монет
menu_16=Логи действий пользователя
menu_17=Управление логами
menu_18=Поиск по логам
menu_19=Логи покупок в магазине
menu_20=Логи изменения монет
menu_21=Логи наград за активность
menu_22=Логи получения активностей
menu_23=Статистика удержания
menu_24=Управление объявлениями
menu_25=Управление блокировками
menu_26=Принудительный выход
menu_27=Блокировка чата
menu_28=Блокировка аккаунта
menu_29=Снятие блокировки чата
menu_30=Разблокировка аккаунта
menu_31=Мгновенное объявление
menu_32=Управление почтой
menu_33=Логи наград в подземельях
menu_34=Отправка почты
menu_35=Список почты
menu_36=Циклические объявления
menu_37=Информация о гильдии
menu_38=Ежедневные данные
menu_39=Почта при входе
menu_40=Онлайн (один сервер)
menu_41=Поиск активационных кодов
menu_42=Логи рейтинга
menu_43=Операционные активности
menu_44=Обычная активность пополнения
menu_45=Циклическая активность пополнения
menu_46=Обычная активность расходования
menu_47=Циклическая активность расходования
menu_48=Активность обмена
menu_49=Активность выпадения
menu_50=Активность убийства монстров
menu_51=Активность получения
menu_52=Праздничное дарение
menu_53=Праздничное получение
menu_54=Рейтинг пополнения (1 сервер)
menu_55=Рейтинг расходования
menu_56=Рейтинг дарения
menu_57=Рейтинг получения
menu_58=Проверка активностей
menu_59=Игровые операции
menu_60=Логи успешного пополнения
menu_61=Выполнение GM-команд
menu_62=Список серверов
menu_63=Список лог-баз
menu_64=Управление белым списком
menu_65=Участники гильдии
menu_66=Динамика гильдии
menu_67=Управление условиями мониторинга
menu_68=Статистика покупок в магазине
menu_69=Распределение по уровням
menu_70=Распределение по классам
menu_71=Рейтинги
menu_72=Рейтинг боевой мощи
menu_73=Рейтинг уровней
menu_74=Онлайн (все серверы)
menu_75=Данные бэкенда
menu_76=Загрузка данных бэкенда
menu_77=Статистика DAU
menu_78=Данные персонажа (по ID)
menu_79=Рейтинг богатства
menu_80=Рейтинг арены
menu_81=Рейтинг скакунов
menu_82=Рейтинг драконов
menu_83=Рейтинг плащей
menu_84=Статистика повторных платежей
menu_85=Статистика количества платежей
menu_86=Статистика накопленных платежей
menu_87=Статистика улучшения питомцев
menu_88=Поиск по логам чата
menu_89=Пополнение через бэкенд
menu_90=Список персонажей
menu_91=Системные переключатели
menu_92=Список подарков
menu_93=Перенос персонажа
menu_94=Логи регистрации на городскую битву
menu_95=Логи входа/выхода с поля боя
menu_96=Поиск активностей
menu_97=Статистика данных
menu_98=Логи смены имени
menu_99=Логи торговли
menu_100=Поиск активностей бэкенда
menu_101=Управление шаблонами активностей пополнения
menu_102=Управление шаблонами обычных активностей
menu_103=Логи бракосочетания
menu_104=Выполнение кросс-серверных GM-команд
menu_105=Списание предметов
menu_106=Инструменты администрирования
menu_107=Статистика оттока игроков
menu_108=Статистика пополнений игроков
menu_109=Рейтинг пополнений
menu_110=Статистика бонусных монет
menu_111=Статистика улучшения скакунов
menu_112=Чёрный список
menu_113=Активность ограниченных покупок
menu_114=Статистика LTV
menu_115=Статистика распределения сумм пополнений
menu_116=Статистика распределения по уровням
menu_117=Пополнение с выдачей предметов
menu_118=Статистика времени в сети
menu_119=Статистика использования монет
menu_120=Активность удвоения опыта с монстров
menu_121=Блокировка ключевых слов
menu_122=Списание монет
menu_123=Активность Небесной сокровищницы
menu_124=Логи городской битвы
menu_125=Список королевств
menu_126=Информация о королевстве
menu_127=Участники королевства
menu_128=Динамика королевства
menu_129=История выполнения GM-команд
menu_130=Статистика персонажей на всех серверах
menu_131=Логи времени жизни боссов
menu_132=Активность убийства боссов
menu_133=Логи входа в кросс-серверные подземелья
menu_134=Логи завершения кросс-серверных подземелий
menu_135=Поиск по кросс-серверным логам
menu_136=Логи персонажей в кросс-серверной войне
menu_137=Логи создания наград за битву
menu_138=Логи удаления наград за битву
menu_139=Логи создания комнат битвы
menu_140=Логи удаления комнат битвы
menu_141=Логи входа игрока в комнату
menu_142=Активность ограниченных покупок на сервер
menu_143=Логи входа в подземелья
menu_144=Настройка двойного пополнения
menu_145=Активность двойного пополнения
menu_146=Запрос к БД по отдельному подключению
menu_147=Настройки параметров сервера
menu_148=Статистика активности игроков в подземельях
menu_149=Логи заданий охоты
menu_150=Логи элитных боссов
menu_151=Логи бонусных монет
menu_152=Логи чести и военной заслуги
menu_153=Логи других валют
menu_154=Логи сюжетных заданий
menu_155=Ежедневные записи входа игрока
menu_156=Логи улучшения экипировки
menu_157=Логи улучшения звёзд экипировки
menu_158=Статистика сбора (скакуны, крылья, питомцы)
menu_159=Активность непрерывного пополнения
menu_160=Активность кросс-серверного рейтинга
menu_161=Активность первого убийства босса
menu_162=Обзор платежей
menu_163=Статистика первого пополнения
menu_164=Статистика потоков предметов и валют
menu_165=Активность ограниченной покупки
menu_166=Активность облачной покупки
menu_167=Поиск по инвентарю
menu_168=Группировка серверов
menu_169=Активность непрерывного входа
menu_170=Активность очков славы
menu_171=Активность сдачи материалов
menu_172=Логи изменения VIP
menu_173=Логи наград королевской битвы
menu_175=Кросс-серверные зоны
menu_176=Создание зон
menu_177=Состояние зон
menu_178=Статистика коммерческого контента
menu_179=Праздничные активности
menu_180=Активность шеринга
menu_181=Пополнение через бэкенд
menu_182=Проверка пополнений через бэкенд
menu_183=Список пополнений через бэкенд
menu_184=Статистика данных по серверам
menu_185=Актуальность списка серверов пополнения
menu_186=Проверка аватаров
menu_187=Пользовательские аватары
menu_188=Переключатель проверки аватаров