jsp.transfer.serverId=ID сервера
jsp.transfer.roleId=ID персонажа
jsp.transfer.srcUserId=ID исходного аккаунта
jsp.transfer.targetUserId=ID целевого аккаунта
jsp.transfer.reason=Причина операции

jsp.transfer.submit=Отправить
jsp.transfer.history=Показать последние 10 записей