############################################################
#gm平台数据库地址
gm.jdbc.url=jdbc:mysql://127.0.0.1:3306/tzj_gm?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
#gm数据库账号名
gm.jdbc.username=root
#gm数据库密码
gm.jdbc.password=4512kek4512
#gm http 端口
gm.http.port = 9321

#统计日志库数据库地址
stat.jdbc.url=jdbc:mysql://127.0.0.1:3306/tzj_stat_log?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
#统计日志库数据库账号名
stat.jdbc.username=root
#统计日志库数据库密码
stat.jdbc.password=4512kek4512
#拉取登录日志 时间间隔 单位（秒）
stat.login.log.corn=300
#拉取充值日志 时间间隔 单位（秒）
stat.recharge.log.corn=300
#拉取角色信息日志 时间间隔 单位（秒）
stat.roleState.log.corn=300
