# Конфигурация источников данных
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        druid:
            # Источник данных GM-админки
            master:
                url: jdbc:mysql://127.0.0.1:3306/tzj_gm?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
                username: root
                password: 4512kek4512
            # Источник данных статистики
            stat: # Источник данных статистики
                 url: jdbc:mysql://127.0.0.1:3306/tzj_stat_log?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
                 username: root
                 password: 4512kek4512
             # Источник данных логического сервера входа
            login:
                url: jdbc:mysql://127.0.0.1:3306/tzj_login?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
                username: root
                password: 4512kek4512
            # Начальное количество соединений
            initialSize: 5
            # Минимальное количество соединений в пуле
            minIdle: 10
            # Максимальное количество соединений в пуле
            maxActive: 20
            # Максимальное время ожидания получения соединения
            maxWait: 60000
            # Интервал проверки на необходимость закрытия простаивающих соединений (в миллисекундах)
            timeBetweenEvictionRunsMillis: 60000
            # Минимальное время жизни соединения в пуле (в миллисекундах)
            minEvictableIdleTimeMillis: 300000
            # Максимальное время жизни соединения в пуле (в миллисекундах)
            maxEvictableIdleTimeMillis: 900000
            # Проверка активности соединения
            validationQuery: SELECT 1 FROM DUAL
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
            webStatFilter: 
                enabled: true
            statViewServlet:
                enabled: true
                # Белый список IP (если не заполнен — доступ разрешён всем)
                allow:
                url-pattern: /druid/*
                # Имя пользователя и пароль для входа в консоль управления
                login-username: root
                login-password: 4512kek4512
            filter:
                stat:
                    enabled: true
                    # Запись медленных SQL-запросов
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: true
                wall:
                    config:
                        multi-statement-allow: true