db.backend.url=jdbc:mysql://127.0.0.1:3306/tzj_backend?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8
db.backend.username=root
db.backend.password=4512kek4512
db.backend.validationQuery=select 1
db.backend.maxActive=100
