db.loginLog.url=jdbc:mysql://127.0.0.1:3306/tzj_login_log?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8
db.loginLog.username=root
db.loginLog.password=o4W3TKCtvm5GYab3
db.loginLog.validationQuery=select 1
db.loginLog.maxActive=100