db.login.url=jdbc:mysql://127.0.0.1:3306/tzj_login?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8
db.login.username=root
db.login.password=o4W3TKCtvm5GYab3
db.login.validationQuery=select 1
db.login.maxActive=100