# Generated by Django 2.0.2 on 2020-07-07 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assets_type', models.CharField(choices=[('server', '服务器'), ('database', '数据库')], default='server', max_length=128, verbose_name='资产类型')),
                ('hostname', models.CharField(max_length=128, verbose_name='服务器名称')),
                ('wip', models.GenericIPAddressField(verbose_name='外网IP')),
                ('lip', models.GenericIPAddressField(verbose_name='内网IP')),
                ('os', models.CharField(max_length=128, verbose_name='服务器操作系统')),
                ('cup', models.CharField(max_length=8, verbose_name='服务器CPU')),
                ('memory', models.CharField(max_length=8, verbose_name='服务器内存')),
                ('disk', models.CharField(max_length=8, verbose_name='服务器磁盘')),
                ('buy_time', models.DateField(blank=True, null=True, verbose_name='购买时间')),
                ('expire_date', models.DateField(blank=True, null=True, verbose_name='过保修期')),
            ],
        ),
        migrations.CreateModel(
            name='AssetStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=8, verbose_name='服务器状态')),
            ],
        ),
        migrations.CreateModel(
            name='MachineRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(max_length=8, verbose_name='机房名称')),
                ('machine_address', models.CharField(max_length=128, verbose_name='机房地址')),
                ('machine_user', models.CharField(max_length=8, verbose_name='机房联系人')),
                ('machine_mail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=8, verbose_name='项目名称')),
                ('project_short_name', models.CharField(max_length=8, verbose_name='项目简称')),
            ],
        ),
        migrations.AddField(
            model_name='assets',
            name='machineroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.MachineRoom'),
        ),
        migrations.AddField(
            model_name='assets',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.ProjectAsset'),
        ),
        migrations.AddField(
            model_name='assets',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='assets.AssetStatus'),
        ),
    ]
