# Generated by Django 2.0.2 on 2020-07-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=8, verbose_name='渠道名称')),
                ('region_short_name', models.CharField(max_length=8, verbose_name='渠道简称')),
            ],
        ),
    ]
