roleTitle=角色重名
roleContent=亲爱的玩家：\n由于合服后导致您的角色存在重名情况，我们已为您发放改名卡，请您使用改名卡免费对您的角色进行改名，感谢您的支持，祝您游戏愉快！
guildTitle=帮会重名
guildContent=亲爱的玩家：\n由于合服后导致您的帮会存在重名情况，我们已为您发放改名卡，请您使用改名卡免费对您的帮会进行改名，感谢您的支持，祝您游戏愉快！
system=系统