roleTitle=Role Name Repetition
roleContent=Dear Player:\nDue To The Server Merger, You Encountered The Role Name Repetition But Don’t Worry, We Have Sent You A Card To Rename Your Role For Free. Thanks For Your Support!
guildTitle=Guild Name Repetition
guildContent=Dear Player:\nDue To The Server Merger, You Encountered The Guild Name Repetition But Don’t Worry, We Have Sent You A Card To Rename Your Guild For Free. Thanks For Your Support!
system=System

