roleTitle=ชื่อตัวละครซ้ำ
roleContent=ผู้เล่นที่รัก：\nเนื่องจากการรวมเซิร์ฟทำให้ตัวละครที่ท่านมีอยู่เกิดสถานะการณ์ชื่อซ้ำ เราจะมอบการ์ดแก้ชื่อให้กับท่าน กรุณาใช้การ์ดแก้ชื่อฟรีนี้ในการดำเนินการแก้ชื่อตัวละครของท่าน ขอขอบคุณที่ท่านให้การสนับสนุน ขอให้ท่านมีความสุขับการเล่นเกม!
guildTitle=ชื่อสำนักซ้ำ
guildContent=ผู้เล่นที่รัก：\nเนื่องจากการรวมเซิร์ฟทำให้สำนักของท่านเกิดสถานะการณ์ชื่อซ้ำ  เราจะมอบการ์ดแก้ชื่อให้กับท่าน กรุณาใช้การ์ดแก้ชื่อฟรีนี้ในการดำเนินการแก้ชื่อสำนักของท่าน ขอขอบคุณที่ท่านให้การสนับสนุน ขอให้ท่านมีความสุขับการเล่นเกม!
system=ระบบ