roleTitle=角色更名
roleContent=親愛的玩家：\n由於合服後導致您的角色存在名稱重複情況，我們已為您發放更名卡，請您使用更名卡對您的角色進行更名，感謝您的支持，祝您遊戲愉快！
guildTitle=幫會更名
guildContent=親愛的玩家：\n由於合服後導致您的幫會存在重複名稱情況，我們已為您發放更名卡，請您使用更名卡免費對您的幫會進行更名，感謝您的支持，祝您遊戲愉快！
system=系統