roleTitle=Trùng tên nhân vật
roleContent=Người chơi thân mến:\nDo sau khi gộp server nên tên nhân vật của bạn bị trùng tên, chúng tôi đã tặng thẻ đổi tên cho bạn, hãy dùng thẻ đổi tên để đổi tên n.vật của bạn, cảm ơn.
guildTitle=Trùng tên bang
guildContent=Người chơi thân mến:\nDo sau khi gộp server nên tên bang của bạn bị trùng tên, chúng tôi đã tặng thẻ đổi tên cho bạn, hãy dùng thẻ đổi tên để đổi tên bang của bạn, cảm ơn.
system=Hệ thống