#物品变化理由itemChangeReason
itemChange_-1=reason.itemChange_-1
itemChange_-2=reason.itemChange_-2
itemChange_-3=reason.itemChange_-3
itemChange_-4=reason.itemChange_-4
itemChange_-5=reason.itemChange_-5
itemChange_-6=reason.itemChange_-6
itemChange_-7=reason.itemChange_-7
itemChange_-8=reason.itemChange_-8
itemChange_1=reason.itemChange_1
itemChange_2=reason.itemChange_2
itemChange_3=reason.itemChange_3
itemChange_4=reason.itemChange_4
itemChange_5=reason.itemChange_5
itemChange_6=reason.itemChange_6
itemChange_7=reason.itemChange_7
itemChange_8=reason.itemChange_8
itemChange_9=reason.itemChange_9
itemChange_10=reason.itemChange_10
itemChange_11=reason.itemChange_11
itemChange_12=reason.itemChange_12
itemChange_13=reason.itemChange_13
itemChange_14=reason.itemChange_14
itemChange_15=reason.itemChange_15
itemChange_16=reason.itemChange_16
itemChange_17=reason.itemChange_17
itemChange_18=reason.itemChange_18
itemChange_19=reason.itemChange_19
itemChange_20=reason.itemChange_20
itemChange_21=reason.itemChange_21
itemChange_22=reason.itemChange_22
itemChange_23=reason.itemChange_23
itemChange_24=reason.itemChange_24
itemChange_25=reason.itemChange_25
itemChange_26=reason.itemChange_26
itemChange_27=reason.itemChange_27
itemChange_28=reason.itemChange_28
itemChange_29=reason.itemChange_29
itemChange_30=reason.itemChange_30
itemChange_31=reason.itemChange_31
itemChange_32=reason.itemChange_32
itemChange_33=reason.itemChange_33
itemChange_34=reason.itemChange_34
itemChange_35=reason.itemChange_35
itemChange_36=reason.itemChange_36
itemChange_37=reason.itemChange_37
itemChange_38=reason.itemChange_38
itemChange_39=reason.itemChange_39
itemChange_40=reason.itemChange_40
itemChange_41=reason.itemChange_41
itemChange_42=reason.itemChange_42
itemChange_43=reason.itemChange_43
itemChange_44=reason.itemChange_44
itemChange_45=reason.itemChange_45
itemChange_46=reason.itemChange_46
itemChange_47=reason.itemChange_47
itemChange_48=reason.itemChange_48
itemChange_49=reason.itemChange_49
itemChange_50=reason.itemChange_50
itemChange_51=reason.itemChange_51
itemChange_52=reason.itemChange_52
itemChange_53=reason.itemChange_53
itemChange_54=reason.itemChange_54
itemChange_55=reason.itemChange_55
itemChange_56=reason.itemChange_56
itemChange_57=reason.itemChange_57
itemChange_58=reason.itemChange_58
itemChange_59=reason.itemChange_59
itemChange_60=reason.itemChange_60
itemChange_61=reason.itemChange_61
itemChange_62=reason.itemChange_62
itemChange_63=reason.itemChange_63
itemChange_64=reason.itemChange_64
itemChange_65=reason.itemChange_65
itemChange_66=reason.itemChange_66
itemChange_67=reason.itemChange_67
itemChange_68=reason.itemChange_68
itemChange_69=reason.itemChange_69
itemChange_70=reason.itemChange_70
itemChange_71=reason.itemChange_71
itemChange_72=reason.itemChange_72
itemChange_73=reason.itemChange_73
itemChange_74=reason.itemChange_74
itemChange_75=reason.itemChange_75
itemChange_76=reason.itemChange_76
itemChange_77=reason.itemChange_77
itemChange_78=reason.itemChange_78
itemChange_79=reason.itemChange_79
itemChange_80=reason.itemChange_80
itemChange_81=reason.itemChange_81
itemChange_82=reason.itemChange_82
itemChange_83=reason.itemChange_83
itemChange_84=reason.itemChange_84
itemChange_85=reason.itemChange_85
itemChange_86=reason.itemChange_86
itemChange_87=reason.itemChange_87
itemChange_88=reason.itemChange_88
itemChange_89=reason.itemChange_89
itemChange_90=reason.itemChange_90
itemChange_91=reason.itemChange_91
itemChange_92=reason.itemChange_92
itemChange_93=reason.itemChange_93
itemChange_94=reason.itemChange_94
itemChange_95=reason.itemChange_95
itemChange_96=reason.itemChange_96
itemChange_97=reason.itemChange_97
itemChange_98=reason.itemChange_98
itemChange_99=reason.itemChange_99
itemChange_100=reason.itemChange_100
itemChange_101=reason.itemChange_101
itemChange_102=reason.itemChange_102
itemChange_103=reason.itemChange_103
itemChange_104=reason.itemChange_104
itemChange_105=reason.itemChange_105
itemChange_106=reason.itemChange_106
itemChange_107=reason.itemChange_107
itemChange_108=reason.itemChange_108
itemChange_109=reason.itemChange_109
itemChange_110=reason.itemChange_110
itemChange_111=reason.itemChange_111
itemChange_112=reason.itemChange_112
itemChange_113=reason.itemChange_113
itemChange_114=reason.itemChange_114
itemChange_115=reason.itemChange_115
itemChange_116=reason.itemChange_116
itemChange_117=reason.itemChange_117
itemChange_118=reason.itemChange_118
itemChange_119=reason.itemChange_119
itemChange_120=reason.itemChange_120
itemChange_121=reason.itemChange_121
itemChange_122=reason.itemChange_122
itemChange_123=reason.itemChange_123
itemChange_124=reason.itemChange_124
itemChange_125=reason.itemChange_125
itemChange_126=reason.itemChange_126
itemChange_127=reason.itemChange_127
itemChange_128=reason.itemChange_128
itemChange_129=reason.itemChange_129
itemChange_130=reason.itemChange_130
itemChange_131=reason.itemChange_131
itemChange_132=reason.itemChange_132
itemChange_133=reason.itemChange_133
itemChange_134=reason.itemChange_134
itemChange_135=reason.itemChange_135
itemChange_136=reason.itemChange_136
itemChange_137=reason.itemChange_137
itemChange_138=reason.itemChange_138
itemChange_139=reason.itemChange_139
itemChange_140=reason.itemChange_140
itemChange_141=reason.itemChange_141
itemChange_142=reason.itemChange_142
itemChange_143=reason.itemChange_143
itemChange_144=reason.itemChange_144
itemChange_145=reason.itemChange_145
itemChange_146=reason.itemChange_146
itemChange_147=reason.itemChange_147
itemChange_148=reason.itemChange_148
itemChange_149=reason.itemChange_149
itemChange_150=reason.itemChange_150
itemChange_151=reason.itemChange_151
itemChange_152=reason.itemChange_152
itemChange_153=reason.itemChange_153
itemChange_154=reason.itemChange_154
itemChange_155=reason.itemChange_155
itemChange_156=reason.itemChange_156
itemChange_157=reason.itemChange_157
itemChange_158=reason.itemChange_158
itemChange_159=reason.itemChange_159
itemChange_160=reason.itemChange_160
itemChange_161=reason.itemChange_161
itemChange_162=reason.itemChange_162
itemChange_163=reason.itemChange_163
itemChange_164=reason.itemChange_164
itemChange_165=reason.itemChange_165
itemChange_166=reason.itemChange_166
itemChange_167=reason.itemChange_167
itemChange_168=reason.itemChange_168
itemChange_169=reason.itemChange_169
itemChange_170=reason.itemChange_170
itemChange_171=reason.itemChange_171
itemChange_172=reason.itemChange_172
itemChange_173=reason.itemChange_173
itemChange_174=reason.itemChange_174
itemChange_175=reason.itemChange_175
itemChange_176=reason.itemChange_176
itemChange_177=reason.itemChange_177
itemChange_178=reason.itemChange_178
itemChange_179=reason.itemChange_179
itemChange_180=reason.itemChange_180
itemChange_181=reason.itemChange_181
itemChange_182=reason.itemChange_182
itemChange_183=reason.itemChange_183
itemChange_184=reason.itemChange_184
itemChange_185=reason.itemChange_185
itemChange_186=reason.itemChange_186
itemChange_187=reason.itemChange_187
itemChange_188=reason.itemChange_188
itemChange_189=reason.itemChange_189
itemChange_190=reason.itemChange_190
itemChange_191=reason.itemChange_191
itemChange_192=reason.itemChange_192
itemChange_193=reason.itemChange_193
itemChange_194=reason.itemChange_194
itemChange_195=reason.itemChange_195
itemChange_196=reason.itemChange_196
itemChange_197=reason.itemChange_197
itemChange_198=reason.itemChange_198
itemChange_199=reason.itemChange_199
itemChange_200=reason.itemChange_200
itemChange_201=reason.itemChange_201
itemChange_202=reason.itemChange_202
itemChange_203=reason.itemChange_203
itemChange_204=reason.itemChange_204
itemChange_205=reason.itemChange_205
itemChange_206=reason.itemChange_206
itemChange_207=reason.itemChange_207
itemChange_208=reason.itemChange_208
itemChange_209=reason.itemChange_209
itemChange_210=reason.itemChange_210
itemChange_211=reason.itemChange_211
itemChange_212=reason.itemChange_212
itemChange_213=reason.itemChange_213
itemChange_214=reason.itemChange_214
itemChange_215=reason.itemChange_215
itemChange_216=reason.itemChange_216
itemChange_217=reason.itemChange_217
itemChange_218=reason.itemChange_218
itemChange_219=reason.itemChange_219
itemChange_220=reason.itemChange_220
itemChange_221=reason.itemChange_221
itemChange_222=reason.itemChange_222
itemChange_223=reason.itemChange_223
itemChange_224=reason.itemChange_224
itemChange_225=reason.itemChange_225
itemChange_226=reason.itemChange_226
itemChange_227=reason.itemChange_227
itemChange_228=reason.itemChange_228
itemChange_229=reason.itemChange_229
itemChange_229=reason.itemChange_229
itemChange_230=reason.itemChange_230
itemChange_231=reason.itemChange_231
itemChange_232=reason.itemChange_232
itemChange_233=reason.itemChange_233
itemChange_234=reason.itemChange_234
itemChange_235=reason.itemChange_235
itemChange_236=reason.itemChange_236
itemChange_237=reason.itemChange_237
itemChange_238=reason.itemChange_238
itemChange_239=reason.itemChange_239
itemChange_240=reason.itemChange_240
itemChange_241=reason.itemChange_241
itemChange_242=reason.itemChange_242
itemChange_243=reason.itemChange_243
itemChange_244=reason.itemChange_244
itemChange_245=reason.itemChange_245
itemChange_246=reason.itemChange_246
itemChange_247=reason.itemChange_247
itemChange_248=reason.itemChange_248
itemChange_249=reason.itemChange_249
itemChange_250=reason.itemChange_250
itemChange_251=reason.itemChange_251
itemChange_252=reason.itemChange_252
itemChange_253=reason.itemChange_253
itemChange_254=reason.itemChange_254
itemChange_255=reason.itemChange_255
itemChange_256=reason.itemChange_256
itemChange_257=reason.itemChange_257
itemChange_258=reason.itemChange_258
itemChange_259=reason.itemChange_259
itemChange_260=reason.itemChange_260
itemChange_261=reason.itemChange_261
itemChange_262=reason.itemChange_262
itemChange_263=reason.itemChange_263
itemChange_264=reason.itemChange_264
itemChange_265=reason.itemChange_265
itemChange_266=reason.itemChange_266
itemChange_267=reason.itemChange_267
itemChange_268=reason.itemChange_268
itemChange_269=reason.itemChange_269
itemChange_270=reason.itemChange_270
itemChange_271=reason.itemChange_271
itemChange_272=reason.itemChange_272
itemChange_273=reason.itemChange_273
itemChange_274=reason.itemChange_274
itemChange_275=reason.itemChange_275
itemChange_276=reason.itemChange_276
itemChange_277=reason.itemChange_277
itemChange_278=reason.itemChange_278
itemChange_288=reason.itemChange_288
itemChange_289=reason.itemChange_289
itemChange_290=reason.itemChange_290
itemChange_291=reason.itemChange_291
itemChange_292=reason.itemChange_292
itemChange_293=reason.itemChange_293
itemChange_294=reason.itemChange_294
itemChange_295=reason.itemChange_295
itemChange_296=reason.itemChange_296
itemChange_297=reason.itemChange_297
itemChange_298=reason.itemChange_298
itemChange_299=reason.itemChange_299
itemChange_300=reason.itemChange_300
itemChange_301=reason.itemChange_301
itemChange_302=reason.itemChange_302
itemChange_303=reason.itemChange_303
itemChange_304=reason.itemChange_304
itemChange_305=reason.itemChange_305
itemChange_306=reason.itemChange_306
itemChange_307=reason.itemChange_307
itemChange_308=reason.itemChange_308
itemChange_309=reason.itemChange_309
itemChange_310=reason.itemChange_310
itemChange_311=reason.itemChange_311
itemChange_312=reason.itemChange_312
itemChange_313=reason.itemChange_313
itemChange_314=reason.itemChange_314
itemChange_315=reason.itemChange_315
itemChange_316=reason.itemChange_316
itemChange_317=reason.itemChange_317
itemChange_318=reason.itemChange_318
itemChange_319=reason.itemChange_319
itemChange_320=reason.itemChange_320
itemChange_321=reason.itemChange_321
itemChange_322=reason.itemChange_322
itemChange_323=reason.itemChange_323
itemChange_324=reason.itemChange_324
itemChange_325=reason.itemChange_325
itemChange_326=reason.itemChange_326
itemChange_327=reason.itemChange_327
itemChange_328=reason.itemChange_328
itemChange_329=reason.itemChange_329
itemChange_330=reason.itemChange_330
itemChange_331=reason.itemChange_331
itemChange_332=reason.itemChange_332
itemChange_333=reason.itemChange_333
itemChange_10000=reason.itemChange_10000
itemChange_100000=reason.itemChange_100000
#货币类型
moneyType_1=reason.moneyType_1
moneyType_2=reason.moneyType_2
moneyType_3=reason.moneyType_3
moneyType_4=reason.moneyType_4
moneyType_5=reason.moneyType_5
moneyType_6=reason.moneyType_6
moneyType_7=reason.moneyType_7
moneyType_8=reason.moneyType_8
moneyType_9=reason.moneyType_9
moneyType_10=reason.moneyType_10
moneyType_11=reason.moneyType_11
moneyType_12=reason.moneyType_12
moneyType_13=reason.moneyType_13
moneyType_14=reason.moneyType_14
moneyType_15=reason.moneyType_15
moneyType_16=reason.moneyType_16
moneyType_17=reason.moneyType_17
moneyType_18=reason.moneyType_18
moneyType_19=reason.moneyType_19
moneyType_20=reason.moneyType_20
moneyType_21=reason.moneyType_21
moneyType_22=reason.moneyType_22
moneyType_23=reason.moneyType_23
moneyType_24=reason.moneyType_24
moneyType_25=reason.moneyType_25
moneyType_26=reason.moneyType_26
moneyType_27=reason.moneyType_27
moneyType_28=reason.moneyType_28
moneyType_29=reason.moneyType_29
moneyType_30=reason.moneyType_30
moneyType_31=reason.moneyType_31
moneyType_32=reason.moneyType_32
#商城ID
shop_-1=reason.shop_-1
shop_1=reason.shop_1
shop_2=reason.shop_2
shop_3=reason.shop_3
shop_4=reason.shop_4
#充值理由
recharge_0=reason.recharge_0
recharge_1=reason.recharge_1
recharge_2=reason.recharge_2
recharge_3=reason.recharge_3
recharge_4=reason.recharge_4
#充值步骤
rechargeProcess_-1=reason.rechargeProcess_-1
rechargeProcess_-2=reason.rechargeProcess_-2
rechargeProcess_-3=reason.rechargeProcess_-3
rechargeProcess_-4=reason.rechargeProcess_-4
rechargeProcess_-5=reason.rechargeProcess_-5
rechargeProcess_-6=reason.rechargeProcess_-6
rechargeProcess_0=reason.rechargeProcess_0
rechargeProcess_1=reason.rechargeProcess_1
rechargeProcess_2=reason.rechargeProcess_2
rechargeProcess_3=reason.rechargeProcess_3
rechargeProcess_4=reason.rechargeProcess_4
rechargeProcess_5=reason.rechargeProcess_5
#坐骑升级结果
horseUpResult_0=reason.horseUpResult_0
horseUpResult_1=reason.horseUpResult_1
#披风升级结果
cloakUpResult_0=reason.cloakUpResult_0
cloakUpResult_1=reason.cloakUpResult_1
#装备强化类型
equipStrengType_0=reason.equipStrengType_0
equipStrengType_1=reason.equipStrengType_1
#角色技能升级
skillUp_0=reason.skillUp_0
skillUp_1=reason.skillUp_1
skillUp_-1=reason.skillUp_-1
#角色属性点变化
playerAttPointChange_0=reason.playerAttPointChange_0
playerAttPointChange_1=reason.playerAttPointChange_1
playerAttPointChange_2=reason.playerAttPointChange_2
playerAttPointChange_3=reason.playerAttPointChange_3
playerAttPointChange_4=reason.playerAttPointChange_4
#邮件类型
mailType_1=reason.mailType_1
mailType_2=reason.mailType_2
mailType_3=reason.mailType_3
#邮件操作
mailAction_1=reason.mailAction_1
mailAction_2=reason.mailAction_2
mailAction_3=reason.mailAction_3
mailAction_4=reason.mailAction_4
mailAction_5=reason.mailAction_5
#祈福类型
prayType_1=reason.prayType_1
prayType_2=reason.prayType_2
prayType_3=reason.prayType_3
#背包类型
bagCellType_1=reason.bagCellType_1
bagCellType_2=reason.bagCellType_2
#背包操作类型
bagActionType_0=reason.bagActionType_0
bagActionType_1=reason.bagActionType_1
bagActionType_2=reason.bagActionType_2
#副本扫荡类型
copyMapSweepType_0=reason.copyMapSweepType_0
copyMapSweepType_1=reason.copyMapSweepType_1
copyMapSweepType_2=reason.copyMapSweepType_2
copyMapSweepType_3=reason.copyMapSweepType_3
copyMapSweepType_101=reason.copyMapSweepType_101
copyMapSweepType_102=reason.copyMapSweepType_102
#聊天类型
chatType_0=reason.chatType_0
chatType_1=reason.chatType_1
chatType_2=reason.chatType_2
chatType_3=reason.chatType_3
#活动类型
activity_1=reason.activity_1
activity_2=reason.activity_2
activity_3=reason.activity_3
activity_4=reason.activity_4
activity_5=reason.activity_5
activity_6=reason.activity_6
activity_7=reason.activity_7
activity_8=reason.activity_8
activity_9=reason.activity_9
activity_10=reason.activity_10
activity_11=reason.activity_11
activity_12=reason.activity_12
activity_13=reason.activity_13
activity_14=reason.activity_14
activity_15=reason.activity_15
activity_16=reason.activity_16
activity_17=reason.activity_17
activity_18=reason.activity_18
activity_19=reason.activity_19
activity_20=reason.activity_20
activity_22=reason.activity_22
activity_23=reason.activity_23
activity_24=reason.activity_24
activity_25=reason.activity_25
activity_26=reason.activity_26
activity_27=reason.activity_27
activity_28=reason.activity_28
activity_29=reason.activity_29
activity_30=reason.activity_30
activity_32=reason.activity_32
activity_33=reason.activity_33
activity_34=reason.activity_34
#结婚类型
marriageType_0=reason.marriageType_0
marriageType_1=reason.marriageType_1
marriageType_2=reason.marriageType_2
marriageType_3=reason.marriageType_3
marriageType_4=reason.marriageType_4
#结婚操作
marriageAction_0=reason.marriageAction_0
marriageAction_1=reason.marriageAction_1
#玩家交易动作
tradeAction_1=reason.tradeAction_1
tradeAction_2=reason.tradeAction_2
tradeAction_3=reason.tradeAction_3
tradeAction_4=reason.tradeAction_4
tradeAction_5=reason.tradeAction_5
tradeAction_6=reason.tradeAction_6
#城市战阵营，防守方0、攻方1、攻方2
cityWarCamp_0=reason.cityWarCamp_0
cityWarCamp_1=reason.cityWarCamp_1
cityWarCamp_2=reason.cityWarCamp_2
#王府官员类型
kpOfficialType_0=reason.kpOfficialType_0
kpOfficialType_1=reason.kpOfficialType_1
kpOfficialType_2=reason.kpOfficialType_2
kpOfficialType_3=reason.kpOfficialType_3
kpOfficialType_4=reason.kpOfficialType_4
kpOfficialType_5=reason.kpOfficialType_5
#王府捐献类型
kpDonateType_1=reason.kpDonateType_1
kpDonateType_2=reason.kpDonateType_2
kpDonateType_3=reason.kpDonateType_3
#王府基本信息修改类型
kpBaseInfoModifyType_0=reason.kpBaseInfoModifyType_0
kpBaseInfoModifyType_1=reason.kpBaseInfoModifyType_1
kpBaseInfoModifyType_2=reason.kpBaseInfoModifyType_2
#公会基本操作类型
guildAction_1=reason.guildAction_1
guildAction_2=reason.guildAction_2
guildAction_3=reason.guildAction_3
guildAction_4=reason.guildAction_4
guildAction_5=reason.guildAction_5
guildAction_6=reason.guildAction_6
guildAction_7=reason.guildAction_7
guildAction_8=reason.guildAction_8